### ISSUE TITLE
[glsl-in] #version parsing incomplete

### ISSUE THREAD

**Issue by magcius** [gfx-rs/naga#1002]
`#version 440` does not work, but `#version 440 core` does. Both forms are supported by the GLSL language spec.

**Comment by JCapucho** [comment]
This seems to be working can you share the beginning of the shader (like 5 to 10 lines)

**Comment by magcius** [comment]
```
#version 440
precision medium float;
#define VERT
#define attribute in
#define varying out
#define mainVS main
#define VIEWPORT_ORIGIN_TL 1
#define gl_VertexID gl_VertexIndex
```

The error I get is "Invalid profile precision"

**Comment by JCapucho** [comment]
This is a problem with the way the preprocessor currently passes information about directives and the fact that precision is handled as a identifier and not a keyword
