### ISSUE TITLE
Naga panics translating valid WGSL to SPIR-V

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/naga#1017]
This may be a duplicate, but filing it just in case: The following WGSL program passes validation, but panics in `back/spv/writer.rs`:

```
fn loop_switch_continue(x: i32) {
   loop {
       switch (x) {
           case 1: {
               continue;
           }
       }
   }
}
```

The failing code is the `unwrap` [here](https://github.com/gfx-rs/naga/blob/64b9e4501576bf5fecdb60c6375b191becbaa992/src/back/spv/writer.rs#L2583):

```
crate::Statement::Continue => {
    block.termination =
        Some(Instruction::branch(loop_context.continuing_id.unwrap()));
}
```

**Comment by jimblandy** [comment]
I think it'll be a challenge to generate SPIR-V for this. SPIR-V §2.11, "Structured Control Flow", includes this rule:

> each header block must strictly dominate its merge block, unless the merge block is unreachable in the CFG

Control flow in shaders is required to be structured, which means that the WGSL `switch` statement gets translated into a SPIR-V `OpSelectionMerge` followed by an `OpSwitch`. The rule quoted above implies that the `continue` cannot simply be translated into an `OpBranch` to the `loop`'s continue target.

I'll see what `glslangValidate` does with similar GLSL code.

**Comment by jimblandy** [comment]
Okay, I was misunderstanding the rule:

Although the header block must strictly dominate the merge block, that does not imply that all paths much reach the merge block, as I had incorrectly inferred. There is no requirement that the merge block post-dominate the header block.

**Comment by jimblandy** [comment]
Given this GLSL:

```
#version 450

int f(int q) { return q + 1; }

void main() {
  int i;
  for (i = 0; i < 10; i++) {
       switch (i & 3) {
           case 1: {
               continue;
           }
       }

       i = f(i);
   }
}
```

we get the following SPIR-V for the body of `main`:

```
         %19 = OpLabel
               OpLoopMerge %21 %22 None
               OpBranch %23

         %23 = OpLabel
         %24 = OpLoad %int %i
         %27 = OpSLessThan %bool %24 %int_10
               OpBranchConditional %27 %20 %21

         %20 = OpLabel
         %28 = OpLoad %int %i
         %30 = OpBitwiseAnd %int %28 %int_3
               OpSelectionMerge %32 None
               OpSwitch %30 %32 1 %31

         %31 = OpLabel
               OpBranch %22

         %32 = OpLabel
         %36 = OpLoad %int %i
               OpStore %param %36
         %37 = OpFunctionCall %int %f_i1_ %param
               OpStore %i %37
               OpBranch %22

         %22 = OpLabel
         %38 = OpLoad %int %i
         %39 = OpIAdd %int %38 %int_1
               OpStore %i %39
               OpBranch %19

         %21 = OpLabel
               OpReturn
               OpFunctionEnd
```

And this validates just fine.

**Comment by Gordon-F** [comment]
I think this wgsl also connected with this issue:
```wgsl
[[stage(compute), workgroup_size(1)]]
fn main() {
    var pos: i32 = 0;
    switch (pos) {
        case 1: {
            break;
        }
    }
}
```

panic here: https://github.com/gfx-rs/naga/blob/64b9e4501576bf5fecdb60c6375b191becbaa992/src/back/spv/writer.rs#L2579
