### ISSUE TITLE
Passing uniform through parameter works on vulkan, not dx12

### ISSUE THREAD

**Issue by Dispersia** [gfx-rs/naga#1027]
Example shader:

```
[[block]]
struct Foo {
    bar: f32;
};

[[group(0), binding(0)]] var<uniform> foo: Foo;

fn accept_foo(foo: Foo) -> f32 {
    return foo.bar;
}

[[stage(vertex)]]
fn vs_main() -> [[builtin(position)]] vec4<f32> {
    let temp = accept_foo(foo);

    return vec4<f32>(temp, 0.0, 0.0, 0.0);
}

[[stage(fragment)]]
fn fs_main() -> [[location(0)]] vec4<f32> {
    return vec4<f32>(0.0, 0.0, 0.0, 0.0);
}
```

the passing foo uniform to accept_foo works on vulkan, but not directx. I don't know if it should be allowed or not, i just simply change to use the global in accept_foo instead, but might be nice to have validation around it or if it can transform it instead

small repo if it's helpful: https://github.com/Dispersia/naga_pass_uniform , just change VULKAN to DX12

**Comment by kvark** [comment]
Thank you for filing!

It doesn't seem to be a Naga issue, is it? wgpu/gfx do not yet use Naga's new HLSL backend, so the translation on DX12 goes through SPIRV-Cross. Therefore, as long as the SPIR-V is valid (which you can check by running `spirv-val` on it), this is a bug in SPIRV-Cross.
Note: we are re-implementing the backends now in `wgpu-hal`, and we'll not use SPIRV-Cross at all.

I think the issue can be closed on this. Please feel free to re-open or continue discussion!

**Comment by Dispersia** [comment]
Thank you for the response, you are correct this is not a Naga issue, I thought it was [wgsl -> naga -> hlsl -> spirv-cross], I didn't realize spirv-cross was for going the other way. I will file an issue on their repo instead (as you are also correct the spv is valid)
