### ISSUE TITLE
Rosetta testing method

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#105]
We have many front-ends, many back-ends, and we need to test them all using the a limited number of shaders in the tree (in `test-data`), and we need to do it in a way that is straightforward and extendable. Here is an idea on how to do it, inspired by [Rosetta stone](https://en.wikipedia.org/wiki/Rosetta_Stone).

Steps:
  1. We select a number of shaders (or shader modules, to be precise), e.g. deferred shaders, forward shaders, flat shaders, compute boids, etc.
  2. For each we compose the "canonical" IR (e.g. by parsing the shaders from one of the languages).
  3. We then write the same shader (each of them) in *all* the front-ends that we can test, and the tests ensure that parsing those sources produces the same IR (possibly with #41).
  4. We also test conversion from IR of this shader (for each of them) to all the backends. If the backend format also has a front-end, we just compare it with the shader we wrote in (3). If it doesn't, we write a shader (e.g. MSL one) and compare against that.

The main idea is to bring structure to the tested material, so that we know how to write the tests and configure them. Basically, the test suite is a collection of those base IR shaders. For each we can define a list of front-ends to test (with the source files) and a list of back-ends to test (with the source files), plus possibly some configuration tables.

One way to structure this is `test-data/boids/` folder having all of `shader.wgsl`, `shader.spv`, `shader.glsl`, `config.ron` (testing configuration), and `shader.ron` (the IR).

Caveats:
  - Classy glsl -> SPIR-V conversion doesn't support multiple entry points, so that could limit the variety of modules we use for testing. However, I think *our* GLSL parser can be configured to support multiple entry points with low effort, so we should do it, resolving the issue.

**Comment by pjoe** [comment]
I like this idea ♥

I'm not sure if there are some issues in practice, but guess we just have to try it out:

- Is there always a "canonical" IR, or can things like ordering or different handle IDs differ, while output is still valid? Maybe some of this can be fixed by post-processing IR, e.g. abstracting out handle IDs.

- Will round-trip e.g. WGSL > IR > WGSL always produce the same? Or do we have cases where the IR doesn't capture all details of the input, or again ordering might differ?

**Comment by kvark** [comment]
Good concerns, thank you for evaluating this!
For ordering in canonical IR: we don't have many unoredered sets/maps, and ones we have are likely to be populated with the same elements in the same order. So it could be that we don't need to do anything specific. We'll see ;)

> Will round-trip e.g. WGSL > IR > WGSL always produce the same? 

That's an interesting concern. It's not clear to me if it couldn't be possible. The main point of this testing method is focusing on IR, so once we fixed IR, we can generated WGSL, and then just make sure that parsing that WGSL produces the same IR.

**Comment by pjoe** [comment]
All for giving it a try, and then possibly adjusting as we go along :)

For ref: had some similar challenges working on tests for the Blender glTF exporter. We had issues with buffer views and accesser indices not always being the same, so ended up de-referencing those before comparing test results. Of course we also ended up having blender 2.79 and 2.80 exporting actual vertex data in different order, which kind of broke the idea of comparing those.

**Comment by pjoe** [comment]
I did some initial experimentation, you can see here: https://github.com/pjoe/naga/tree/rosetta-experiment/test-data/simple

Still fighting with issues of different expressions ordering

**Comment by pjoe** [comment]
I think I managed to get glsl-new in line, except for expression ordering.

I'm however fighting to understand how wgsl orders expressions :S

For glsl I have:
```glsl
#version 450 core

layout(location = 0) in vec2 a_pos;
layout(location = 0) out vec4 o_pos;

void main() {
    float w = 1.0;
    o_pos = vec4(a_pos, 0.0, w);
}
```
which translates to following expression order:
```js
[
Constant(1), // w initialiser 1.0
GlobalVariable(2), // o_pos
GlobalVariable(1), // a_pos
Constant(2), // 0.0
LocalVariable(1), // w
Compose(ty: 2, components: [3, 4, 5,]),
],
```

However for wgsl I get:
```wgsl
# vertex
[[location 0]] var<in> a_pos : vec2<f32>;
[[location 0]] var<out> o_pos : vec4<f32>;

fn main() -> void {
  var w: f32 = 1.0;
  o_pos = vec4<f32>(a_pos, 0.0, w);
}
entry_point vertex as "main" = main;
```
and expressions:
```js
[
GlobalVariable(2), // o_pos
GlobalVariable(1), // a_pos
Constant(1), // w initialiser 1.0
LocalVariable(1), // w
Constant(2), // 0.0
Compose(ty: 2, components: [1, 5, 4,]),
],
```

So I don't understand:
- why is the w initialiser expression inserted later than it's declaration statement ?
- why does the reference to local var `w` come before the 0.0 constant ?

**Comment by kvark** [comment]
Some insight on the WGSL logic. In the prelude of a function, it registers expressions for *all* global variables, so that it can access them later. This is unlike GLSL, where you are adding them lazily to the expression list. The benefit here is that if the WGSL parser sees an identifier, it can look it up *always* in the expression map, or otherwise it's an error. This simplifies the parser, and makes it faster to lookup identifiers.

You might have a concern here: if a function has expressions for all the globals, doesn't it breaks the static analysis of what globals are used? Answer is NO, because the analysis (and we have it in `proc`) iterates statements, and expressions used from them, recursively. It doesn't care about expressions that are not linked from any statements at the top level.

**Comment by pjoe** [comment]
@kvark: okay that explains the first part. Should be possible to do similar for GLSL (always add global vars first when parsing a function definition).

But what about the second one - why the LocalVar(w) before the constant(0.0) ... is that the same thing? Will it also add an expression for a LocalVar as soon as it's defined?

**Comment by kvark** [comment]
I think the second part is a bug in WGSL frontend. Expressions should not depend on ones that go after them.

**Comment by pjoe** [comment]
Oh, I don't think there is any dependency issue, looks to me like it simply does:
```wgsl
var w: f32 = 1.0;
```
becomes
```js
Constant(1), // w initialiser 1.0
LocalVariable(1), // w
```
And then when it reaches the compose, the only thing that isn't already in the expression list is the 0.0 constant.

Starting to make a bit of sense to me :)

**Comment by pjoe** [comment]
Managed to make glsl-new use same order (at least for the simple example) in #147.

Check out this: https://github.com/pjoe/naga/blob/rosetta-experiment/test-data/simple/simple-ron.diff (an empty diff). glsl-new now generates identical IR to wgsl 🚀

**Comment by kvark** [comment]
Thinking about this some more, trying to converge all the frontends into a single IR could be possible, but it's work that no end user needs, it's only a change to ease the testing. Instead of making this a requirement, we should make it a preference, thus allowing SPIR-V frontend to diverge, for example.

Here is an updated test plan.  We'll not have separate "tests" for multiple backends/frontends, but rather
- each frontend would have a map of inputs -> IRs. Sharing of IRs in encouraged/preferred (e.g. between GLSL and WGSL).
- each backend would have a map of IRs -> outputs. It doesn't have to use all the IRs, just a representative subset is fine.

We can move the test files (all except RON for IR) into the backend/frontent folders.
