### ISSUE TITLE
[wgsl-out] Can produce functions without return statements at the end

### ISSUE THREAD

**Issue by magcius** [gfx-rs/naga#1053]
See also https://github.com/gpuweb/gpuweb/issues/1897

If the spec is changed, then no action is needed here. But for the current spec, Naga should return zero-initialized value so that a return statement is the last statement of a WGSL function.

**Comment by kvark** [comment]
I'm fairly confident the spec is just wrong here. No changes needed on our side, but it's good to keep an issue open to track this.

**Comment by teoxoy** [comment]
I think we can close this since https://github.com/gpuweb/gpuweb/issues/2317 got merged.

**Comment by magcius** [comment]
Sounds good.
