### ISSUE TITLE
[wgsl-in][msl-out] Type inferring for “var”

### ISSUE THREAD

**Issue by munrocket** [gfx-rs/naga#1058]
This is obvious issue and probably exist somewhere, but I didn’t found.

Type inferring not works with “var” currently.
```rs
let a = vec3<f32>(1.);
var b = floor(a); //<- gives an error
```

The same story with “let”, we can’t explicitly choose type for it.
```rs
let a: f32 = 42.; //<- gives an error
```
As I know let/var should work the same with inferring. And the only difference between them is mutability.

This is the reason why triangle not rendering right now (at least on macos) http://austin-eng.com/webgpu-samples
P.S. I will try to fix webgpu-samples for firefox, so in future maybe triangle will work correctly.

**Comment by hcsch** [comment]
Running `naga-cli` compiled from the current code from the master branch (a35de06f33f43b3a44ab911143c35dd630b00893) on
```wgsl
fn main() {
    let a = vec3<f32>(1.);
    var b = floor(a);
}
```
gives me
```metal
// language: metal1.1
#include <metal_stdlib>
#include <simd/simd.h>


void main1(
) {
    metal::float3 b;
    metal::float3 a = metal::float3(1.0);
    b = metal::floor(a);
    return;
}
```
without errors and correctly inferred types.
Same with
```wgsl
fn main() {
    let a: f32 = 42.;
    var b = min(1., a);
}
```
which results in
```metal
// language: metal1.1
#include <metal_stdlib>
#include <simd/simd.h>


void main1(
) {
    float b;
    b = metal::min(1.0, 42.0);
    return;
}
```
(the `min` is so at least something showing the let was there is emitted, since the `let` gets eliminated)

Based on the above, I think this is fixed now.

**Comment by kvark** [comment]
Oh yes, thank you!

**Comment by munrocket** [comment]
This is really huge! Thanks!
Waiting for shipping in Firefox Nightly 🎉🎉🎉
