### ISSUE TITLE
[wgsl-in] Syntax to declare access modes differs from spec

### ISSUE THREAD

**Issue by SNCPlay42** [gfx-rs/naga#1129]
The spec gives [this](https://gpuweb.github.io/gpuweb/wgsl/#variable-declaration) grammar for variable declarations:

```
variable_decl
  : VAR variable_qualifier? variable_ident_decl

variable_qualifier
  : LESS_THAN storage_class ( COMMA access_mode )? GREATER_THAN
```

With the [usage example](https://gpuweb.github.io/gpuweb/wgsl/#example-8803e357):

```
[[group(0), binding(1)]
var<storage,read_write> buf3: Buffer; // Can both read and write.
```

But naga does not support this syntax:

```
error: expected '>', found ','
  ┌─ wgsl:3:12
  │
3 │ var<storage, read> x: Block;
  │            ^ expected '>'
```

In the tests in this repository I found this syntax:

https://github.com/gfx-rs/naga/blob/cc91c77f7ac7e22b615bf2e188f659ce623c1fe9/tests/in/collatz.wgsl#L7

The spec does not define an `[[access]]` attribute.

Also, the spec [says](https://gpuweb.github.io/gpuweb/wgsl/#access-mode-defaults) the access mode of a storage variable defaults to `read`, but naga currently treats a storage variable with no `[[access]]` attribute as apparently permitting no access; this code

```
[[block]] struct Block {
	values: vec4<f32>;
};

[[group(0), binding(0)]]
var<storage> x: Block;

[[stage(vertex)]]
fn shader() {
	let v = x.values;
}
```

Gives the validation error

```
Entry point shader at Vertex is invalid:
        Global variable [1] is used incorrectly as READ
```

**Comment by kvark** [comment]
This is a new change in WGSL spec that we haven't caught up to, yet.

**Comment by hcsch** [comment]
I think this has been fixed by now, right? Based on `git blame`, probably somewhere around 2f516c0932d1e4684d4f4f38b3941345336751ed.

See the same test in the current code base: https://github.com/gfx-rs/naga/blob/f11afd4fcf16350cba29cfdac5f09ef9df7a57a7/tests/in/collatz.wgsl#L6-L7

**Comment by kvark** [comment]
Indeed, #1142, thank you for triaging!
