### ISSUE TITLE
[glsl-out] No inout or out qualifiers in GLSL output

### ISSUE THREAD

**Issue by ElArtista** [gfx-rs/naga#1147]
Currently glsl output misses parameter qualifiers in original code.
For example, the function:
```
float intersect_sphere(vec3 ro, vec3 rd, vec2 db, vec4 sp, out vec3 nm)
```
comes out as:
```
float intersect_spherevf3vf3vf2vf4vf3_(vec3 ro1, vec3 rd1, vec2 db1, vec4 sp, vec3 nm1)
```
according to RenderDoc.

**Comment by Gordon-F** [comment]
This case might be a problem for naga IR, because currently, it doesn't have an in\out attribute for function arguments.

https://github.com/gfx-rs/naga/blob/2f516c0932d1e4684d4f4f38b3941345336751ed/src/lib.rs#L973-L981

**Comment by ElArtista** [comment]
Its a pretty basic and important functionality for the glsl output.
Note that I pre-compiled the shader at build time (with build.rs) with shaderc to spv if that makes any difference.
I would love to provide a PR with some guidance!

**Comment by kvark** [comment]
@Gordon-F this isn't a problem with Naga's IR. We aren't going to have "out" and "inout" parameters in the IR. Instead, we have pointers.
