### ISSUE TITLE
Parse shaders with half-precision floats (float16)

### ISSUE THREAD

**Issue by lyricwulf** [gfx-rs/naga#1149]
When using 16bit float storage and arithmetic extensions:
```glsl
#extension GL_EXT_shader_16bit_storage : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : enable
```

Shader compiles to spv without issue, but trying to create a wgpu shader module:
```
[WARN wgpu_core::device] Failed to parse shader SPIR-V code for Some("shader.comp.spv"): UnsupportedCapability(Float16)
```

**Comment by kvark** [comment]
If you want to use them from wgpu, you'd also need a feature inside wgpu to be exposed/enabled first. WebGPU group has it on the radar for the nearest future, but it's not there yet. See https://github.com/gpuweb/gpuweb/issues/658

**Comment by TimothyBergstrom** [comment]
> If you want to use them from wgpu, you'd also need a feature inside wgpu to be exposed/enabled first. WebGPU group has it on the radar for the nearest future, but it's not there yet. See https://github.com/gpuweb/gpuweb/issues/658


Two relatively new PRs have added f16 for WebGPU



https://github.com/gpuweb/gpuweb/pull/2696

https://github.com/gpuweb/gpuweb/pull/2647

**Comment by teoxoy** [comment]
Support for f16 for wgpu has been merged in https://github.com/gfx-rs/wgpu/pull/2646.
Let's track f16 support for WGSL in https://github.com/gfx-rs/naga/issues/1884.
