### ISSUE TITLE
Change frexp and modf to work with structures

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#1161]
See https://github.com/gpuweb/gpuweb/pull/1973
I think this change needs to be done at IR level.

**Comment by kvark** [comment]
Similar work needs to be done for atomic compare+exchange - https://github.com/gpuweb/gpuweb/pull/2113
I think all of this should wait for #1419 first.

**Comment by kvark** [comment]
This isn't urgent for the release.

**Comment by cwfitzgerald** [comment]
Currently bumping up against this when targeting WebGPU, as wgpu's water example uses modf.

**Comment by kvark** [comment]
This should be simpler now that #2256 is in, which contains infra to create IR structure types.
