### ISSUE TITLE
SPIRV Shader Struct Size Mismatch

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/naga#1177]
If I parse the following spirv with naga, I get an error:

[spirv.zip](https://github.com/gfx-rs/naga/files/6957748/spirv.zip) (contains spirv and preprocessed source GLSL)
[IR.txt](https://github.com/gfx-rs/naga/files/6957726/IR.txt)

```
Type [12] 'ObjectOutputData' is invalid: 
        Structure member[0] at 0 and size 64 crosses the structure boundary of size 16
```

The spirv is being generated from GLSL. The relevant usages:

```glsl
struct ObjectOutputData {
    mat4 model_view;
    mat4 model_view_proj;
    mat3 inv_trans_model_view;
    uint material_idx;
};
layout(set = 1, binding = 0, std430) readonly buffer ObjectOutputDataBuffer {
    ObjectOutputData object_output[];
};
```

**Comment by kvark** [comment]
Ok, I see. The structure is represented twice in IR: once as a layout-full structure, and once as a layout-less one.
The layout-less has zero offsets for all members, and the span of 16 (shouldn't matter).
We need to tweak the generator for this layout-less texture to use a different span.
