### ISSUE TITLE
Updating `rspirv` crate

### ISSUE THREAD

**Issue by Jasper-Bekkers** [gfx-rs/naga#1187]
Creating this ticket since we had some breakage in this project the last time we tried to update `rspirv`. This was tracked in https://github.com/gfx-rs/rspirv/issues/196 but we'd like to announce it here as well since we're planning on pushing a new update to `rspirv` soon (with a seperate `spirv` crate instead of `spirv_headers`).

Historically the semver handing of rspirv hasn't been ... great, which is something we're working on fixing but I thought I'd give a small heads up at least.

**Comment by Jasper-Bekkers** [comment]
@kvark we have just pushed `rspirv 0.9.0` and `spirv 0.1.0`.

**Comment by kvark** [comment]
I'm having a bit of an issue updating
>warning: /Users/dmalyshau/Code/naga/Cargo.toml: version requirement `0.1.0+1.5.4` for dependency `spirv` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
warning: /Users/dmalyshau/Code/naga/Cargo.toml: version requirement `0.1.0+1.5.4` for dependency `spirv` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
    Updating crates.io index
  Downloaded spirv v0.1.0
error: failed to verify the checksum of `spirv v0.1.0`

**Comment by kvark** [comment]
Stripping the "+1.5.4" removes the warnings but I'm left with
> failed to verify the checksum of `spirv v0.1.0`

**Comment by Jasper-Bekkers** [comment]
Yeah, you're not supposed to specify the metadata with the version.

The checksum issue is a bit odd - we didn't get that issue when publishing a new rspirv update.

**Comment by kvark** [comment]
Removing everything with `cargo-cache -r all` doesn't help either. And I'm seeing this on an empty project (just adding `spirv = "0.1"` dependency). Something is fishy here.

**Comment by Jasper-Bekkers** [comment]
@kvark I seem to be getting the same issue locally - I'll investigate.

**Comment by Jasper-Bekkers** [comment]
Seems related to https://github.com/rust-lang/cargo/issues/7180

**Comment by Jasper-Bekkers** [comment]
Seems like there used to be an old version of `spirv` at 0.1.0 that `cargo fetch` compares against incorrectly. I'll just release a `0.2.0` and that should work :crossed_fingers:

**Comment by kvark** [comment]
Thanks! Unfortunately, now rspirv also needs to be updated, since it still tries to drag in the old spirv-0.1.0

**Comment by Jasper-Bekkers** [comment]
Pushed a new version of `rspirv` now as well. I'll close this as it looks like there wasn't any major fallout from this release. Further issues can be discussed on the `rspirv` repo directly.

**Comment by kvark** [comment]
Thanks! Just as I needed this. Naga-0.6 is also released now, using the new spirv crate.
