### ISSUE TITLE
[hlsl-out] Unimplemented write_value_type Pointer 

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/naga#1192]
On this rather complex spirv fragment shader, trying to output HLSL causes the following error:

[opaque.frag.cpu.zip](https://github.com/gfx-rs/naga/files/6976977/opaque.frag.cpu.zip)

> Internal error in FRAGMENT shader: HLSL: Unimplemented("write_value_type Pointer { base: [1], class: Function }")

You can repro using naga-cli easily.

**Comment by teoxoy** [comment]
This has been fixed in e59582469c586b99f025fa99508964d9026746b9 (as part of #1193).
While the linked shader now fails validation on latest master, this is already tracked by #1358.
