### ISSUE TITLE
Compile the validation out of an executable

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#1213]
For tools like glsl-to-wgsl, which gets deployed on the web as a WASM module, validation isn't actually needed. If anything is wrong, the translation may fail with a panic, or produce bad WGSL, neither of which is critical for this case.

**Comment by Gordon-F** [comment]
Should the validation module be under a separate feature? It will reduce the compilation time, reduce the size of the library (a little, but this is important for the web target).

**Comment by kvark** [comment]
When I did #1429, the size reduction for WASM was really tiny.
However, I think it still makes sense. For example, we may start depending on petgraph for the uniform control flow analysis - #605. In this case, `validation` would trigger the `petgraph` to be included.

If you are interested to drive this to completion, this is a welcome move! And we'll probably want to include it into 0.7 release.
