### ISSUE TITLE
[wgsl-in] Better error message for assignment to function argument

### ISSUE THREAD

**Issue by hcsch** [gfx-rs/naga#1228]
When assigning a value to a function argument like in the following code for example:
```wgsl
fn assign_to_argument(a: vec2<f32>) {
    a = vec2<f32>(0.0);
}
```
the error naga outputs talks about a mismatch of types, rather than an assignment to a name that may not be assigned to (though I haven't found any particular part in the spec describing this particular situation about non-pointer function arguments):
```
Function [1] 'assign_to_argument' is invalid: 
	Store of [3] into [1] doesn't have matching types
```

It is probably better if the error specifically mentions that assignment to a function argument is not valid (and perhaps also, that a variable should be created for this or a pointer used as the argument type).

**Comment by teoxoy** [comment]
This has been fixed by https://github.com/gfx-rs/naga/pull/1367

This is the error we now output:

```cmd
error: the left-hand side of an assignment must be a reference
   ┌─ test.wgsl:63:38
   │  
63 │   fn assign_to_argument(a: vec2<f32>) {
   │ ╭─────────────────────────────────────^
64 │ │     a = vec2<f32>(0.0);
   │ ╰─────^ expression is not a reference
```
