### ISSUE TITLE
Are Bitcast Expressions Not Supported in WGSL?

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/naga#1229]
Looking at the [Reinterpretation of Representation Expressions](https://gpuweb.github.io/gpuweb/wgsl/#bitcast-expr) section of the WGSL spec, if I'm interpreting it correctly, it seems like you should be able call `bitcast<f32>(my_i32_value)` to interpret the bits of an `i32` as an `f32`, but it seems that naga doesn't recognize the `bitcast` expression. Am I understanding the spec correctly?

I have a situation where I need to be able to bitcast from i32 to f32 and vice-versa, but I couldn't find a way to do that in WGSL with naga. If this is just something that needs to be implemented I'd be glad to do it.

**Comment by kvark** [comment]
Indeed! Good news is, IR has `Expression::As { convert: false }` for this, so it's just a matter of exposing the `bitcast` function from WGSL.

**Comment by zicklag** [comment]
OK, great! That looks like it will be easy.
