### ISSUE TITLE
Can We "Polyfill" U32/I32 Bitcast in the GLSL Backend?

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/naga#1230]
I have a situation where I need to be able to interpret the bits of an `i32` as a `u32` and vice-versa without doing a conversion, but I found this line in the GLSL backend that makes it look like that won't work for GLSL:

https://github.com/gfx-rs/naga/blob/6ab6d6fc46684b16bc493d06aab094361b0598f0/src/back/glsl/mod.rs#L2334

Would it be possible to write our own GLSL function that would do an equivalent ( even if it was slower or something ) to a bitcast for `i32` and `u32` and then use that instead of the constructor conversion?

**Comment by JCapucho** [comment]
That comment is very misleading what it's trying to say is that there's isn't a special function, normal constructors already do bitcast.

**Comment by zicklag** [comment]
Ah, great! OK, then I've got no worries there. :) Thanks. :+1:
