### ISSUE TITLE
Validation error detecting loop in CFG

### ISSUE THREAD

**Issue by HeroicKatora** [gfx-rs/naga#1257]
This shader that pases the `spirv-val` tools contains, according to `naga`, a fatal control flow loop:

https://gist.github.com/HeroicKatora/bad60a304fabc676ac26c1c75c1ea11a

```
./target/release/naga frag.spv 
cycle detected in the CFG during traversal at 353
```

This (obvioulsy) caused error switching to `wgpu = 0.10`.

**Comment by JCapucho** [comment]
Fixed by #1294
