### ISSUE TITLE
Incorrect translation of spirv with float64 (dvec2)

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/naga#1272]
KAS's [mandlebrot example](https://github.com/kas-gui/kas/tree/master/examples/mandlebrot) does not render with 64-bit shaders (`--features shader64`) since upgrading to wgpu v0.10 (leaving a black background, which is not the clear colour). It runs correctly with 32-bit shaders (almost identical code aside from the fragment shader).

An API trace is attached: [trace.tar.gz](https://github.com/gfx-rs/naga/files/7025630/trace.tar.gz)

Using `wgpu::Features::SPIRV_SHADER_PASSTHROUGH` the example works correctly, therefore I deduce the error lies with Naga rather than (other parts of) WGPU. The following patch achieves this:
```diff
diff --git a/examples/mandlebrot/mandlebrot.rs b/examples/mandlebrot/mandlebrot.rs
index bf1b202b..03e23cbb 100644
--- a/examples/mandlebrot/mandlebrot.rs
+++ b/examples/mandlebrot/mandlebrot.rs
@@ -45,10 +45,12 @@ impl Shaders {
         let vertex = device.create_shader_module(&include_spirv!("shader.vert.spv"));
         // Note: we don't use wgpu::include_spirv since it forces validation,
         // which cannot currently deal with double precision floats (dvec2).
-        let fragment = device.create_shader_module(&wgpu::ShaderModuleDescriptor {
-            label: Some("fragment shader"),
-            source: wgpu::util::make_spirv(FRAG_SHADER),
-        });
+        let fragment = unsafe {
+            device.create_shader_module_spirv(&wgpu::ShaderModuleDescriptorSpirV {
+                label: Some("fragment shader"),
+                source: wgpu::util::make_spirv_raw(FRAG_SHADER),
+            })
+        };
 
         Shaders { vertex, fragment }
     }
@@ -94,7 +96,9 @@ impl CustomPipeBuilder for PipeBuilder {
     fn device_descriptor() -> wgpu::DeviceDescriptor<'static> {
         wgpu::DeviceDescriptor {
             label: None,
-            features: wgpu::Features::PUSH_CONSTANTS | SHADER_FLOAT64,
+            features: wgpu::Features::PUSH_CONSTANTS
+                | wgpu::Features::SPIRV_SHADER_PASSTHROUGH
+                | SHADER_FLOAT64,
             limits: wgpu::Limits {
                 max_push_constant_size: size_of::<PushConstants>().cast(),
                 ..Default::default()
```

Tested on: Fedora 34 x86_64 RX570

**Comment by teoxoy** [comment]
I tried the latest version of the [example](https://github.com/kas-gui/kas/tree/149e34ffa3d09cffe3321f6c9b74316288404448/examples/mandlebrot) and noticed it's working. I narrowed it down to naga v0.7.2 which gets it going.

I believe this has been fixed by https://github.com/gfx-rs/naga/pull/1515.
