### ISSUE TITLE
Error compiling the shader "Naga parsing: InvalidGlobalVar(FunctionArgument(2))"

### ISSUE THREAD

**Issue by HolgerGottChristensen** [gfx-rs/naga#1275]
I am trying to compile and run the triangle example for [https://github.com/fintelia/smaa-rs](https://github.com/fintelia/smaa-rs). 
When running this it compiles fine, but fails the fragment shader at runtime with a validation error:
``` 
[2021-08-21T23:53:28Z ERROR wgpu::backend::direct] wgpu error: Validation Error
    
    Caused by:
        In Device::create_render_pipeline
          note: label = `smaa.pipeline.edge_detect`
        Internal error in FRAGMENT shader: Error compiling the shader "Naga parsing: InvalidGlobalVar(FunctionArgument(2))"
```

I am running on macOS 10.15 and the spirV has been compiles with shaderrc. Below I have included the spirV that fails to run.

[shader.smaa.shader.edge_detect.frag.spv.zip](https://github.com/gfx-rs/naga/files/7026373/shader.smaa.shader.edge_detect.frag.spv.zip)

I will try to provide more information if needed.

**Comment by JCapucho** [comment]
What version of wgpu/Naga are you using?

**Comment by HolgerGottChristensen** [comment]
I am using wgpu v0.9.0 and naga v0.5.0. I have just tried the exact same code (with the same crate versions) on a windows machine, where it runs fine and does not fail with the same errors.

**Comment by JCapucho** [comment]
This is fixed in 0.6, could you try with it

**Comment by HolgerGottChristensen** [comment]
This might be a wgpu question then, but is there a way to make wgpu 0.9 use naga 0.6?

**Comment by JCapucho** [comment]
No since they aren't semver compatible you'll need to use wgpu 0.10 or patch the naga dependency to point to a commit that has the patch but it's still considered 0.5 (I don't recommend doing this, you'll miss on other fixes)

**Comment by HolgerGottChristensen** [comment]
I have updated the project to use wgpu 0.10 and naga 0.6, and it gets further before hitting issues.
It now does not return a validation error but panics the parsing with a very similar error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidGlobalVar(LocalVariable([3]))'

stack backtrace:
4: <wgpu::backend::direct::Context as wgpu::Context>::device_create_shader_module
             at /Users/holgergottchristensen/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/backend/direct.rs:978:30
   5: wgpu::Device::create_shader_module
             at /Users/holgergottchristensen/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/lib.rs:1633:17
   6: smaa::shader::ShaderSource::get_shader
             at ./src/shader.rs:206:9
   7: smaa::Pipelines::new
             at ./src/lib.rs:318:22
   8: smaa::SmaaTarget::new
             at ./src/lib.rs:648:25
   9: triangle::main
             at ./examples/triangle.rs:33:27
```
Below I have included the new spv that fails.
[shader.smaa.shader.blending_weight.frag.spv.zip](https://github.com/gfx-rs/naga/files/7027512/shader.smaa.shader.blending_weight.frag.spv.zip)

**Comment by HolgerGottChristensen** [comment]
As a small comment, it seems to work when using the wgpu v0.9 cross feature.

**Comment by HolgerGottChristensen** [comment]
Thank you so much for the work done to fix this and to the quick responses. It has been a pleasure :D
