### ISSUE TITLE
Preprocessor for glsl-new

### ISSUE THREAD

**Issue by lachlansneff** [gfx-rs/naga#132]
I threw together a quick, partial implementation of the glsl preprocessor (notably doesn't support `#if` or `#elif` because I didn't want to implement constant expression evaluation) for bevy ([here](https://github.com/bevyengine/bevy/blob/a47749c794761cc4c13879a1638a77cecaa06804/crates/bevy_render/src/shader/preprocessor.rs)) because the `glsl-new` frontend doesn't have one. I'm happy to donate this to naga if it's wanted as a starting  point.

**Comment by pjoe** [comment]
Initial code in #238

**Comment by fintelia** [comment]
I think this is resolved?

**Comment by kvark** [comment]
@pjoe had concerns about the way we have it currently. I think the question still remains open, although it would be great to spell out all the details here.

**Comment by kvark** [comment]
#238 got merged
