### ISSUE TITLE
WGSL back end generates incorrect code for address-of expressions

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/naga#1322]
(Bug description revised).

Passing the following WGSL through Naga IR:

```
fn f(i: ptr<function, i32>) {}

fn g() {
  var x = 10;
  f(&x);
}
```

produces the following incorrect output:

```
fn f(i: ptr<function, i32>) {
    return;
}

fn g() {
    var x: i32 = 10;

    f(x);
    return;
}
```

Specifically, the passing of `x` to `f` is ill-typed: the `&` operator has been dropped.

---

Original, incorrect bug report:

Passing the following WGSL through Naga IR:

```
fn f(i: i32) -> i32 {
  var x = i;
  var p = &x;
  return i;
}
```

produces the following incorrect output:

```
fn f(i: i32) -> i32 {
    var x: i32;
    var p: ptr<function, i32>;

    x = i;
    p = x;
    return i;
}
```

Specifically, the assignment of `x` to `p` is ill-typed: the `&` operator has been dropped.

**Comment by kvark** [comment]
> var p = &x;

I don't think you can do this in WGSL. It doesn't make sense for pointers to be variables.

**Comment by jimblandy** [comment]
> I don't think you can do this in WGSL. It doesn't make sense for pointers to be variables.

Oops, that's true. How about this:

```
fn f(i: ptr<function, i32>) {}

fn g() {
  var x = 10;
  f(&x);
}
```

That compiles to this, which is still incorrect:

```
fn f(i: ptr<function, i32>) {
    return;
}

fn g() {
    var x: i32 = 10;

    f(x);
    return;
}
```

**Comment by kvark** [comment]
Right, we are missing "&" at function call arguments

**Comment by jimblandy** [comment]
I have [a fix](https://github.com/jimblandy/naga/tree/wgsl-address-of-with-split) for this, but I think it could be done more clearly and with a lot less code churn.
