### ISSUE TITLE
[hlsl-out] D3DCompile error: syntax error: unexpected token 'texture'

### ISSUE THREAD

**Issue by zachreizner** [gfx-rs/naga#1336]
I noticed the `unexpected token 'texture'` error while using wgpu and wgsl on Windows. Digging into it, I noticed the generated shader had the reserved `texture` keyword in a generated helper:

```hlsl
int2 NagaDimensions2D(Texture2D<float4> texture)
{
    uint4 ret;
    texture.GetDimensions(0, ret.x, ret.y, ret.z);
    return ret.xy;
}
```

It seems this `texture` name was coming from this line of code: https://github.com/gfx-rs/naga/blob/ce676cf13090b87e1405640ea8ee43e1a1666005/src/back/hlsl/help.rs#L247

As an experiment, I changed the name to another name that was not a reserved keyword. The result was that the error went away, and my shader worked as expected.

**Comment by kvark** [comment]
Thank you for filing!
What is the exact error you are seeing?

**Comment by zachreizner** [comment]
The exact error I got was:

```
    Caused by:
        In Device::create_render_pipeline
          note: label = `label`
        Internal error in VERTEX shader: D3DCompile error (0x80004005): C:\Users\Zach\rivos\corvis\Shader@0x00000285BD8B0D10(51,41-47): error X3000: syntax error: unexpected token 'texture'
    C:\Users\Zach\rivos\corvis\Shader@0x00000285BD8B0D10(54,5-11): error X3086: untyped textures are deprecated in strict mode
```
