### ISSUE TITLE
[glsl-in] Shader rejected with "Argument ... value ... doesn't match the type ..."

### ISSUE THREAD

**Issue by afd** [gfx-rs/naga#1341]
Tested using naga 7681f4a21f554412dad494809855edb8367f8994

[This shader](https://github.com/gfx-rs/naga/files/7144188/binarysearch_tree.json.frag.txt) is accepted by glslangValidator, but with naga it leads to a type error.

**Comment by JCapucho** [comment]
Could you please provide a smaller shader that reproduces the bug

**Comment by afd** [comment]
@JCapucho Sure thing. Here is a small shader tat leads to the type error:

```
#version 450

struct BST {
 int data;
} ;

BST tree[1] = BST[1](BST(1));

void main()
{
}
```

**Comment by JCapucho** [comment]
That shader leads to a different error (thanks for providing a test case for it) which I already have a fix incoming, but you main shader has a different error.

**Comment by afd** [comment]
Ah, good catch - I used glsl-reduce and didn't make the interestingness test require the original type error to occur.

Here's a small example that causes the original error:

```
#version 450

struct BST {
 int data;
} ;

BST tree[1];

void makeTreeNode(inout BST tree)
{
}
void main()
{
 tree[0].data = 2;
 makeTreeNode(tree[0]);
}
```
