### ISSUE TITLE
SPIR-V Validation Error 'Constant [10] is invalid'

### ISSUE THREAD

**Issue by timokoesters** [gfx-rs/naga#1345]
```
ERROR wgpu::backend::direct > wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `shader.comp.spv`
    Constant [10] '' is invalid
    The type doesn't match the constant
```

Shader is here: https://github.com/timokoesters/nbodysim/blob/5688c5319a9af9d6217bd024db12e9becd7c3412/src/shader.comp, I compiled it using `glsl_to_spirv::compile(cs, glsl_to_spirv::ShaderType::Compute)`

**Comment by kvark** [comment]
Not able to reproduce this. Naga master is happy to validate this module.

**Comment by timokoesters** [comment]
I was using naga v0.6.3

**Comment by kvark** [comment]
Still "Validation Successful" if I convert it using cli. Perhaps, you didn't specify the FLOAT64 capability, and the error is just misleading?

**Comment by timokoesters** [comment]
That was indeed the problem. Thank you for your help
