### ISSUE TITLE
Comparing types

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#1385]
Today, the validation code does "best effort" to compare types. It does so by resolving the `TypeInner` and comparing it by value. This isn't enough for pointers and arrays though (structural composite types), since the `TypeInner` would refer to the handle of the base type, which can be different.

**Comment by jimblandy** [comment]
#1419 changes the type arenas to use `IndexSet`, ensuring that each type occurs only once in the arena, so `Eq` on `Handle<Type>` is the same as `Eq` on `Type`.
