### ISSUE TITLE
Any plans to publish `naga-cli`?

### ISSUE THREAD

**Issue by mitchmindtree** [gfx-rs/naga#1394]
I've found the CLI super useful for converting old GLSL and SPIR-V shaders to WGSL. It would be handy if one could grab it via `cargo install naga-cli` (or `fetchCrate` on Nix). Are there any plans to publish the tool?

**Comment by mitchmindtree** [comment]
Ahh my apologies, after double checking I realise it already is! Though with the bin name `naga`.

**Comment by kvark** [comment]
It might be the older one though.
