### ISSUE TITLE
Incorrect shader passthrough of SPIR-V with fallthrough switch

### ISSUE THREAD

**Issue by HeroicKatora** [gfx-rs/naga#1403]
Passing SPIR-V shaders to naga and back alters their effects.

This bug affects the `stage` shader, a term I use to describe converting an integer encoded texel to its full 4-component floating point format. This makes heavy use of switch-case for essentially choosing one conversion function based on input parameters. [https://github.com/HeroicKatora/stealth-paint/blob/wgpu-0.10/src/shaders/stage.frag](https://github.com/HeroicKatora/stealth-paint/blob/e3d7b586102851df08482b3df8c112c58e703a8d/src/shaders/stage.frag)

The critical section is here, which is utilized while decoding Oklab colors to rgb.

```glsl
vec4 parts_normalize(vec4 components, uint parts) {
  switch (parts) {
// .. lines skipped
  case SAMPLE_PARTS_Lab:
  case SAMPLE_PARTS_LCh:
    return vec4(c.xyz, 1.0);
  case SAMPLE_PARTS_LabA:
  case SAMPLE_PARTS_LChA:
    return c.xyzw;
  }
  return BIT_DECODE_FAIL; // vec4(1.0, 0.0, 0.0, 1.0)
}
```

Expected:
![oklab-good](https://user-images.githubusercontent.com/5550310/134059475-e3b4e0f7-1c5b-486a-9d80-3c943fbc803a.png)

Actual:
![oklab-bad](https://user-images.githubusercontent.com/5550310/134059763-09fafba8-4f84-456f-aefc-cefc863ae6f5.png)

To understand why we must have a small understanding of `Lab` color spaces. The first component is `lightness` and the second and third are chromaticities. So, full white would correspond to `1.0, 0.0, 0.0`. Familiar? Yes. Indeed this render pipeline includes invoking the above `parts_normalize` with `parts = SAMPLE_PARTS_LChA`. However this seems to instead reach to statement _below_ and returns `BIT_DECODE_FAIL`. (I've validated that by switching the default return value to `c.xyzw` as well).

I have also uploaded a fix that simply does not use fallthrough behavior at all, which also works. [This is the full patch](https://github.com/HeroicKatora/stealth-paint/pull/15/commits/a24928ce657a5aa6507f9f889db6bd06cde4c1bb).

```glsl
vec4 parts_normalize(vec4 components, uint parts) {
  switch (parts) {
// .. lines skipped
  case SAMPLE_PARTS_Lab:
    return vec4(c.xyz, 1.0);
  case SAMPLE_PARTS_LCh:
    return vec4(c.xyz, 1.0);
  case SAMPLE_PARTS_LabA:
   return c.xyzw;
  case SAMPLE_PARTS_LChA:
    return c.xyzw;
  }
  return BIT_DECODE_FAIL; // vec4(1.0, 0.0, 0.0, 1.0)
}
```

## Additional information

Reproduce: Run the test suite [here](https://github.com/HeroicKatora/stealth-paint), see `tests/debug/oklab.png.crc` output (a png image).

```bash
# Enables SPIR-V passthrough, works okay.
STEALTH_PAINT_PASSTHROUGH=1 STEALTH_PAINT_BLESS=1 cargo test
# Goes through Naga, fails
STEALTH_PAINT_BLESS=1 cargo test
```

Version information:
```toml
naga = { git = "https://github.com/gfx-rs/naga", rev = "60d0bf850b5bfeb87aeb5a0d4db6bb4059f80290" }
```
[Cargo.lock.gz](https://github.com/gfx-rs/naga/files/7198423/Cargo.lock.gz)

**Comment by HeroicKatora** [comment]
Note: Despite all the shaders mentioned in my bug reports being under MPL-2.0 in their source repository, I'm its sole contributors with full righst and you can use any of them for test suites and such. Just aks about any specific versions you would need.

**Comment by JCapucho** [comment]
I talked with jimb about this, spir-v allows cases to appear in any order in the switch header, naga doesn't reorder them yet, honestly I didn't expect any tool to do this but the more you know.
