### ISSUE TITLE
Glsl's `mod` should not be translated to metal `fmod`

### ISSUE THREAD

**Issue by thenlevy** [gfx-rs/naga#1410]
Translating this glsl [fragment shader](https://github.com/thenlevy/ensnano/blob/3aa82992518018f2c61944ceadbf3867bd563397/src/flatscene/view/background.frag) to spriv (using `glslc`) then to metal (using `naga` for the spirv -> metal ) or directly to metal (using only `naga`for glsl -> spriv ) results in a metal shader where the `mod` instruction has been translated into a `metal::fmod` instruction.

According to https://stackoverflow.com/questions/7610631/glsl-mod-vs-hlsl-fmod this is incorrect as `mod(x,y)` and `fmod(x, y)` have different values when `x/y <= 0`

PS:  I don't think that this is a glsl-in issue because on platforms that don't use `metal`, the shader works as expected.

**Comment by JCapucho** [comment]
So what would be the appropriate here? `BinaryOperator::Remainder`?

**Comment by teoxoy** [comment]
Has been resolved by https://github.com/gfx-rs/naga/pull/1867.
