### ISSUE TITLE
[glsl-in] array length is inferred as `Sint` in type and `Uint` in expression

### ISSUE THREAD

**Issue by jakobhellermann** [gfx-rs/naga#1446]
The code
```glsl
void main() {
    vec4 offset[2] = vec4[](vec4(0.0), vec4(0.0));
}
```
fails to compile because of
```glsl
Function [1] 'main' is invalid: 
	Local variable [1] 'offset' is invalid
	Initializer doesn't match the variable type
```

Looking at the types, the only difference is the type of the array length constant:

Local variable `offset` array length:
```rust
[1]: Constant {
	name: None,
	specialization: None,
	inner: Scalar {
		width: 4,
		value: Sint(
			2,
		),
	},
}
```
Initializer expression type array length:
```rust
[3]: Constant {
	name: None,
	specialization: None,
	inner: Scalar {
		width: 4,
		value: Uint(
			2,
		),
	},
}
```

The token for the 2 in `offset[2]` as returned by `pp-rs` is
```rust
Integer {
    value: 2,
    signed: true,
    width: 32,
}
```

**Comment by jakobhellermann** [comment]
Should both be `Sint`s or `Uint`s?

**Comment by jakobhellermann** [comment]
```glsl
vec4 offset[2] = { vec4(0.0), vec4(0.0) };
```
works.

**Comment by kvark** [comment]
Let's settle on `uint` as the array size in the IR. Supporting both seems more trouble than it's worth.

**Comment by JCapucho** [comment]
> ```glsl
> vec4 offset[2] = { vec4(0.0), vec4(0.0) };
> ```
> 
> works, but when running `naga repro.frag out.frag` it results in
> 
> ```glsl
> vec4 offset[2] = vec4(vec4(0.0, 0.0, 0.0, 0.0), vec4(0.0, 0.0, 0.0, 0.0));
> ```
This is an issue in glsl-out please open an issue for it
