### ISSUE TITLE
[wgsl-in] Redefinition incorrectly passes validation

### ISSUE THREAD

**Issue by Herschel** [gfx-rs/naga#1480]
Naga allows reusing a name in the same scope:

```
fn foo() {}
fn foo() {}

[[block]]
struct Globals {
    bar: vec4<f32>;
};

[[group(0), binding(0)]]
var<uniform> a: Globals;
[[group(0), binding(1)]]
var<uniform> a: Globals;
```
This passes validation in Naga, but this is not allowed by the [WGSL spec](https://www.w3.org/TR/WGSL/#declaration-and-scope):
 > A declaration must not introduce a name when that identifier is already in scope with the same end scope as another instance of that name.

Tint rejects the code with this message:
```
d:\projects\naga\color.wgsl:2:1 error: redefinition of 'foo'
fn foo() {}
^^

d:\projects\naga\color.wgsl:1:1 note: previous definition is here
fn foo() {}
^^
```

I hit this because [learn wgpu book](https://github.com/sotrh/learn-wgpu/blob/master/code/beginner/tutorial3-pipeline/src/shader.wgsl) uses `main` for both vertex and fragment entry points. Tint disagrees with this, so I was caught by surprise when my shader worked in wgpu desktop but not Chrome.

naga @ https://github.com/gfx-rs/naga/commit/5cf11ab73429f4b64cda6617459e7eca379f4135

**Comment by jimblandy** [comment]
I think this was fixed in [dba6beb](https://github.com/gfx-rs/naga/commit/dba6beb941aaf89436b57f14d6fc405da612e6e5). If that's not the case, please re-open.
