### ISSUE TITLE
[wgsl-in] Keywords should not be allowed for identifiers

### ISSUE THREAD

**Issue by Herschel** [gfx-rs/naga#1481]
This code passes validation in Naga:
```
[[group(0), binding(0)]]
var sampler: sampler;
```

The [WGSL spec](https://www.w3.org/TR/WGSL/#identifiers) says:
 > The form of an identifier is defined via pattern-matching, except that an identifier must not have the same spelling as a keyword or as a reserved word.

Tint rejects with this error:
```
d:\projects\naga\color.wgsl:2:5 error: expected identifier for variable declaration
var sampler: sampler;
    ^^^^^^^
```

naga @ https://github.com/gfx-rs/naga/commit/5cf11ab73429f4b64cda6617459e7eca379f4135

**Comment by jimblandy** [comment]
I think this was fixed in [2107b20](https://github.com/gfx-rs/naga/commit/2107b205619dfa329214bfcbe1b6b5dd38445966). If that's not the case, please re-open.
