### ISSUE TITLE
[wgsl-out] Missing `flat` qualifiers on vertex outputs or fragment inputs

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/naga#1491]
Chrome Canary complains when I pass a naga-converted shader to it:

```
1 warning(s) generated while compiling the shader:
21:21 warning: integral user-defined vertex outputs must have a flat interpolation attribute
    [[location(3)]] member1: u32;
                    ^^^^^^^
```

Same for fragment intputs. We seem to just be missing `[[interpolate(flat)]]`.

**Comment by teoxoy** [comment]
Opened https://github.com/gpuweb/gpuweb/issues/2760 to clarify the requirement (all user-defined IO vs user-defined vertex outputs and fragment inputs).

**Comment by expenses** [comment]
I've been running into this problem with the shipped version of WebGPU in Chrome Canary. I'll try and cook up a fix.

**Comment by expenses** [comment]
Here are examples of manual changes I've had to make:

```diff
diff --git a/single_view_fragment.spv.wgsl b/testing/single_view_fragment.spv.wgsl
index a410794..71e2045 100644
--- a/single_view_fragment.spv.wgsl
+++ b/testing/single_view_fragment.spv.wgsl
@@ -266,7 +266,7 @@ fn function() {
 }

 @fragment
-fn single_view__fragment(@location(0) param: vec3<f32>, @location(1) param_1: vec3<f32>, @location(2) param_2: vec2<f32>, @location(3) param_3: vec2<f32>, @location(5) param_4: u32, @builtin(front_facing) param_5: bool, @location(4) param_6: u32) -> @location(0) vec4<f32> {
+fn single_view__fragment(@location(0) param: vec3<f32>, @location(1) param_1: vec3<f32>, @location(2) param_2: vec2<f32>, @location(3) param_3: vec2<f32>, @location(5) @interpolate(flat) param_4: u32, @builtin(front_facing) param_5: bool, @location(4) @interpolate(flat) param_6: u32) -> @location(0) vec4<f32> {
     global_2 = param;
     global_3 = param_1;
     global_4 = param_2;
```

```diff
diff --git a/single_view_vertex.spv.wgsl b/testing/single_view_vertex.spv.wgsl
index 0afa948..5f013e1 100644
--- a/single_view_vertex.spv.wgsl
+++ b/testing/single_view_vertex.spv.wgsl
@@ -56,8 +56,8 @@ struct VertexOutput {
     @location(1) member_2: vec3<f32>,
     @location(2) member_3: vec2<f32>,
     @location(3) member_4: vec2<f32>,
-    @location(4) member_5: u32,
-    @location(5) member_6: u32,
+    @location(4) @interpolate(flat) member_5: u32,
+    @location(5) @interpolate(flat) member_6: u32,
 }

 var<private> global: vec4<f32>;
```

**Comment by expenses** [comment]
https://gpuweb.github.io/gpuweb/wgsl/ says
>User-defined [vertex](https://gpuweb.github.io/gpuweb/wgsl/#vertex) outputs and [fragment](https://gpuweb.github.io/gpuweb/wgsl/#fragment) inputs of scalar or vector integer type [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) always be specified as @_interpolate(flat).

So do we just revert https://github.com/gfx-rs/naga/pull/1103?

I've pushed https://github.com/gfx-rs/naga/compare/master...expenses:naga:wgsl-out-interpolate-flat. It seems to work for my shaders but I'm not sure if it's correct.

**Comment by teoxoy** [comment]
We already check that user-defined vertex outputs and fragment inputs of integer type use flat interpolation in the validator.

https://github.com/gfx-rs/naga/blob/1421a5e1ab5ca66ecdd1c03998fb0a712ec92bdf/src/valid/interface.rs#L333-L336

So, https://github.com/gfx-rs/naga/commit/07afcced39451e8f15d11bdae890e0bba468c1e7 (reverting https://github.com/gfx-rs/naga/pull/1103) sounds good to me.
