### ISSUE TITLE
[glsl-in] naga rejects use of clamp in constant initializer

### ISSUE THREAD

**Issue by afd** [gfx-rs/naga#1498]
This shader is legal in GLSL 4.5:

```
#version 450

const int x = clamp(1, 1, 1);

void main()
{
}
```

because builtins such as clamp are allowed in constant expressions if invoked with constant expression arguments (see "4.3.3 Constant Expressions" in the GLSL 4.5 spec).

naga (revision 9d2b357214dacce0fe30587844d4c7bf41b51773) rejects the example with:

```
error: const values must have an initializer
```

**Comment by sjinno** [comment]
I would like to work on this issue if it's okay :) @jimblandy will be mentoring me.
