### ISSUE TITLE
How well are varyings optimized out?

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/naga#1509]
Hi!

Could someone please help me figure out to what extend varyings (are they still called that way?) are optimized out?

Consider the following code, where `out.a`  and `out.b` will be interpolated. In this case, will the compiler figure out that `b` is not used, and omit it?
```
        struct VertexOutput {
            [[location(0)]] a: vec3<f32>;
            [[location(1)]] b: vec3<f32>;
        };

        [[stage(vertex)]]
        fn vs_main(...) -> VertexOutput {
             ...
             var out : VertexOutput ;
             out.a = something;
             out.b = something_else;
        }

        [[stage(fragment)]]
        fn fs_main1(in: VertexOutput) -> FragmentOutput {
             ...
             does_something_with(in.a);  // but does not use b
        }
``` 

Second question: now consider adding another fragment entrypoint to the same shader (compiled into the same shader module), which *does* use `b`. Will this affect whether `b` is interpolated for `fs_main1`?
```
        [[stage(fragment)]]
        fn fs_main2(in: VertexOutput) -> FragmentOutput {
             ...
             does_something_with(in.a, in.b);
        }
```

**Comment by kvark** [comment]
There is no optimization in place to remove the varyings. If it's a part of the entry point interface, then it's considered used.

**Comment by ElectronicRU** [comment]
That kind of optimization is usually late-stage and happens in the driver once you assemble the pipeline. Before that, you can mix and match shaders for different stages arbitrarily, so there's no telling which is used and which is not.

**Comment by almarklein** [comment]
Right. I now see that Naga can never make this optimization. At the time that it becomes known what combination of entrypoints is used (i.e. when the pipeline is created), Naga has already generated the driver-specific shader code.

Then my question becomes: can I assume that the driver will make this optimization? Or will it depend on the driver?

**Comment by almarklein** [comment]
The context for this question: at [pygfx](https://github.com/pygfx/pygfx) we have vertex shaders that each have multiple corresponding fragment shaders, which differ slightly and may not use all varyings. I could try to extend our templating/codegen to optimize out unused varyings, but if it's reasonable to assume that drivers already do this, then we could keep our shader-system simpler (and safe me a ton of work) :)

**Comment by jimblandy** [comment]
Questions like this come up a lot. Since graphics drivers are produced by so many different organizations, so it's hard to say that something will definitely be optimized everywhere. We've even come across cases where different iOS devices - all from Apple - made sufficiently different optimizations that developers had to deal with it.

I think the approach most people take is to try to do the simplest reasonable thing, and then deal with performance based on actual observations. It's not ideal, because you don't want to be led around by the nose by this one weird driver. But the landscape varies enough that an empirical approach is really the only option.

**Comment by almarklein** [comment]
Thanks for the clarification. I was hoping that someone would know more about these optimizations in specific. But I see how any answer would still be anecdotal and it would be hard to come up with numbers...
