### ISSUE TITLE
SPIR-V front end generates invalid Naga types for pointers to unsized arrays

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/naga#1519]
Naga IR permits `Dynamic`-sized arrays only in the `Storage` storage class, but the SPIR-V front end creates Naga `Pointer` types to `Dynamic`-sized arrays in the `Uniform` storage class. I think these types are not used, but their presence prevents us from tightening up the validation of pointer types as much as I'd like.

For example, the Naga IR for `tests/in/spv/shadow.spv` includes the following types:

        [19]: Type {
            name: None,
            inner: Array {
                base: [18],
                size: Dynamic,
                stride: 96,
            },
        },
        ...
        [22]: Type {
            name: None,
            inner: Pointer {
                base: [19],
                class: Uniform,
            },
        },

SPIR-V allows runtime-sized arrays to appear only as the last member of a struct in the `StorageBuffer` storage class, or in the `Uniform` storage class when the struct type is decorated with `BufferBlock`. Naga's SPIR-V front end notices the `BufferBlock` decoration, and assigns all `GlobalVariable`s of such types to the Naga `Storage` storage class, regardless of the class given in the `OpVariable` instruction. In this way, the SPIR-V front end respects Naga's requirement that all `Dynamic`-sized arrays appear in `Storage`.

However, in the SPIR-V, all the pointers derived from such variables respect the class given in the `OpVariable`, so there are plenty of pointers to runtime-sized arrays in the `Uniform` storage class floating around in code like `tests/in/spv/shadow.spv`. I imagine some of these must be provoking the SPIR-V front end to also emit a Naga `Uniform` `Pointer` type to a `Dynamic`-sized array.

**Comment by kvark** [comment]
I think the shadow SPV uses "Uniform" class because it's SPIRV-1.0 without the `SPV_KHR_storage_buffer_storage_class` simply doesn't have a separate storage class for storage buffers (d'oh). This caused enough trouble for us on the backend that today we don't even expose Vulkan adapters that don't support this storage class:
```rust
        // VK_KHR_storage_buffer_storage_class required for `Naga` on Vulkan 1.0 devices
        if driver_api_version == vk::API_VERSION_1_0 {
            extensions.push(vk::KhrStorageBufferStorageClassFn::name());
        }
```

So, I think we can just say Naga doesn't support runtime sized arrays in storage buffers under SPIRV-1.0 without the extension, and error out on that in the frontend.
