### ISSUE TITLE
Call not added to statement body when calling function

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/naga#152]
Recently the `Expression::Call` has been implemented for the WGSL front-end. Using this at the right handed side of an expression will add it to the statement body in the IR.

WGSL:
```
fn test_function(test: f32) -> f32 {
  return test;
}

fn main_vert() -> void {
  var test: f32 = test_function(1.0);
  return;
}
entry_point vertex as "main" = main_vert;
```

IR:
```
expressions: Arena {
  data: [
    Constant(
      Handle(1),
    ),
    Call {
      origin: Local(
        Handle(1),
      ),
      arguments: [
        Handle(1),
      ],
    },
    LocalVariable(
      Handle(1),
    ),
  ],
},
body: [
  Store {
    pointer: Handle(3),
    value: Handle(2),
  },
  Return {
    value: None,
  },
],
```

When not calling the function at the right handed side of an expression, but rather just call it in the body of a function, this will not be added to the IR.

WGSL:
```
fn test_function(test: f32) -> f32 {
  return test;
}

fn main_vert() -> void {
  test_function(1.0);
  return;
}
entry_point vertex as "main" = main_vert;
```

IR:
```
expressions: Arena {
  data: [
    Constant(
      Handle(1),
    ),
    Call {
      origin: Local(
        Handle(1),
      ),
      arguments: [
        Handle(1),
      ],
    },
  ],
},
body: [
  Empty,
  Return {
    value: None,
  },
],
```

The most probable reason that this happens is because the IR technically thinks it is always an expression, and cannot be a statement, hence there is only `Expression::Call`.

What I propose to do is adding a `Statement::Call`, and to detect if it is an expression or an statement will be done based on if the function is called at the right side of an expression (e.g. variable declaration), or not.

**Comment by kvark** [comment]
I'm thinking if something more generic will be appropriate. Maybe `Statement::Expression(expr)`?

**Comment by Napokue** [comment]
Sure, but at the moment I cannot think of another use case where we would require this generic statement. Do you maybe know more cases?

**Comment by kvark** [comment]
Not really, but it's also harmless: it doesn't hurt our criteria of a "valid" module, and we can easily generate backend code for this statement, so it feels more future-proof.

**Comment by Napokue** [comment]
Agreed, and we are free to modify the IR, as long as we can verify the integrity of both the input and output. This will always be a case by case situation to choose it we would add it to our generic statement or create an explicit statement for it.

**Comment by kvark** [comment]
Pretty sure this is addressed. We call plenty of functions now.
