### ISSUE TITLE
[spv-out] `Matrix + Matrix` operations not implemented

### ISSUE THREAD

**Issue by parasyte** [gfx-rs/naga#1527]
WGSL test case:

```wgsl
[[stage(vertex)]]
fn vertex() {
    let model = mat4x4<f32>(
        vec4<f32>(1.0, 0.0, 0.0, 0.0),
        vec4<f32>(0.0, 1.0, 0.0, 0.0),
        vec4<f32>(0.0, 0.0, 1.0, 0.0),
        vec4<f32>(0.0, 0.0, 0.0, 1.0),
    );

    let foo = model + model;
}
```

Panics at: https://github.com/gfx-rs/naga/blob/e69a70bfb7b3dff1391d5189d5c68fb798c02040/src/back/spv/block.rs#L321-L328

Workaround by decomposing the matrices into their column vectors and constructing a new matrix after adding the columns separately:

```wgsl
[[stage(vertex)]]
fn vertex() {
    let model = mat4x4<f32>(
        vec4<f32>(1.0, 0.0, 0.0, 0.0),
        vec4<f32>(0.0, 1.0, 0.0, 0.0),
        vec4<f32>(0.0, 0.0, 1.0, 0.0),
        vec4<f32>(0.0, 0.0, 0.0, 1.0),
    );

    let foo = mat4x4<f32>(
        model.x + model.x,
        model.y + model.y,
        model.z + model.z,
        model.w + model.w,
    );
}
```

I believe this is the transformation required for SpirV.

**Comment by kvark** [comment]
I don't think WGSL supports that today, see the spec - https://gpuweb.github.io/gpuweb/wgsl/#arithmetic-expr

**Comment by parasyte** [comment]
Looks like it does, though. In the “Matrix arithmetic” table.

**Comment by kvark** [comment]
Sorry, you are correct. I'm surprised it's in a separate section.
