### ISSUE TITLE
Naga validation doesn't reject stores to read-only variables

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/naga#1533]
[EDIT: I originally misidentified which rule was being broken here. The lead para has been changed.]

Naga fails to reject assignments to variables in the `storage` storage class declared with a default access mode. WGSL says that the default for such variables should be `read`, not `read_write`. For example, the following WGSL input is not rejected:

```
[[block]]
struct Globals {
    i: i32;
};

[[group(0), binding(0)]]
var<storage> globals: Globals;

fn store(v: i32) {
    globals.i = v;
}
```

**Comment by kvark** [comment]
Isn't `wgpu` validating this, actually? But yeah, if naga catches this - even better.
