### ISSUE TITLE
[glsl-in] naga's handling of statements after return/break/continue

### ISSUE THREAD

**Issue by afd** [gfx-rs/naga#1558]
I find that naga rejects this:

```
#version 450

void main() {
 do {
   return;
 } while(false);
}
```

but accepts this:

```
#version 450

void main() {
 do {
   if (true) {
     return;
   } else {
     return;
   }
 } while(false);
}
```

I see there may be an argument for wanting to disallow the first case, but it actually could crop up if a do...while(false) is used in a macro. It also seems slightly unsatisfactory that the first case is disallowed but the second case is allowed.

More generally, GLSL does allow code to appear after return/break/continue. I believe this is disallowed in WGSL. But I suppose it would be easy to prune such code when translating from GLSL to WGSL, so maybe it would be better for naga to accept such examples, so that it's notion of validity is closer to that of glslang.

**Comment by kvark** [comment]
The working group is actually discussing this right now - https://github.com/gpuweb/gpuweb/issues/2378
@JCapucho so perhaps we should hold off merging for a bit until this is decided? Unless somebody needs this right now.

**Comment by JCapucho** [comment]
> The working group is actually discussing this right now - [gpuweb/gpuweb#2378](https://github.com/gpuweb/gpuweb/issues/2378)
@JCapucho so perhaps we should hold off merging for a bit until this is decided? Unless somebody needs this right now.

Fine by me, happy to see the group considering this, seems like such a strange restriction for a textual language.

**Comment by JCapucho** [comment]
@kvark from the issue it seems like the resolution was to keep the error

**Comment by kvark** [comment]
@JCapucho that was a silly resolution, made in a late-time meeting without my participation. I.e. the group hasn't really understood/converged on what they agreed on. When I brought this up, the group wanted to revisit the question.
