### ISSUE TITLE
error occurs in validating the block comment in WGSL 

### ISSUE THREAD

**Issue by jack1232** [gfx-rs/naga#1582]
WGSL allows the block comment, and it works fine in WebGPU apps. Here is an example of using block (or multi-line) comment from the official WGSL site (https://www.w3.org/TR/WGSL/#comments):

EXAMPLE: COMMENTS
let f = 1.5;   // This is line-ending comment.
let g = 2.5;   /* This is a block comment
                  that spans lines.
                  /* Block comments can nest.
                   */
                  But all block comments must terminate.
                */

However, naga gives the following error for this block comment in wgpu apps:

Shader error:
error: expected global item ('struct', 'let', 'var', 'type', ';', 'fn') or the end of the file, found '/'

How to get around this error?

**Comment by kvark** [comment]
We need to implement block comments in WGSL.
