### ISSUE TITLE
Runtime-sized array in a struct triggers interface validation error.

### ISSUE THREAD

**Issue by benvanik** [gfx-rs/naga#1584]
I have a relatively simple tint-produced spirv->wgsl shader:
```wgsl
type RTArr = [[stride(4)]] array<f32>;
struct S {
  field0 : RTArr;
};
[[binding(0), group(0)]] var<storage, read_write> x__resource_var_0_0_ : S;
[[binding(1), group(0)]] var<storage, read_write> x__resource_var_0_1_ : S;
fn abs_dispatch_0_1() {
  let x_15 : f32 = x__resource_var_0_0_.field0[0u];
  x__resource_var_0_1_.field0[0u] = abs(x_15);
  return;
}
[[stage(compute), workgroup_size(1, 1, 1)]]
fn abs_dispatch_0() {
  abs_dispatch_0_1();
}
```
Which seems like it should be ok, roughly matching what's in the spec:
![image](https://user-images.githubusercontent.com/75337/145502434-ec2ea329-35bb-4b5a-8344-3afba7deaa72.png)

When trying to use wgpu naga fails with `Validation(GlobalVariable { handle: [1], name: "x__resource_var_0_0_", error: MissingTypeFlags { required: DATA | HOST_SHARED | TOP_LEVEL, seen: DATA | COPY | INTERFACE | HOST_SHARED } })'` from https://wgpu.rs/doc/src/naga/valid/interface.rs.html#393.

(I'm using the tip-of-tree tint and latest wgpu-native but it seems like it hasn't been updated in awhile - the note in the spec makes me wonder if this is a spec version mismatch?)

**Comment by kvark** [comment]
Looks like Tint generates the newer WGSL with removed `[[block]]` declaration. The almost fresh WGSL required it:
```rust
[[block]]
struct S {
  field0 : RTArr;
};
```

Latest Naga just got updated for this as well in #1581
I confirm it works on master.
So this is just a question of updating wgpu-native's dependencies.

**Comment by benvanik** [comment]
That works, thanks!
