### ISSUE TITLE
[GLSL] "Constructor: Too many arguments" when creating constant array

### ISSUE THREAD

**Issue by sotrh** [gfx-rs/naga#1623]
I have the following vertex shader.

```glsl
#version 450

layout(location=0) out vec3 clip_coords;

const vec3 positions[6] = vec3[6](
    // Bottom left triangle
    vec3(-1.0, 1.0, 0.0),
    vec3(-1.0, -1.0, 0.0),
    vec3(1.0, -1.0, 0.0),

    // Top right triangle
    vec3(-1.0, 1.0, 0.0),
    vec3(1.0, -1.0, 0.0),
    vec3(1.0, 1.0, 0.0)
);

void main() {
    gl_Position = vec4(positions[gl_VertexIndex], 1.0);
    clip_coords = gl_Position.xyz;
}
```

This compiles fine on 0.7, but on 0.8 it fails with the following error.

      Error {
          kind: SemanticError(
              "Constructor: Too many arguments",
          ),
          meta: Span {
              start: 82,
              end: 302,
          },
      },

I've tracked the error down to the `positions` array that I use in lieu of a vertex buffer. Are constant arrays no longer a thing? If so, their should probably be a more specific error for this.

**Comment by lucas-miranda** [comment]
It seems this problem has been reintroduced.

I've tried using the following:

```glsl
#version 450

const vec2 positions[3] = vec2[3] (vec2(0.0, -0.5), vec2(-0.5, 0.5), vec2(0.5, 0.5));

void main() {
    gl_Position = vec4(positions[gl_VertexIndex], 0.0, 1.0);
}
```

and it fails with the following error:

```
Error {
    kind: SemanticError("Constructor: Too many arguments"),
    meta: Span { start: 45, end: 103 }
}
```

**Comment by JCapucho** [comment]
I cannot reproduce this issue on master
