### ISSUE TITLE
Error: unknown type name 'packed_float3'

### ISSUE THREAD

**Issue by djeedai** [gfx-rs/naga#1625]
I have a very similar issue to #999 with naga 0.8.0 on macOS 10.13 High Sierra (if that matters). The generated code includes:
```
// language: metal2.0
#include <metal_stdlib>
#include <simd/simd.h>

[...]

struct View {
    metal::float4x4 view_proj;
    metal::float4x4 inverse_view;
    metal::float4x4 projection;
    packed_float3 world_position;
    float near;
    float far;
    float width;
    float height;
};
```

Compilation fails on the `packed_float3`, same as @Lichtso from #999.

```
program_source:18:5: error: unknown type name 'packed_float3'
    packed_float3 world_position;
```

Is that really supposed to be fixed as stated in #999? If so, was it rather in a version later than 0.8.0, which is the one Bevy is using? Or is that a separate issue maybe?

Cargo.lock:
```
[[package]]
name = "naga"
version = "0.8.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bc7216bec6be822a562dda435236539c7fb5aa5e5ceecc8c565e81139ed1d4b0"
```

**Comment by djeedai** [comment]
Related Bevy issue is here : https://github.com/bevyengine/bevy/issues/3434
@cart confirmed this doesn't repro on Big Sur with the same GPU, so possibly a problem with the macOS version not supporting some newer Metal feature? (I know nothing about Metal, and couldn't find any feature table)

**Comment by djeedai** [comment]
@kvark many thanks for the quick fix! I'm a bit concerned though, if you look at the original issue that behavior only reproduces on older macOS versions like High Sierra, but not on Big Sur, even with the exact same GPU. Were you able to confirm that this is indeed a bug, and why Big Sur doesn't exhibit the bug? Ok now nothing of Metal so apology if the answer is trivial, but I just want to make sure something's not overlooked here and this is not masking another class of bugs due to OS version differences. Let me know if I can help testing. Thanks!

**Comment by djeedai** [comment]
I added a patch to Cargo, and that fixes the particular error reported here, to consume your fix from #1630.

```toml
[patch.crates-io]
naga = { git = "https://github.com/gfx-rs/naga.git" }
```

This does indeed fix the particular error reported above. However now I have more errors, one related to `packed_float3` and the other to `uint`:

```
program_source:312:5: error: use of undeclared identifier 'uint'; did you mean 'int'?
    uint indices = metal::uint(_e46) < 4 && metal::uint(_e37) < 1024 ? cluster_light_index_lists.data.inner[_e37][_e46] : DefaultConstructible();
    ^~~~
    int
program_source:391:63: error: no member named 'xyz' in 'metal::packed_vec<float, 3>'
    metal::float3 incident_light = light_1.direction_to_light.xyz;
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
```

It seems the version of Metal on macOS High Sierra is missing some features compared to the code generated by naga.

**Comment by kvark** [comment]
interesting, thank you for testing! I'll look into this some more.

**Comment by djeedai** [comment]
@kvark I tested again with latest 1d0f484b37dec4828ce581a55a94d4706fe6d583 and the packed float errors are gone but the`uint` error is still there. Was that an overlook from the logs above, and should I open a separate issue for it? It's again a problem of missing `metal::` apparently. Thanks!

**Comment by kvark** [comment]
sorry, it's a separate issue, and I totally missed it. Please file it!

**Comment by djeedai** [comment]
Opened as #1636, thanks!
