### ISSUE TITLE
error: use of undeclared identifier 'uint'

### ISSUE THREAD

**Issue by djeedai** [gfx-rs/naga#1636]
This is a follow up on #1625, for the specific error of `uint`, running naga 0.8.0 (latest; 1d0f484b37dec4828ce581a55a94d4706fe6d583) on macOS 10.13 High Sierra:

```
program_source:312:5: error: use of undeclared identifier 'uint'; did you mean 'int'?
    uint indices = metal::uint(_e46) < 4 && metal::uint(_e37) < 1024 ? cluster_light_index_lists.data.inner[_e37][_e46] : DefaultConstructible();
    ^~~~
    int
```

Likely the same issue as for packed floats, lacking of `metal::` namespacing.

**Comment by kvark** [comment]
Do you have some source code for reproducing this?

**Comment by kvark** [comment]
Re-reading the code again, this should have been fixed by #1634

**Comment by kvark** [comment]
Going to close it for now, unless new information comes in.

**Comment by djeedai** [comment]
Yes sorry I haven't been able to repro again so maybe indeed was fixed. Not sure what happened when I tried first. Anyway can't test again as I upgraded. Thanks!
