### ISSUE TITLE
MSL bounds checks don't allow taking an address of an element of an array

### ISSUE THREAD

**Issue by kyren** [gfx-rs/naga#1643]
In WGSL we have code like this

```
let v = atomicAdd(&histogram_shared_group[bucket_index], 1u);
```

and when compiled by naga into MSL with bounds checks, that gets turned into this:

```
metal::uint _e26 = metal::atomic_fetch_add_explicit(&metal::uint(_e23) < 256 ? histogram_shared_group.inner[_e23] : DefaultConstructible(), 1u, metal::memory_order_relaxed);
```

which then generates this error from metal:

```
program_source:67:61: error: cannot take the address of an rvalue of type 'metal::uint' (aka 'unsigned int')
        metal::uint _e26 = metal::atomic_fetch_add_explicit(&metal::uint(_e23) < 256 ? histogram_shared_group.inner[_e23] : DefaultConstructible(), 1u, metal::memory_order_relaxed);
```

This doesn't compile obviously because of the badly placed `&`, but even if that was fixed, in order to make the entire thing work it would still require taking the address of an rvalue (namely `DefaultConstructible()`) right?  I'm not sure what the best way to fix this is.

This is a pretty rough bug because currently this is the only way of using atomics that I am aware of.

**Comment by jimblandy** [comment]
@kyren, thanks for reporting this. As a workaround, would it suffice to use `BoundsCheckPolicy::Restrict` instead of `ReadZeroSkipWrite`?

**Comment by kyren** [comment]
@jimblandy I'm using naga indirectly through wgpu, is there a way to pipe that setting through wgpu currently?

**Comment by kyren** [comment]
Oh also, if it helps our particular use case, we don't actually need the return value from `atomicAdd`, that was actually added as a workaround for another bug which I'm not sure of right now, but it no longer exists in wgpu `0.12` and the version of naga that it uses so that part has been removed.

**Comment by kvark** [comment]
> @kyren, thanks for reporting this. As a workaround, would it suffice to use `BoundsCheckPolicy::Restrict` instead of `ReadZeroSkipWrite`?

Since we don't have the full shader, we can just try to construct a case and see.

**Comment by jimblandy** [comment]
@kyren, does bb604fd6 fix this bug?

**Comment by zeh** [comment]
> @kyren, does [bb604fd](https://github.com/gfx-rs/naga/commit/bb604fd6a3ad9cb9dbe2ff579be55d008e624b18) fix this bug?

Newbie question: is there an easy way to test that commit's changes without having to checkout naga 0.8.5 to a folder, cherry-pick this commit into it, and then `[patch]` on `Cargo.toml` to override the transitive dependency of wgpu?

I have the same issue on a shader, and would like to run my application tests against this patched version on CI, but just using `[patch]` doesn't work (the version of naga in `master` seems incompatible with the latest version of wgpu, so it doesn't compile).

**Comment by caelunshun** [comment]
I can confirm that #1703 has fixed the bug for me.

> Newbie question: is there an easy way to test that commit's changes without having to checkout naga 0.8.5 to a folder, cherry-pick this commit into it, and then [patch] on Cargo.toml to override the transitive dependency of wgpu?

I had to do what you say—cherry-pick the commit onto the v0.8 branch. I don't think there's an easier way.

**Comment by kvark** [comment]
Please reopen if this is still an issue!
