### ISSUE TITLE
naga-cli crate seems old

### ISSUE THREAD

**Issue by rhysd** [gfx-rs/naga#1657]
Hi,

[`naga-cli`](https://crates.io/crates/naga-cli/versions) crate is useful for me to learn WGSL. However, `naga` command installed via `cargo install naga-cli` seems old.

```wgsl
// foo.wgsl
struct CameraUniform {
    view_proj: mat4x4<f32>;
};

[[group(1), binding(0)]]
var<uniform> camera: CameraUniform;

struct VertexInput {
    [[location(0)]] position: vec3<f32>;
    [[location(1)]] tex_coords: vec2<f32>;
};

struct VertexOutput {
    [[builtin(position)]] clip_position: vec4<f32>;
    [[location(0)]] tex_coords: vec2<f32>;
};

[[stage(vertex)]]
fn vs_main(model: VertexInput) -> VertexOutput {
    var out: VertexOutput;
    out.tex_coords = model.tex_coords;
    out.clip_position = camera.view_proj * vec4<f32>(model.position, 1.0);
    return out;
}
```

When running `naga` command as follows,

```
naga /path/to/foo.wgsl
```

I got this error:

```
Global variable [1] 'camera' is invalid:
        Type flags DATA | SIZED | COPY | INTERFACE | HOST_SHARED | ARGUMENT do not meet the required DATA | SIZED | COPY | HOST_SHARED | TOP_LEVEL
```

But the shader program ran correctly so it seemed valid. Next, I tried the latest master branch.

```
cd /path/to/naga/cli
cargo run -- /path/to/foo.wgsl
```

It ran successfully:

```
Validation successful
```

I think `naga-cli` crate currently uploaded to crates.io is old. Actually, it was released on Oct. 10 though the latest `wgpu` was released 22 days ago.

And I'm a bit confused with the version. Current latest version on crates.io is 0.7.0 but in master branch it is [0.4.0](https://github.com/gfx-rs/naga/blob/70b5ddaaad46b68ffb4e298b1d10d920544d3ca0/cli/Cargo.toml#L3).

**Comment by kvark** [comment]
Published 0.8.0

**Comment by rhysd** [comment]
Thank you!

**Comment by dannyfritz** [comment]
`naga-cli` appears to be old again. Doesn't support the `@location` syntax for WGSL.
