### ISSUE TITLE
[msl-out] `back::msl::writer::test_stack_size` fails

### ISSUE THREAD

**Issue by NoelTautges** [gfx-rs/naga#1661]
Testing [the most recent commit](https://github.com/gfx-rs/naga/tree/298a8c30bd8b4500e852211956fbd293590d3a96) on Rust `x86_64-pc-windows-msvc` 1.43/stable/nightly with `cargo test back::msl::writer::test_stack_size` yields the following error:

```
thread 'back::msl::writer::test_stack_size' panicked at '`put_block` stack size 11312 has changed!', src\back\msl\writer.rs:3243:13
```

[Here's the test.](https://github.com/gfx-rs/naga/blob/53eeb654aafde4be239b99faff68f3521c465863/src/back/msl/writer.rs#L3243)

This error doesn't exist on the latest CI run on [1.43](https://github.com/gfx-rs/naga/runs/4763058067?check_suite_focus=true#step:6:45) or [nightly](https://github.com/gfx-rs/naga/runs/4763058151?check_suite_focus=true#step:6:44).

**Comment by kvark** [comment]
Should be fixed in 7555df9
