### ISSUE TITLE
Index array out of bounds with pointers

### ISSUE THREAD

**Issue by munrocket** [gfx-rs/naga#1709]
It is possible to crash Firefox Nightly with "out of bounds" index in arrays.

```ts
fn sdPolygon(/*...*/ v: ptr<function, array<vec2<f32>, 5>>) -> f32 {
  return (*v)[-1];
}
```
Minimal example: https://codepen.io/munrocket/pen/podgPgp

Possible solution:
At least for now seems that Chrome calculating reminder id = id % N

[ lang: metal ]

**Comment by kvark** [comment]
How do I see your crash? Opening this page on FF Nightly on macOS doesn't crash anything, shows a star with some pattern.
Feeding this fragment through naga just results in the parsing error:
```
error: expected unsigned integer constant expression, found `-1`
  ┌─ wgsl:2:15
  │
2 │   return (*v)[-1];
  │               ^^ expected unsigned integer

Could not parse WGSL
```

**Comment by munrocket** [comment]
Sorry, maybe crashes not related to this particular example and they happening randomly with WebGPU context.
Anyway, thank you for error messages in console. They are very useful!
