### ISSUE TITLE
builtin(position) vertex output does not match fragment input

### ISSUE THREAD

**Issue by glfmn** [gfx-rs/naga#1731]
According to the WGSL spec, [`builtin(position)`](https://gpuweb.github.io/gpuweb/wgsl/#builtin-values) is in normalized device coordinate space.  In my vertex shader, I output the position in clip space (with `w` component of `1.0`), but when I access `builtin(position)` in the fragment shader it appears to be in screen space (I pass all values into my shader in screen space as I am rendering UI).  With a `w` component of `1.0`, I would expect them to be the same.

I discovered this by performing a renderdoc capture and compared the output of the vertex shader to the input of the fragment shader:

### Vertex Output
![image](https://user-images.githubusercontent.com/14112725/154271506-0de44847-7569-4521-9eac-1fee3bf4fcbf.png)

### Fragment Input
Position as seen by the fragment shader very near the position of the vertex
![image](https://user-images.githubusercontent.com/14112725/154271763-32bbdf21-f697-45a4-a6ca-52e575c780e8.png)

The polygons appear where they should on screen, but the fragment shader gets the wrong value.  As a workaround, I am using `location(0)` to pass the value.

I have reproduced this issue on two AMD GPUs, both with Vulkan.

**Comment by cwfitzgerald** [comment]
This is a problem of a bad description in the spec. This is the correct (and confusing) behavior for builtin(position). The definition depends on a very particular definition of "normalized".

> Framebuffer position of the current fragment, using normalized homogeneous coordinates. 

The homogeneity is normalized (i.e. w = 1) not the coordinates themselves. I really think this should be a different named builtin, but I don't make the rules.

**Comment by glfmn** [comment]
Thank you for clearing that up!  After re-reading the spec that makes a lot of sense.
