### ISSUE TITLE
[spir-v] Invalid result when using implicitly initialized array

### ISSUE THREAD

**Issue by hasali19** [gfx-rs/naga#1748]
I've noticed an issue when accessing a module scoped array that's implicitly initialized (with vulkan, works fine with dx12). This is the smallest reproduction I've managed to get:

```wgsl
var<private> arr: array<u32, 1>;

@group(0)
@binding(0)
var<storage, read_write> output: array<u32>;

@stage(compute)
@workgroup_size(1)
fn main() {
    // arr[0] = 0u;
    if (arr[0] >= 1u) {
        return;
    }
    output[0] = 123u;
}
```

If I uncomment the first line of `main` then it gives the expected result (123) in output, otherwise it's 0. The [spec](https://www.w3.org/TR/WGSL/#var-decls) says that variables in the private address space should be zero initialized so I think this code should work.

**Comment by kvark** [comment]
I think it's easiest to handle on the backend side. I.e. SPIR-V would use "OpConstantNull", GLSL would use `(Type)0`, MSL would use `{}`. But I'm open to other suggestions here :) cc @jimblandy

**Comment by jimblandy** [comment]
That sounds right to me. Naga produces the following Metal:

```
    type_1 arr = {};
```

So that's initialized. But Naga produces the following SPIR-V:

```
        %arr = OpVariable %_ptr_Private__arr_uint_int_1 Private
```

That's missing the final optional "Initializer" argument.
