### ISSUE TITLE
atomicCompareExchangeWeak not working

### ISSUE THREAD

**Issue by ria8651** [gfx-rs/naga#1755]
**Description**
When using atomicCompareExchangeWeak I get a validation error: `Result type for [33] doesn't match the statement`
```rust
let exchange = atomicCompareExchangeWeak(&n.lock, 0u, 1u);
```

**Expected vs observed behaviour**
I'd expect the behaviour explained in the spec.

**Platform**
 * macOS
 * wgpu 0.12 or wgpu master

**Comment by kvark** [comment]
We could implement *something* in the backends, but it would be partially wasted work, since this isn't going to be the API of WGSL but rather something ad-hoc.

**Comment by teoxoy** [comment]
Validation was updated by https://github.com/gfx-rs/naga/pull/2165 which also added support for SPIR-V codegen.
Let's track remaining work (adding support for the builting to the other remaining backends) in https://github.com/gfx-rs/naga/issues/1413.
