### ISSUE TITLE
Component-wise division of vectors doesnt compile

### ISSUE THREAD

**Issue by jasperdewinther** [gfx-rs/naga#1765]
**Description**
Component-wise division of vectors doesnt compile.

**Repro steps**
Try using create_shader_module on the file listed below.

**Expected vs observed behavior**
Expected: The shader compiles as a component-wise division should work on two vectors according to the [spec](https://www.w3.org/TR/WGSL/#arithmetic-expr). 
Observed: The shader doesnt compile as the expression "cant work" on two vectors.

**Extra materials**
[Error in an image](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/zUvfAFoYrItmxSsAYieNCdVC)
```
struct Ray {
    pos: vec4<f32>;
    dir: vec4<f32>;
};

struct Rays {
  rays : [[stride(32)]] array<Ray>;
};

[[group(0), binding(0)]] var<storage, read> rays : Rays;

[[stage(compute), workgroup_size(16, 16)]]
fn main([[builtin(global_invocation_id)]] global_invocation_id: vec3<u32>){
    let x: u32 = global_invocation_id[0];
    let y: u32 = global_invocation_id[1];    

    let ray = rays.rays[x + (720u * y)];

	let deltaDist = abs(vec3<f32>(length(ray.dir)) / vec3<f32>(ray.dir));
}
```

**Platform**
Windows 10, wgpu 0.12.0, naga 0.8.5

**Comment by teoxoy** [comment]
The validation error was misleading due to #1774 which has been fixed by #1790.

It should have been this

```
error: cannot cast a vec4<f32> to a vec3<f32>
   ┌─ test.wgsl:20:61
   │
20 │     let deltaDist = abs(vec3<f32>(length(ray.dir)) / vec3<f32>(ray.dir));
   │                                                                ^^^^^^^ cannot cast a vec4<f32> to a vec3<f32>
```

which is now properly output on latest master.
