### ISSUE TITLE
Shader working on VULKAN but not on DX12 FRAGMENT

### ISSUE THREAD

**Issue by MrMarnic** [gfx-rs/naga#1772]
I have a problem that my shader is only producing the right result on VULKAN but not DX12.

Expected result (works on VULKAN):
https://imgur.com/xIHAQdv
![dragonVULKAN](https://user-images.githubusercontent.com/42642302/158024302-21187777-fa8e-4cc5-9f71-7663bad2fc2a.png)

Result on DX12:
https://imgur.com/1EbPQOf
![dragonDX12](https://user-images.githubusercontent.com/42642302/158024300-f872c79a-82eb-4db1-9404-86ce11a21fdc.png)

My fragment shader code looks like this:
```
void main() {

    float ambientStrength = 0.2;
    vec4 texel = texture(sampler2D(t_diffuse, s_diffuse), tex_coords_out);

    vec3 resultA = vec3(0.0,0.0,0.0);

    for(int i = 0;i<numLights;i++) {
        vec3 ambient = material.ambientColor * ambientStrength * light[i].lightColor;

        vec3 norm = normalize(normal);
        vec3 lightDir = normalize(light[i].lightPos - frag_pos);

        float diff = max(dot(norm,lightDir),0.0);
        vec3 diffuse = light[i].lightColor * (diff * material.diffuseColor);

        resultA += ambient + diffuse;
    }

    vec4 result = texel * vec4(resultA,1.0);

    f_color = result;
}
```

The Light struct looks like this:

```
struct Light {
    vec3 lightPos;
    vec3 lightColor;
};

layout(set = 3, binding = 0)
uniform LightUniform {
    Light light[4];
    int numLights;
};

```
If the numLights variable is 1 the lighting is working on DX12 (but only for one light of course).
There seems to be a problem with "resultA += ambient + diffuse;" because if two lights are present than the addition is not correct (everything black).

naga-version = "0.8"

**Comment by kvark** [comment]
What exactly are you feeding to wgpu? The shader provided is for GLSL. Are you passing GLSL to wgpu?

**Comment by MrMarnic** [comment]
Yes I am.

**Comment by kvark** [comment]
If you are reproducing this, you could step through the code in RenderDoc pixel debugger and see which values are screwing everything up.

**Comment by MrMarnic** [comment]
I have checked it with RenderDoc. The numLights int is the problem. On Vulkan it has the correct value. But in DX12 it is always 0. And because it never iterates, the resulting color is black. If I change numLights manually to 2 DX12 produces the correct image.

**Comment by MrMarnic** [comment]
![render_doc](https://user-images.githubusercontent.com/42642302/158059248-131018ce-1904-4b17-a269-50a45e99a8a5.png)

**Comment by MrMarnic** [comment]
And here is the Vulkan result:
![render_doc_vulkan](https://user-images.githubusercontent.com/42642302/158059372-58d58ed8-c6a9-456f-bdd7-69e99b5d80df.png)

**Comment by kvark** [comment]
That's a good finding! Now you can check the copy operation that filled out this buffer, and eventually narrow down to the problem.

**Comment by MrMarnic** [comment]
Should I also do this in RenderDoc or in wgpu ?

**Comment by MrMarnic** [comment]
And how can I do this?

**Comment by kvark** [comment]
The copy would be in your RenderDoc capture as some `vkCmdCopyBuffer`. If the copy is only done on the first frame, then you need RD to capture only the first frame. And then if the mapped data is incorrect, you'd need to look into wgpu implementation.

**Comment by MrMarnic** [comment]
Ok I think I found it. This is the capture on DX12 for the buffer:
![bufferContent](https://user-images.githubusercontent.com/42642302/158877140-6c24f7f9-b207-4c8c-aae9-147db85f1053.png)

**Comment by MrMarnic** [comment]
This is the buffer content for VULKAN:
![bufferContentVulkan](https://user-images.githubusercontent.com/42642302/158877940-2d539810-4a9d-4d0c-b2cf-41f3f7f9a475.png)

**Comment by MrMarnic** [comment]
They both have the same content up until line 8 0000002

**Comment by teoxoy** [comment]
The data looks the same. The buffer is just slightly larger for some reason but I don't think it's relevant here.
What hardware and drivers are you running?

**Comment by MrMarnic** [comment]
NVIDIA GTX 1080 Ti
Driver Version 512.15

**Comment by teoxoy** [comment]
Would you be able to provide a complete code sample for us to try and reproduce the issue?

**Comment by teoxoy** [comment]
I found out what the issue is. The padding after the last vec3 (that's inside a struct that's inside an array) is being read as `numLights` due to the following HLSL buffer layout rule:

> Aggregates (arrays and structures) are always 16-byte row-aligned. If the aggregate ends in an element that does not completely fill a row, the remaining space on the last row may be used by the next value.

quoting [DXC's Constant Buffer Packing Wiki](https://github.com/microsoft/DirectXShaderCompiler/wiki/Buffer-Packing/4e59b6a713aa5b363ac57e87574bc1d13557bd0e#constant-buffer-packing)

From my [tests](https://shader-playground.timjones.io/cc4c0a2110f11cfb439a3829214fc3cb) this also includes matrices.

To fix this we need to add some more explicit padding in a few places.
