### ISSUE TITLE
wgsl-in: switch case expression shouldn't require parenthesis

### ISSUE THREAD

**Issue by jakobhellermann** [gfx-rs/naga#1778]
The grammar of the switch statement declares

```py
switch_statement:
| switch expression brace_left switch_body+ brace_right
```

so

```rust
switch 0 {
  ..
}
```

should be accepted.

```rust
error: expected '(', found '0'
   ┌─ wgsl:32:12
   │
32 │     switch 0 {
   │            ^ expected '('

Could not parse WGSL
```

**Comment by Gordon-F** [comment]
@jakobhellermann Are you tested this on latest master branch? I think it was fixed in https://github.com/gfx-rs/naga/pull/1725

**Comment by jakobhellermann** [comment]
I did not, I just used the binary I installed a while ago. Looks like this is already fixed then 👍
