### ISSUE TITLE
Use global vars in Image-related expressions

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#178]
Currently, we have both the image and the sampler specified as expressions:
```rust
    ImageSample {
        image: Handle<Expression>,
        sampler: Handle<Expression>,
        coordinate: Handle<Expression>,
        level: SampleLevel,
        depth_ref: Option<Handle<Expression>>,
    },
```
WGSL today requires them to be statically known, so maybe it would make more sense to have this expression as:
```rust
    ImageSample {
        image: Handle<GlobalVariable>,
        sampler: Handle<GlobalVariable>,
        coordinate: Handle<Expression>,
        level: SampleLevel,
        depth_ref: Option<Handle<Expression>>,
    },
```

The main concern is: whether or not we'll want to support the variable pointers at some point. In this case, the exact image or sampler will not be statically known to IR.

**Comment by JCapucho** [comment]
I think we can close this since we now also support function arguments as images/samplers
