### ISSUE TITLE
[spv-out] wrapping struct types for globals lack required decorations

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/naga#1810]
Naga IR permits globals to have non-struct types, but Vulkan [requires][rq] that globals in the `Uniform` and `Storage` storage classes be struct types. Our SPIR-V backend accommodates this by synthesizing SPIR-V struct types wrapping the contents of Naga globals as needed, but it fails to apply decorations required on members that are matrices or arrays of matrices.

For example, the following WGSL input generates SPIR-V that fails to validate:

```
@group(0)
@binding(0)
var<uniform> transform: mat4x4<f32>;

@stage(vertex)
fn vs_main(
    @location(0) position: vec4<f32>,
) -> @builtin(position) vec4<f32> {
    return transform * position;
}
```

This fails validation in the `vulkan1.0` target environment:

```
error: line 19: Structure id 7 decorated as Block must be explicitly laid out with MatrixStride decorations.
  %_struct_7 = OpTypeStruct %mat4v4float
```

[rq]:  https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#interfaces-resources-descset

**Comment by kvark** [comment]
Hmm now I feel strange. Wouldn't we see this on CI? Our CI runs spirv-val on produced code, and tests use non-structured uniform/storage buffers.

**Comment by jimblandy** [comment]
> Hmm now I feel strange. Wouldn't we see this on CI? Our CI runs spirv-val on produced code, and tests use non-structured uniform/storage buffers.

We don't have any tests that use straight matrix types in uniform or storage buffers. I tried to introduce one in the tests for #1815, but discovered #1811.
