### ISSUE TITLE
[wgsl-in] Phony assignment

### ISSUE THREAD

**Issue by hanawatson** [gfx-rs/naga#1842]
Hi, phony assignments in WGSL input seem to not be recognised by naga currently

code example (slightly altered copy of an example in the spec https://gpuweb.github.io/gpuweb/wgsl/#phony-assignment-section, since as this is an example use it should presumably definitely work):
```
var <private> counter: i32;

fn increment_and_yield_previous() -> i32 {
	let previous = counter;
	counter = counter + 1;
	return previous;
}

@stage(compute) @workgroup_size(1)
fn compute_main(
) {
	_ = increment_and_yield_previous();
}
```

resultant error:
```
error: unknown local function `_`
   ┌─ phonytest.wgsl:12:2
   │
12 │     _ = increment_and_yield_previous();
   │     ^ unknown local function

Could not parse WGSL
```

**Comment by teoxoy** [comment]
We currently allow the `_` identifier for let and var assignments and this works like phony assignment but according to the spec (and this issue) we shouldn't require let/var since the `_` is not supposed to be an identifier and therefore not able to be declared via let/var.

**Comment by stshine** [comment]
It is strange for phony assignment not requiring `let`.

**Comment by teoxoy** [comment]
@stshine see https://github.com/gpuweb/gpuweb/pull/2127 for the reasons behind it
