### ISSUE TITLE
[msl-out] atomic functions try to take reference of rvalue

### ISSUE THREAD

**Issue by superdump** [gfx-rs/naga#1848]
In some WGSL shader code in bevy-hikari:
```rust
struct VoxelBuffer {
    data: array<atomic<u32>, 16777216>;
}
...
[[group(3), binding(2)]]
var<storage, read_write> voxel_buffer: VoxelBuffer;
...
    var packed = pack4x8unorm(vec4<f32>(color.rgb, color.a / 255.0));

    let index = spatial_index(in.world_position.xyz);
    let voxel = &voxel_buffer.data[linear_index(index)];
    atomicMax(voxel, packed);
```
So that is basically an `atomixMac(ptr<private, atomic<u32>, read_write>, ref<function, u32, read_write>)`. The problem on metal is that this produces:
```msl
2022-04-17T15:18:10.341677Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `opaque_mesh_pipeline`
    Internal error in FRAGMENT shader: Metal: program_source:302:15: warning: unused variable '_e89'
        float _e89 = compute_roughness(_e88);
              ^
program_source:374:58: error: cannot take the address of an rvalue of type 'metal::uint' (aka 'unsigned int')
    metal::uint _e199 = metal::atomic_fetch_max_explicit(&metal::uint(_e196) < 16777216 ? voxel_buffer.data.inner[_e196] : DefaultConstructible(), _e198, metal::memory_order_relaxed);
                                                         ^~~~~~~~~~~~~~~~~~~
```
So the _e196, which is presumably a uint, is wrapped in metal::uint() which makes it an rvalue, and then the reference of it is attempted to be taken. That is, I believe, not what is intended here.

wgpu-0.12.0
naga-0.8.5

**Comment by kvark** [comment]
That seems familiar. @jimblandy would know more

**Comment by raphlinus** [comment]
I did a bit more digging on this. The corresponding behavior for other atomics like `atomicAdd` seems correct, and the logic is in the `put_atomic_fetch` function, which has explicit case handling for the checked option. This was added in #1703, but the problem is that `atomicExchange` is output directly from the `Statement::Atomic` match arm, without going through this helper function.
