### ISSUE TITLE
[wgsl-in] `binding_array` type should require a capability

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/naga#1858]
Since the `binding_array` type (for arrays of textures) is not part of the WebGPU standard, it should be gated somehow, so that we can disable it on the web - perhaps with a flag in `valid::Capabilities`.

cc @cwfitzgerald

**Comment by cwfitzgerald** [comment]
I got the impression that we only needed capabilities for things that weren't part of the shaders interface -- a binding array is, so it's impossible to create a valid pipeline from a shader using a binding array on the web, as the wgpu feature will never be enable.

If we still do want this to be a capability, I can add it, though we probably should document what should and shouldn't be.

**Comment by jimblandy** [comment]
Oh, I see what you mean. Naga validation may pass, but wgpu validation will not, so they can't use it anyway.

It's also the case that `binding_array` is an identifier WGSL says the user is allowed to define on their own; at present, it's a reserved word. That's a less serious problem than the one I originally had in mind, though.

**Comment by jimblandy** [comment]
I filed a WGSL issue about reserving `binding_array`:
https://github.com/gpuweb/gpuweb/issues/2794

**Comment by jimblandy** [comment]
WGSL committee agreed to make `binding_array` a reserved word. (This of course does not imply any position on standardizing the feature itself.) So I don't think we have any need for a capability in Naga.
