### ISSUE TITLE
[wgsl-in] Error on matrices with non float scalar kinds

### ISSUE THREAD

**Issue by pixelspark** [gfx-rs/naga#1896]
The following works (on naga master cf32c2b):

````wgsl
@group(0) @binding(0)
var<storage, write> output_0: vec3<f32>;

@compute @workgroup_size(1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
	let zero: f32 = 0.0;
	let zero_vec = vec3<f32>(zero,zero,zero);
	let m = mat3x3<f32>(zero_vec, zero_vec, zero_vec);
}
````

````bash
% cargo run --  ./test.wgsl
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/naga ./test.wgsl`
Validation successful
````

The following shows an error (`f32` is replaced with `i32`):

````wgsl
@group(0) @binding(0)
var<storage, write> output_0: vec3<i32>;

@compute @workgroup_size(1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
	let zero: i32 = 0;
	let zero_vec = vec3<i32>(zero,zero,zero);
	let m = mat3x3<i32>(zero_vec, zero_vec, zero_vec);
}
````

````bash
% cargo run --  ./test.wgsl
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/naga ./test.wgsl`
[2022-05-09T19:06:29Z ERROR naga::valid::compose] Matrix component[0] type Handle([1])
error: 
  ┌─ test.wgsl:8:9
  │
8 │     let m = mat3x3<i32>(zero_vec, zero_vec, zero_vec);
  │            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ naga::Expression [5]

Entry point main at Compute is invalid: 
	Expression [5] is invalid
	Composing 0's component type is not expected
````

This seems... a bug, or is this just a counterintuitive aspect of the spec? 

Use case: in [wonnx](https://github.com/webonnx/wonnx) we generate shaders using templates (e.g. [this one for generalized matrix multiplication](https://github.com/webonnx/wonnx/blob/master/wonnx/templates/matrix/gemm.wgsl)) to implement machine learning operators, which may use different data types (typically f32, i32 or i64) and would like to make the shaders work on all types. We often need to construct zero values (or other statically initialized values).

**Comment by pixelspark** [comment]
OK, thanks, that makes sense (I guess there's probably some platform that doesn't support it and WGSL therefore restricts to floats). 

I would then suggest to improve the error messaging here (mayne it should throw an error even when just naming the type `mat3x3<i32>` as that can never be used?).

**Comment by teoxoy** [comment]
Looks like we are currently ignoring the `ScalarKind` returned by `next_scalar_generic()`.

This could be handled by introducing a new error type `BadScalarKind` (akin to the existing `BadScalarWidth`) and if we encounter any scalar kind other than `ScalarKind::Float` return the `BadScalarKind` error.

https://github.com/gfx-rs/naga/blob/cf32c2b7f38c985e1c770eeff05a91e0cd15ee04/src/front/wgsl/construction.rs#L187

https://github.com/gfx-rs/naga/blob/cf32c2b7f38c985e1c770eeff05a91e0cd15ee04/src/front/wgsl/mod.rs#L2940-L3011
