### ISSUE TITLE
[hlsl-out] Invalid hlsl for write to scalar/vector storage buffer

### ISSUE THREAD

**Issue by hasali19** [gfx-rs/naga#1902]
WGSL:

```
@group(0)
@binding(0)
var<storage, read_write> buf: vec2<i32>;

@compute
@workgroup_size(1)
fn main() {
    buf = vec2<i32>(1);
}
```

HLSL:

```hlsl
RWByteAddressBuffer buf : register(u0);

[numthreads(1, 1, 1)]
void main()
{
    buf.Store2(, asuint((1).xx));
    return;
}
```

The `Store2` call seems to have a missing argument.

**Comment by hasali19** [comment]
Looks like this also affects scalars:

```
@group(0)
@binding(0)
var<storage, read_write> buf: i32;

@compute
@workgroup_size(1)
fn main() {
    buf = 0;
}
```

**Comment by teoxoy** [comment]
The WGSL spec and also naga used to only allow structs for global variables in uniform and storage address spaces.
Following the spec we recently relaxed this requirement (in https://github.com/gfx-rs/naga/pull/1682) but it looks like the `Writer::write_storage_address` method still assumes there is a non empty chain of accesses.

I think to get this working we just need to write a 0 if the chain is empty here

https://github.com/gfx-rs/naga/blob/b3d5e6d807560310fa514c0920c91c7f2cac974b/src/back/hlsl/storage.rs#L41-L62
