### ISSUE TITLE
[hlsl-out] Incorrect result for min(reverseBits(-1), 0)

### ISSUE THREAD

**Issue by hasali19** [gfx-rs/naga#1904]
WGSL:

```
struct f {
    a: i32,
}

@group(0)
@binding(1)
var<storage, read_write> h: f;

@stage(compute)
@workgroup_size(1)
fn main() {
    h = f(min(reverseBits(-1), 0));
}
```

HLSL:

```hlsl
struct f {
    int a;
};

RWByteAddressBuffer h : register(u1);

f Constructf(int arg0) {
    f ret;
    ret.a = arg0;
    return ret;
}

[numthreads(1, 1, 1)]
void main()
{
    {
        f _value2 = Constructf(min(reversebits(-1), 0));
        h.Store(0, asuint(_value2.a));
    }
    return;
}
```

This incorrectly produces 0, though `reverseBits(-1)` should in fact be a no-op. I think hlsl's `reversebits` operates on `uint`, so needs to be transformed to `asint(reversebits(asuint(-1)))`.

**Comment by teoxoy** [comment]
> I think hlsl's `reversebits` operates on `uint`, so needs to be transformed to `asint(reversebits(asuint(-1)))`.

Indeed, good catch!

`countbits` is also missing signed integer overloads.

The fix is a bit more involved but a good stepping stone; if you'd like to contribute a fix for this and need any help feel free to ask here or over on the naga matrix channel!

**Comment by hasali19** [comment]
Thanks! I'm a bit busy at the moment but I might have a go at this on the weekend.
