### ISSUE TITLE
[wgsl-in] Error on provision of boolean scalars to all/any built-in functions

### ISSUE THREAD

**Issue by hanawatson** [gfx-rs/naga#1911]
The specification provides two overloads for the `all` and `any` built-in functions, with one accepting boolean vectors and the second accepting boolean scalars. naga appears to only accept the former.

code example (analogous for `any`):
```
@compute @workgroup_size(1)
fn compute_main() {
	var var0 = all(true);
}
```

naga compilation error:
```
[2022-05-11T18:19:19Z ERROR naga::valid::expression] All/Any of type Scalar { kind: Bool, width: 1 }
error: 
  ┌─ all_any_scalar.wgsl:3:12
  │
3 │     var var0 = all(true);
  │               ^^^^^^^^^^ naga::Expression [2]

Entry point compute_main at Compute is invalid: 
	Expression [2] is invalid
	Relational argument [1] is not a boolean vector
```

**Comment by teoxoy** [comment]
For future reference, these were added by https://github.com/gpuweb/gpuweb/pull/2174.
