### ISSUE TITLE
[glsl] Translating read-write storage buffer from WGSL->GLSL and validating throws error

### ISSUE THREAD

**Issue by hanawatson** [gfx-rs/naga#1943]
Translating the following piece of WGSL code to GLSL 440 or 450 using naga returns no errors, but validating the translated .comp shader with naga throws an error. Again, I'm unsure if this is an issue with glsl-in or glsl-out.

WGSL:
```
struct outputBuffer {
	output: i32,
}

@group(0) @binding(0)
var<storage, read_write> out: outputBuffer;

@stage(compute) @workgroup_size(1)
fn main() {
	out.output = 0;
}
```

Error:
```
        error: uniform/buffer blocks require layout(binding=X)
          ┌─ test.comp:9:23
          │
        9 │ layout(std430) buffer outputBuffer_block_0Compute { outputBuffer _group_0_binding_0_cs; };
          │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Translated GLSL from glsl-out:
```
#version 440 core
#extension GL_ARB_compute_shader : require
#extension GL_ARB_shader_storage_buffer_object : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct outputBuffer {
    int output_;
};
layout(std430) buffer outputBuffer_block_0Compute { outputBuffer _group_0_binding_0_cs; };
```

**Comment by JCapucho** [comment]
Neither is wrong in this case, the glsl frontend is designed to accept the vulkan flavor of GLSL, and the backend is for OpenGL glsl, these are very similar but sometimes diverge, for example vulkan glsl is much stricter with explicit bindings and positions, and this is the problem you're running into.

I think the README had this at some point but it no longer seems to be there.
