### ISSUE TITLE
[wgsl-in] Generating wrong `ConstantInner` variant

### ISSUE THREAD

**Issue by JCapucho** [gfx-rs/naga#196]
Given the following piece of wgsl code:
```js
var index : u32 = gl_GlobalInvocationID.x;
if (index >= 5) {
  return;
}
```
The wgsl frontend will generate `ConstantInner::Sint(5)` instead of `ConstantInner::Uint(5)` this causes issues in backends that don't have implicit conversions, for example the glsl es backend will generate
```c
uint index = gl_GlobalInvocationID[0];
if((index >= 5)) {
	return;
}
```
which is wrong and `glslangValidator` complains about the correct code would be
```c
uint index = gl_GlobalInvocationID[0];
if((index >= 5u)) {
	return;
}
```
hence why generating the right variant is important

**Comment by kvark** [comment]
I believe this is not a bug in the WGSL front-end. WGSL doesn't have implicit conversions, and it's still in development. So `index >= 5` is just an error in the shader itself that we'll need to fix.

**Comment by JCapucho** [comment]
Sorry thought wgsl had implicit conversions but i did try making a uint literal as per the wgsl spec and the frontend returned
```rust
ParseError { 
    error: Unexpected(Word("u")),
    scopes: [FunctionDecl, Block, Statement, Statement], 
    pos: (89, 15)
}
```

**Comment by kvark** [comment]
That part is just not implemented that, I assume. The spec text talking about int literals is fairly fresh, and was written after our initial WGSL front-end code was developed.
