### ISSUE TITLE
[glsl-out] [wgsl-out] Incorrect translation of unsigned switch cases as signed

### ISSUE THREAD

**Issue by hanawatson** [gfx-rs/naga#1960]
Translating the following piece of WGSL code to either GLSL 440/450 or WGSL using naga returns no errors, but validating the translated .comp or .wgsl shaders respectively with naga throws an error.

WGSL (works for any unsigned ints that are > 2147483647u, i.e. have a leading bit of 1):
```
@stage(compute) @workgroup_size(1)
fn main() {
	var var0: u32;
    switch var0 {
        case 2147483648u: {
            break;
        }
        default: {}
    }
}
```

Error validating GLSL:
```
    error: Cannot apply the unary op to the argument
           ┌─ test.comp:10:14
           │
        10 │         case -2147483648u:
           │              ^^^^^^^^^^^^
```

Error validating WGSL:
```
    error: expected unsigned integer literal, found `-2147483648u`
          ┌─ test.wgsl:7:14
          │
        7 │         case -2147483648u: {
          │              ^^^^^^^^^^^^ expected unsigned integer
          │
          = note: invalid digit found in string
        
        Could not parse WGSL
```

It seems that the higher the original unsigned int case selector, the lower the translated selector - e.g. for an original selector `3147483648u` the translated, erroring selector becomes `-1147483648u`.

**Comment by teoxoy** [comment]
Looks like the IR only allows `i32` but it should also allow `u32`
https://github.com/gfx-rs/naga/blob/f9dfc38c405be4b97bb2647a7a407c2171c9ba12/src/lib.rs#L1376-L1379
