### ISSUE TITLE
WGSL texture query expressions return signed integers; should return unsigned

### ISSUE THREAD

**Issue by norepimorphism** [gfx-rs/naga#2010]
See here:
https://github.com/gfx-rs/naga/blob/17dcf39a1b2e4282943580302f510955704650f5/src/proc/typifier.rs#L533-L562

The current working and editor's drafts of the WGSL spec indicate that [`textureDimensions`](https://gpuweb.github.io/gpuweb/wgsl/#texturedimensions), [`textureNumLayers`](https://gpuweb.github.io/gpuweb/wgsl/#texturenumlayers), [`textureNumSamples`](https://gpuweb.github.io/gpuweb/wgsl/#texturenumsamples), and [`textureNumLevels`](https://gpuweb.github.io/gpuweb/wgsl/#texturenumlevels) should return unsigned coordinates.

**Comment by norepimorphism** [comment]
I'll make a PR.

**Comment by norepimorphism** [comment]
I'm curious how this is done for MSL. I see in [the MSL spec](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) that `<texture>::{get_width, get_height, get_num_mip_levels}` return a `uint` (p. 189). However, the code excerpt above from `typifier.rs` seems to suggest that all image queries return `Sint` regardless of the function signature defined by the frontend language's spec.

**Comment by JCapucho** [comment]
Naga's IR is based on wgsl semantics, and since the `typifier` is part of the frontend it also follows wgsl semantics (note it doesn't follow each frontend language's spec), so it's the job of the backends to convert the IR into their respective languages while fixing the differences
