### ISSUE TITLE
Add support for uchar and char types for the GLSL front-end

### ISSUE THREAD

**Issue by PlasmaPower** [gfx-rs/naga#2070]
A precursory review of the code suggests that support for 8-bit types already exist, and `uchar` and `char` exist in the metal backend, so I'd hope that this would just involve mapping `uchar` and `char` onto them for the GLSL frontend.

**Comment by JCapucho** [comment]
GLSL doesn't have any `char` or `uchar` type, are you perhaps talking about some extension? If so which?

**Comment by PlasmaPower** [comment]
Hmm, it seems to be nonstandard. Nevermind, sorry.
