### ISSUE TITLE
workgroup_size attribute does not support variable expression

### ISSUE THREAD

**Issue by haoyunfeix** [gfx-rs/naga#2080]
Failed shader:
```javascript
 var a : i32 = 256u;
 @compute @workgroup_size(a, 1u, 1u)
        fn main(@builtin(local_invocation_id) LocalId : vec3<u32>,
                  @builtin(global_invocation_id) GlobalId : vec3<u32>,
                  @builtin(num_workgroups) NumWorkgroups : vec3<u32>) {
          var localId = LocalId;
          var globalId = GlobalId;
          var numWorkgroups = NumWorkgroups;
          }
```
Output:
```
naga .\6842.wgsl
error: expected 32-bit signed integer literal, found 'a'
  ┌─ .\6842.wgsl:2:27
  │
2 │  @compute @workgroup_size(a, 1u, 1u)
  │                           ^ expected 32-bit signed integer literal

Could not parse WGSL
```
This shader should be acceptable due to spec https://gpuweb.github.io/gpuweb/wgsl/#attributes
Each parameter [must](https://gpuweb.github.io/gpuweb/wgsl/#shader-creation-error) be a [const-expression](https://gpuweb.github.io/gpuweb/wgsl/#const-expressions) or an [override-expression](https://gpuweb.github.io/gpuweb/wgsl/#override-expressions).

Related to tfjs issue: https://github.com/tensorflow/tfjs/issues/6842#issuecomment-1262708937

**Comment by SparkyPotato** [comment]
Note that `a` must be declared `const a = 256;` in accordance with the spec.
(Naga does not support this yet)
