### ISSUE TITLE
[glsl-in] swizzle on matrix rows

### ISSUE THREAD

**Issue by j-e10** [gfx-rs/naga#2082]
Running `naga in.vert out.wgsl` on the following input:

```
// in.vert

cat in.vert 
float f(mat4 m)
{
	return m[0].x;
}
```

results in:

```
error: Can't lookup field on this type "x"
  ┌─ in.vert:3:13
  │
3 │     return m[0].x;
  │                ^^
```

Using subscripts instead does work, but it's less convenient if we're doing multiple accesses (e.g., `.xyz`).

**Comment by JCapucho** [comment]
This is fixed by #2079
