### ISSUE TITLE
Error span reported on the declaration of a variable instead of its use

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#2089]
Testcase
```rust
@group(0) @binding(1)
var mip_dst: texture_storage_3d<r32uint, write>;

var<workgroup> result: u32;

@compute
@workgroup_size(1)
fn main() {
	textureStore(mip_dst, vec3<i32>(0), result);
}
```
Error:
>error: 
  ┌─ test.wgsl:4:4
  │
4 │ var<workgroup> result: u32;
  │    ^^^^^^^^^^^^^^^^^^^^^^^^ naga::Expression [5]
> Entry point main at Compute is invalid: 
	The value [5] can not be stored

It's totally unclear from the error that the problem is in `textureStore`.

**Comment by EriKWDev** [comment]
Similar just happened me in naga v23.0.0 but with local variables, the error messsage points to min_d declaration, or rather strangely the first `min` function but gives no context to `textureStore` call

```wgsl
var input_texture: texture_depth_2d;
var input_sampler: sampler;
var output_texture: texture_storage_2d<r32float,write>;

// ..

    let d: vec4<f32> = textureGather(input_texture, input_sampler, uv);
    let min_d = min(min(d[0], d[1]), min(d[2], d[3]));
    // textureStore(output_texture, pixel, vec4(min_d, 0.0, 0.0, 0.0)); // correct
    textureStore(output_texture, pixel, min_d);

```



error:

```yml
error:
   ┌─ :26:17
   │
26 │     let min_d = min(min(d[0], d[1]), min(d[2], d[3]));
   │                 ^^^ naga::Expression [23]

Entry point depth_downsample_main at Compute is invalid:
        The value [23] can not be stored
```

**Comment by cwfitzgerald** [comment]
Please re-file an issue over in https://github.com/gfx-rs/wgpu - this repo is no longer the source of naga maintence
