### ISSUE TITLE
stpq support for texture_2d swizzling

### ISSUE THREAD

**Issue by apexmfer** [gfx-rs/naga#2107]
PLEASE add support for 'stpq' swizzling on texture_2d just like GLSL has.  I am trying to convert GLSL shaders over to wgsl and am having a really hard time without support for important data like this. 

stpq are the texture coordinates

**Comment by cwfitzgerald** [comment]
As it stands, wgsl doesn't support this: https://gpuweb.github.io/gpuweb/wgsl/#vector-multi-component only had xyzw and rgba. While we could potentially add it as a native only extension, that's a rather big hammer for a small problem.

Converting them should be possible with either regex or a manual find and replace depending on the level of automation you need.

**Comment by apexmfer** [comment]
i was told in matrix that xyzw can effectively be used instead of stpq
