### ISSUE TITLE
[msl-out] Struct field @align is ignored

### ISSUE THREAD

**Issue by guusw** [gfx-rs/naga#2125]
I have a storage buffer that looks something like this
```wgsl
struct u_object_t {
	@align(256) baseColor: vec4<f32>,
	invTransWorld: mat4x4<f32>,
	world: mat4x4<f32>,
};
struct u_object_container { elements: array<u_object_t> };
@group(0) @binding(0)
var<storage> u_object: u_object_container;
```

I want to align the `u_object_t` struct to 256, however the generated metal code seems to ignore this alignment. it turns it into this:

```metal

struct u_object_t {
    metal::float4 baseColor;
    metal::float4x4 invTransWorld;
    metal::float4x4 world;
};
typedef u_object_t type_3[1];
struct u_object_container {
    type_3 elements;
};
```

which completely loses the information about the alignment and no longer matching the host layout.

There seems to be a test in access.wgsl too (`AlignedWrapper`) but it also generates code that loses this info.
HLSL does seem to generate padding fields, SPV probably too, since it works for me but I haven't decompiled it to verify yet

**Comment by teoxoy** [comment]
Thanks for the report!
This is a more general issue with the wgsl frontend not propagating struct member alignment to the struct itself.

See #1813

**Comment by guusw** [comment]
Could find a related issue, thanks for pointing me to it.

**Comment by teoxoy** [comment]
No worries :)
