### ISSUE TITLE
Integration with oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by manunio** [gfx-rs/naga#2133]
Hi, I would like to help integrate this project into [OSS-Fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/9025, it contains necessary logic from an OSS-Fuzz perspective to integrate naga.

- OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects, you can find more details in our [FAQ](https://google.github.io/oss-fuzz/faq/).

-  If you would like to integrate, the only thing I need is a list of email(s), it must be associated with a google account like gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by jimblandy** [comment]
This looks great - yes, we'd love to participate!

For a start, please add jblandy@mozilla.com (that is a gmail address).

Is there any way to give access to a role account? We have a team of people working on WebGPU / wgpu / naga at Mozilla, and it would be nice if we could simply subscribe the team.
