### ISSUE TITLE
Issues with textureGather on texture_2d<u32>

### ISSUE THREAD

**Issue by JMS55** [gfx-rs/naga#2135]
Edit: Can't reproduce on naga master. However, now a different validation error is produced in wgpu:
```
Caused by:
    In Device::create_compute_pipeline
      note: label = `ambient_occlusion_denoise_pipeline`
    error matching shader requirements against the pipeline
    unable to filter the texture (ResourceBinding { group: 0, binding: 1 }) by the sampler (ResourceBinding { group: 1, binding: 0 })
    integer textures can't be sampled
```

Caused by the following match ignoring the gather field in naga: https://github.com/gfx-rs/naga/blob/df4e40327c280a038365fb3d4ec839353f06eed3/src/valid/analyzer.rs#L571-L594

---

According to the spec, this should be a valid operation. However, I get the following error in my project:

```
var depth_differences: texture_2d<u32>;

error: Entry point denoise at Compute is invalid
    ┌─ wgsl:106:18
    │
106 │     let edges0 = textureGather(0, depth_differences, point_clamp_sampler, uv);
    │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ naga::Expression [17]
    │
    = Expression [17] is invalid
    = Unable to operate on image class Sampled { kind: Uint, multi: false }
```

Taking a look at naga's source code, it looks like this is an `InvalidImageClass` Err. There's only 3 places it's created, of which the following seems most likely:

https://github.com/gfx-rs/naga/blob/2a11d830bb8a4965758cab787196322de4f24e19/src/valid/expression.rs#L382-L389

It looks like originally this match statement assumes a float texture only, which is a valid assumption when this was originally used for only regular samples, but when gathers were added, this assumption was broken.

**Comment by JMS55** [comment]
@teoxoy this commit https://github.com/gfx-rs/naga/pull/2138/commits/9ddf38e90d4fb522e806c0155a0f3cacd6b6763e turned out to be necessary for my shader https://github.com/JMS55/bevy/blob/gtao/crates/bevy_pbr/src/ssao/gtao.wgsl#L41. The tests I wrote just didn't catch it :/.

**Comment by teoxoy** [comment]
What is the error exactly?

**Comment by JMS55** [comment]
Ah sorry, the error is:
```
Caused by:
    In Device::create_compute_pipeline
      note: label = `ssao_denoise_pipeline`
    error matching shader requirements against the pipeline
    unable to filter the texture (ResourceBinding { group: 0, binding: 1 }) by the sampler (ResourceBinding { group: 1, binding: 0 })
    integer textures can't be sampled
```

**Comment by teoxoy** [comment]
This looks like it's caused by this validation error over in wgpu: https://github.com/gfx-rs/wgpu/blob/f14bee6740b8755afa362c3be6ef4b225209871a/wgpu-core/src/validation.rs#L1071

I think we should allow those through if the `SamplerBindingType` is `NonFiltering`.
