### ISSUE TITLE
Unreachable reached in `originating_global`

### ISSUE THREAD

**Issue by PROMETHIA-27** [gfx-rs/naga#2140]
According to `Function::originating_global`'s documentation: 
> Assuming that pointer is a series of Access and AccessIndex expressions that ultimately access some part of a GlobalVariable, return a handle for that global.
If the expression does not ultimately access a global variable, return None.

So I expected this to not panic:
```rust
let globals: FastHashSet<Handle<GlobalVariable>> = point
    .function
    .expressions
    .iter()
    .map(|(handle, _)| {
        point.function.originating_global(handle)
    })
    .flatten()
    .collect();
```
However, it panics with an unreachable error when a handle to a `Load` expression is passed to `originating_global`:
```rust
loop {
    pointer = match self.expressions[pointer] {
        crate::Expression::Access { base, .. } => base,
        crate::Expression::AccessIndex { base, .. } => base,
        crate::Expression::GlobalVariable(handle) => return Some(handle),
        crate::Expression::LocalVariable(_) => return None,
        crate::Expression::FunctionArgument(_) => return None,
        // There are no other expressions that produce pointer values.
        _ => unreachable!(),
    }
}
```
I don't know exactly how this should be fixed, but I'd imagine a load operation should be matched on as a way to produce a global (you can load a global, right?) and the unreachable should be replaced with `None` to be consistent with the description. 
Some other issues I can see:
- It will panic if a constant is reached
- There are many expressions that could access a global that will be panicked on instead of returning `Some` or `None`

How should this be addressed? I'd be willing to put in a PR for it.

**Comment by teoxoy** [comment]
Well, it does say that the `pointer` is a series of `Access` and `AccessIndex` expressions ending in one of the variable expressions.

It looks like this is only used in the `msl` backend and called with this assumption in mind.

I guess we can make the docs more explicit but what is your usecase for this?

**Comment by teoxoy** [comment]
I also think we have a bunch of things in our public API that we shouldn't.

I opened https://github.com/gfx-rs/naga/issues/2141 to track that.
