### ISSUE TITLE
Add predeclared vector and matrix type aliases

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/naga#2144]
see
https://gpuweb.github.io/gpuweb/wgsl/#vector-types
https://gpuweb.github.io/gpuweb/wgsl/#matrix-types

**Comment by LukasKalbertodt** [comment]
Seems like this can be closed? The referenced PR is merged and was released as 0.12

**Comment by teoxoy** [comment]
Fixed by https://github.com/gfx-rs/naga/pull/2251
