### ISSUE TITLE
Disallow ptr to workgroup fn arguments

### ISSUE THREAD

**Issue by teoxoy** [gfx-rs/naga#2159]
Remove `As::WorkGroup` from here:
https://github.com/gfx-rs/naga/blob/bf4e62b1ac78759705f544f71bf0b43b654a163c/src/valid/type.rs#L175

Additionally, I think we can remove this altogether since right below it, we check if the type can be used as an `ARGUMENT`
https://github.com/gfx-rs/naga/blob/bf4e62b1ac78759705f544f71bf0b43b654a163c/src/valid/function.rs#L888-L903

ref https://github.com/gpuweb/gpuweb/pull/3422

**Comment by jimblandy** [comment]
I don't think we can remove it altogether from `type.rs`. See the comment later:

```
                // `Validator::validate_function` actually checks the storage
                // space of pointer arguments explicitly before checking the
                // `ARGUMENT` flag, to give better error messages. But it seems
                // best to set `ARGUMENT` accurately anyway.
```
