### ISSUE TITLE
Miscompilation to SPIR-V when the `default` branch of a `switch` is not at the last place

### ISSUE THREAD

**Issue by torokati44** [gfx-rs/naga#2181]
See the exact shader (incl. the workaround) here: https://github.com/ruffle-rs/ruffle/pull/8262/commits/e432e37679a79016a0d01243d7c8639f77eb69fb

The original version worked right with the OpenGL (and probably with the DX12) backend of `wgpu`, but not with the Vulkan one - at least on Linux. The new one works even in the latter case.

This is about as much as I am able to provide at the moment, sorry if it's too little.

**Comment by jimblandy** [comment]
@torokati44 We recently made some changes to the SPIR-V back end's switch statement handling, in changesets be70a2ec and eccdc0ae.

If you're able to, could you confirm that the bug occurs in the most recent Naga sources (say, 461fdda4)?

If the bug does occur with that commit, could you see if it occurs in bf4e62b1?

**Comment by jimblandy** [comment]
> See the exact shader (incl. the workaround) here: [ruffle-rs/ruffle@e432e37](https://github.com/ruffle-rs/ruffle/commit/e432e37679a79016a0d01243d7c8639f77eb69fb)

This change appears in [@dinnerbone's blend branch](https://github.com/Dinnerbone/ruffle/commits/blend).

**Comment by jimblandy** [comment]
Based on experiments with the code below, I believe this bug was fixed in be70a2ec. If that is not the case, please reopen this issue and tell us more.

```
fn f(i: i32) -> i32 {
   switch (i) {
     default: { return 200; }
     case 1: { return 100; }
   }
}
```

In the parent of be70a2ec, 34551474, Naga produces:

```
          %8 = OpFunction %int None %9
          %7 = OpFunctionParameter %int
          %6 = OpLabel
               OpBranch %10
         %10 = OpLabel
               OpSelectionMerge %11 None
               OpSwitch %7 %12
         %12 = OpLabel
               OpReturnValue %int_200
         %13 = OpLabel
               OpReturnValue %int_100
         %11 = OpLabel
               OpReturnValue %14
               OpFunctionEnd
```

The `OpSwitch` instruction there has only a 'default' branch.

Then, with the fix in be70a2ec, Naga produces:

```
          %8 = OpFunction %int None %9
          %7 = OpFunctionParameter %int
          %6 = OpLabel
               OpBranch %10
         %10 = OpLabel
               OpSelectionMerge %11 None
               OpSwitch %7 %12 1 %13
         %12 = OpLabel
               OpReturnValue %int_200
         %13 = OpLabel
               OpReturnValue %int_100
         %11 = OpLabel
               OpReturnValue %14
               OpFunctionEnd
```

This looks correct to me.

**Comment by torokati44** [comment]
Thank you so much for the quick investigation, and the even quicker fix! :)

> If you're able to, could you confirm that the bug occurs in the most recent Naga sources (say, https://github.com/gfx-rs/naga/commit/461fdda4250cdf9aa49de960afd0fa5042a51bc9)?

Oh, sorry, I should have done that before submitting this report, my apologies. :|

> Based on experiments with the code below, I believe this bug was fixed in https://github.com/gfx-rs/naga/commit/be70a2ec03cd02db0c03cbfb95f49f3b568aa2be. If that is not the case, please reopen this issue and tell us more.

While I have not yet verified it myself, I believe you based on your pasted code snippets!

> This change appears in [@dinnerbone's blend branch](https://github.com/Dinnerbone/ruffle/commits/blend).

Cc: https://github.com/ruffle-rs/ruffle/pull/8262

**Comment by teoxoy** [comment]
So, this sounds like something we fixed on master and have no release yet containing it.

**Comment by torokati44** [comment]
I think so, yeah.
