### ISSUE TITLE
[wgsl-in] panic on malformed input

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/naga#2209]
The following program causes Naga to panic:

```
fn S()3-array<f32,0f>()=v}
```

The crash:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/front/wgsl/mod.rs:1388:83
```

**Comment by SparkyPotato** [comment]
Due to #2216, the above code is transformed to
```rs
fn S() {
    -array<f32, 0f>() = v
}
```
(There seems to be another bug in the parser where it doesn't error on the missing `;`?)
It can be further lowered into
```rs
fn S() {
    let x = array<f32, 0f>();
}
```
The `unwrap` occurs when lowering zero-value arrays with invalid sizes.
