### ISSUE TITLE
Nested conversion does not work

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/naga#222]
When using a nested conversion, this does seem to produce some weird result in the WGSL front-end. Using the following WGSL:
```
[[stage(fragment)]]
fn main() -> void {
    var int_1: i32 = i32(u32(1));
}
```

One would expect to get two `Expression::As`, where the last `Expression::As` is the value that needs to be stored in `int_1`, but the WGSL produces the following IR:
```
expressions: Arena {
  data: [
    Constant(
      Handle(1),
    ),
    Compose {
      ty: Handle(2),
      components: [
        Handle(1),
      ],
    },
    As {
      expr: Handle(2),
      kind: Sint,
      convert: true,
    },
    LocalVariable(
      Handle(1),
    ),
  ],
},
```

The inner conversion, `u32(1)` is expressed as an `Expression::Compose`. What I expect is:
```
expressions: Arena {
  data: [
    Constant(
      Handle(1),
    ),
    As {
      expr: Handle(1),
      kind: Uint,
      convert: true,
    },
    As {
      expr: Handle(2),
      kind: Sint,
      convert: true,
    },
    LocalVariable(
      Handle(1),
    ),
  ],
},
```

I haven't tested other combination with non scalar conversions, but I expect all kinds of nested expressions to behave like this.

**Comment by Systemcluster** [comment]
This seems to work as expected now:

```ron
expressions: [
	Constant(1),// [0]
	As(
		expr: 1,
		kind: Uint,
		convert: true,
	),// [1]
	As(
		expr: 2,
		kind: Sint,
		convert: true,
		),// [2]
	LocalVariable(1),
],
```
