### ISSUE TITLE
Confusing error message due to missing `{`

### ISSUE THREAD

**Issue by dj2** [gfx-rs/naga#2249]
I created a shader missing a `{`, essentially as below:

```
@vertex
fn vs_main(@builtin(vertex_index) idx: u32) -> VertexOutput
  var out: VertexOutput;
  ...
}
```

The error produced by Naga was:

```
Shader '' parsing error: expected assignment or increment/decrement, found ':'
  ┌─ wgsl:9:12
  │
9 │     var out:  VertexOutput;
  │            ^ expected assignment or increment/decrement


    expected assignment or increment/decrement, found ':'
```

This took me a long time to realize the `{` was missing as I was trying to figure out why the syntax for my `var` declaration could be wrong.

**Comment by SparkyPotato** [comment]
This was fixed in https://github.com/gfx-rs/naga/commit/bb20ae8e796f50f30d164a56067524026cc9ebb8.
Should be out in the next `wgpu` release.
