### ISSUE TITLE
glsl-out: `invariant gl_FragCoord` might not be allowed under WebGL2

### ISSUE THREAD

**Issue by grovesNL** [gfx-rs/naga#2252]
glsl-out emits `invariant gl_FragCoord` because of invariant position (e.g., for wgsl-in this might look like `@invariant @builtin(position) position`), but this doesn't compile under WebGL2/ANGLE.

I opened https://github.com/KhronosGroup/WebGL/issues/3518 to try to clarify the intended behavior because this seems to be allowed for WebGL1.

We might want to consider skipping `invariant` for `gl_FragCoord` for now until the intended WebGL2 behavior is clarified.

**Comment by teoxoy** [comment]
Hmm, so it sounds like the [GLSL ES 3.0 spec](https://registry.khronos.org/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf) is ambiguous here.

**Comment by grovesNL** [comment]
Right, the GLSL ES 3.00 spec mentions that outputs cannot have `invariant` (ES 1 doesn't have this restriction)

>RESOLUTION: Only allow invariant declarations on outputs.

but later mentions `gl_FragCoord` specifically when talking about built-ins

>How does this rule apply to the built-in special variables.
Option 1: It should be the same as for varyings. But gl_Position is used internally by the rasterizer as
well as for gl_FragCoord so there may be cases where rasterization is required to be invariant but
gl_FragCoord is not.
Option 2: gl_FragCoord and gl_PointCoord can be qualified as invariance if and only if gl_Position and
gl_PointSize are qualified invariant, respectively.

which implies that the variance for `gl_FragCoord` could actually vary (pardon the pun!)

**Comment by teoxoy** [comment]
Reopening to track the spec disambiguation.
