### ISSUE TITLE
GLSL front-end

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#23]
Shipping glsl_to_spirv has been a major pain for all gfx-rs related projects, see https://github.com/gfx-rs/gfx/issues/2546
Building and deploying it is a portability nightmare.

It would be great to have a front-end for GLSL here, in the lines of https://github.com/jrmuizel/glsl-to-spirv , which uses https://crates.io/crates/glsl parser.

**Comment by shika-blyat** [comment]
Hi. I'd be interested to work on this, i'd just like to know if the IR used by naga is documented somewhere ?

**Comment by kvark** [comment]
@shika-blyat Naga IR is basically `naga::Module` and whatever it contains. So you can generate the documentation locally, look at other front-ends and backends if you aren't sure what things are, and ask questions on #naga:matrix.org

**Comment by shika-blyat** [comment]
Okay, thank you, i'll dive into in the week then

**Comment by shika-blyat** [comment]
I have some bad news: i can't work anymore on the frontend  for the moment because school restarts soon. I hope i'll be able to work on it again during holidays

**Comment by kvark** [comment]
This has been worked on by @pjoe for a while 🥇 
More concrete bugs to follow!
