### ISSUE TITLE
[wgsl-in] 0.0 / 0.0 should not be allowed

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/naga#2313]
Spec says that NaN is generally not defined. I think Tint is right here and Naga should catch this as well as Tint does:

```
Tint WGSL reader failure: :80:17 error: '0.0 / 0.0' cannot be represented as 'abstract-float'
    let a = 0.0 / 0.0;
```

**Comment by ErichDonGubler** [comment]
For reference, this violates the [WGSL spec for abstract numeric types](https://www.w3.org/TR/WGSL/#abstract-types):

> An evaluation of an expression in one of these types must not overflow or produce infinite, NaN, undefined, or indeterminate results.
