### ISSUE TITLE
`naga::valid::ConstantError::UnresolvedComponent` and `UnresolvedSize` are no longer necessary

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/naga#2329]
Now that handles are validated separately before carrying out any other validation, there should be no need for the validator to ever return `naga::valid::ConstantError::UnresolvedComponent` or `UnresolvedSize`. These should be removed.

cc @ErichDonGubler

**Comment by ErichDonGubler** [comment]
I have been successfully nerd sniped. 😆
