### ISSUE TITLE
[spv-in] shaders that use `OpImageQuerySize` to read uint values and do comparisons with them don't pass validation

### ISSUE THREAD

**Issue by expenses** [gfx-rs/naga#2354]
After https://github.com/gfx-rs/naga/pull/2245 the following shader doesn't pass validation:
```hlsl
[[vk::binding(0), vk::image_format("rgba16f")]] RWTexture2D<float4> output_tex; 

[numthreads(8, 8, 1)]
void shader(
    uint3 id: SV_DispatchThreadID
) {
    uint width;
    uint height;
    output_tex.GetDimensions(width, height);

    if (id.x < width) {
        return;
    }

    output_tex[id.xy].x = id.z;
}
```
compiled with `dxc shader.hlsl -T cs_6_6 -E shader -spirv -HV 2021`
```
<snip>
         %20 = OpLoad %type_2d_image %output_tex
         %21 = OpImageQuerySize %v2uint %20
         %22 = OpCompositeExtract %uint %21 0
         %23 = OpCompositeExtract %uint %17 0
         %24 = OpULessThan %bool %23 %22
               OpSelectionMerge %25 None
               OpBranchConditional %24 %26 %25
         %26 = OpLabel
               OpBranch %18
         %25 = OpLabel
         %27 = OpCompositeExtract %uint %17 2
         %28 = OpConvertUToF %float %27
         %29 = OpVectorShuffle %v2uint %17 %17 0 1
         %30 = OpLoad %type_2d_image %output_tex
         %31 = OpImageRead %v4float %30 %29 None
         %32 = OpCompositeInsert %v4float %28 %31 0
         %33 = OpLoad %type_2d_image %output_tex
               OpImageWrite %33 %29 %32 None
               OpBranch %18
         %18 = OpLabel
               OpReturn
               OpFunctionEnd
```
results in this error:
```
[2023-05-25T21:51:46Z ERROR naga::valid::expression] Left: AccessIndex { base: [8], index: 0 } of type Scalar { kind: Uint, width: 4 }
[2023-05-25T21:51:46Z ERROR naga::valid::expression] Right: AccessIndex { base: [11], index: 0 } of type Scalar { kind: Sint, width: 4 }
Function [1] 'shader' is invalid: 
        Expression [14] is invalid
        Operation Less can't work with [13] and [12]
```
this is caused by this cast to an Sint:
https://github.com/evahop/naga/blob/2fe9c2fb19d017ec03722516e45d97bdfd34ab98/src/front/spv/image.rs#L687-L691

Either using  `int` values for `width` and `height` or casting `width` to an `int` fixes this in the comparison, so it's not a huge deal. I'd rather not have to add workarounds like this to my shaders though.

**Comment by evahop** [comment]
It's possible I mistook the spir-v or glsl spec's result type to always be a signed integer in which case this is just a blunder and there is no reason for these casts.

**Comment by expenses** [comment]
@evahop ah, good to know! That's all good, I'll run some tests to check if they can be removed.

**Comment by evahop** [comment]
For some reason I was definitely under the impression the return types were sized https://github.com/gfx-rs/naga/pull/2245#discussion_r1099460386. Were you able to do any testing of that?

**Comment by evahop** [comment]
So this cast exists because the `wgsl` equivalent always returns a `uint`. Looks like `msl` is the same way. So casting here seemed like the simplest way to ensure the output ended up as the right type, but I may have wrongfully assumed the types were both `sint`. Maybe the casting logic needs to be moved to the backend? idk

**Comment by teoxoy** [comment]
The fix for this is to conditionally cast in the spv frontend. We need to cast to signed only if the result type was originally signed.

We are currently always casting since we were assuming that the result type was always signed.

**Comment by evahop** [comment]
@teoxoy Is OpenGL always `Sint`? If that’s the case perhaps it’s casting needs to be moved to the backend as spir-v -> OpenGL involving `uints` likely isn’t handled

**Comment by evahop** [comment]
I'll knock this out in the coming days, just haven't been programing much as of late
