### ISSUE TITLE
Naga conversion rule seems to be inconsistent and breaking?

### ISSUE THREAD

**Issue by Trap101** [gfx-rs/naga#2369]
When I try to convert the vertex part of the example wgsl shader from [learn wgpu tutorial](https://sotrh.github.io/learn-wgpu/beginner/tutorial3-pipeline/#writing-the-shaders) through Naga, I got this
```
#version 450 core
struct VertexOutput {
    vec4 clip_position;
    vec4 color;
};
layout(location = 0) smooth out vec4 _vs2fs_location0;

void main() {
    uint in_vertex_index = uint(gl_VertexID);
    VertexOutput out_ = VertexOutput(vec4(0.0), vec4(0.0));
    float x = (float((1 - int(in_vertex_index))) * 0.5);
    float y = (float(((int((in_vertex_index & 1u)) * 2) - 1)) * 0.5);
    out_.clip_position = vec4(x, y, 0.0, 1.0);
    vec4 _e24 = out_.clip_position;
    out_.color = _e24;
    VertexOutput _e25 = out_;
    gl_Position = _e25.clip_position;
    _vs2fs_location0 = _e25.color;
    gl_Position.yz = vec2(-gl_Position.y, gl_Position.z * 2.0 - gl_Position.w);
    return;
}


```
which seems fine, except gl_vertexID is not a valid token that can be read by naga. And this cannot be passed through `wgpu` to be converted into valid draw call, as, well `gl_VertexID` according to the source code, is not valid, while `gl_VertexIndex` is. 
So i am not sure if this is a rendering side of an issue from wgpu? or a compiling side issue from naga. But this is quite strange to me.

**Comment by cwfitzgerald** [comment]
There are actually two different flavors of GLSL, naga reads vulkan-flavor GLSL (including gl_VertexIndex) and this is what wgpu accepts. naga outputs OpenGL flavored GLSL (including gl_VertexID).

So naga not accepting it's own output is actually expected. If wgpu isn't rendering using glVertexIndex, that's a different problem.
