### ISSUE TITLE
WGSL: Invalid span for error

### ISSUE THREAD

**Issue by sotrh** [gfx-rs/naga#2371]
Consider the following shader code (ignore the terrible formatting as it's generated by code).

```wgsl
struct Vertex {
@location(0) position: vec3<f32>,
@location(1) texcoord: vec2<f32>,
}
struct Uniforms {
mvp: mat4x4<f32>,
}
struct VsOut {
@builtin(position) position: vec4<f32>,
@location(0) texcoord: vec2<f32>,
}
@group(0)
@binding(0)
var<uniform> uniforms: Uniforms;
@group(0)
@binding(1)
var color_tex: texture_2d<f32>;
@group(0)
@binding(2)
var color_samp: sampler;
@vertex
fn textured_mvp (
vert: Vertex,
) -> VsOut {
let position = uniforms.mvp * vec4(vert.position,1.0,);
return VsOut(positionvert.texcoord,);
}

@fragment
fn textured (
vert: VsOut,
) -> @location(0) vec4<f32> {
let color = textureSample(color_tex,color_samp,vert.texcoord,);
return color;
}
```

This code has an error on line 26. This is the error that `naga` (version `0.12.2`) gives:

```
thread 'parser::webgpu::code_gen::tests::test_gen_shader_code' panicked at 'Couldn't parse shader: no definition in scope for identifier: 'positionvert'
```

This is fine, but inspecting the span I get the following `span: Span { start: 0, end: 0 }`. This suggests that the error occurs at the start of the file, and takes up 0 bytes. It should highlight the `positionvert` identifier.

**Comment by teoxoy** [comment]
There is a `span` feature that needs to be enabled in order for the spans to work. Do you have it enabled?

**Comment by sotrh** [comment]
I'm using `wgpu`, so I'm not sure if it's enabled.

**Comment by teoxoy** [comment]
`wgpu` enables `naga`'s `span` feature by default. Could you provide a reproducible example?

**Comment by sotrh** [comment]
This seems to be fixed in the current version
