### ISSUE TITLE
Cuda vs WGSL program execution time

### ISSUE THREAD

**Issue by Sakapoi** [gfx-rs/naga#2405]
I wrote a **trivial function** that performs element-by-element addition of two vectors in Rust, cuda, and wgsl and did a runtime comparison of the programs. Here is a [link](https://github.com/Wandalen/demo_cuda_vs_wgpu) to the results and code. It turns out that the execution time of the wgsl solution is much higher than cuda. Therefore, I had a few questions.

- why is cuda so much faster than wgsl?
- is my code optimal? can it be optimized?
- is it possible to download / upload / work with buffers faster?
- is it worth saving the compiled code to a file between runs?

**Comment by grovesNL** [comment]
In https://github.com/Wandalen/demo_cuda_vs_wgpu/blob/master/wgsl/src/vec_func.wgsl you set `@workgroup_size(1)` which isn't ideal for performance.

I'd recommend looking at how to improve GPU parallelism by using larger workgroup sizes. This isn't specific to WebGPU but there are some WebGPU-specific guides like https://developer.chrome.com/articles/gpu-compute/

There should be some ways to improve buffer copies too, but maybe we could focus on the actual compute time first.

**Comment by Sakapoi** [comment]
> In https://github.com/Wandalen/demo_cuda_vs_wgpu/blob/master/wgsl/src/vec_func.wgsl you set `@workgroup_size(1)` which isn't ideal for performance.
> 
> I'd recommend looking at how to improve GPU parallelism by using larger workgroup sizes. This isn't specific to WebGPU but there are some WebGPU-specific guides like https://developer.chrome.com/articles/gpu-compute/
> 
> There should be some ways to improve buffer copies too, but maybe we could focus on the actual compute time first.

Thanks for the reply. This link helped me a lot!
