### ISSUE TITLE
Support for the .glsl extension

### ISSUE THREAD

**Issue by eliemichel** [gfx-rs/naga#2446]
Using `shader.glsl` as input leads to `Unknown input file extension`. I believe using `.glsl` as an extension for GLSL files is not an exotic practice and should be supported. If the type of shader is needed (frag/vert/comp) this could be added as an command line argument.

**Comment by teoxoy** [comment]
Sounds like a good addition, would you be interested in contributing it?

**Comment by eliemichel** [comment]
Sure, here is a proposal: #2462
