### ISSUE TITLE
[glsl-in] Unsupported compute stage layout qualifiers

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#246]
Running on https://github.com/gfx-rs/gfx/blob/17249afe4c3b219200abb3a5c979984bdcb4a640/examples/compute/shader/collatz.comp
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError { kind: NotImplemented("unsupported layout qualifier(s)") }', examples/convert.rs:91:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by JCapucho** [comment]
This is a good first issue for anyone who wants to start working on the glsl frontend, if anyone wants to work and needs guidance ping me here or in the matrix room.
