### ISSUE TITLE
`indexmap` dependency is out of date

### ISSUE THREAD

**Issue by OvermindDL1** [gfx-rs/naga#2464]
`indexmap` is up to version 2.0 now, `petgraph` in this projects current dependency is using 2.0, this is bringing in both indexmap 1.9.3 and 2.0.0 in the current project increasing code size and full compile-time.

Is there any chance the `indexmap` dependency can be updated to 2.0?

**Comment by cwfitzgerald** [comment]
The indexmap bump is already on trunk (https://github.com/gfx-rs/naga/pull/2426), will land in naga 0.14
