### ISSUE TITLE
Could not find `glsl` in `front` | Linux

### ISSUE THREAD

**Issue by sotrh** [gfx-rs/naga#252]
I'm working on an example of running `wgpu` on multiple platforms. I was running into an issue with my project not building on `travis-ci`. I assumed it was an issue with `shaderc`, so I decided to give `naga` a try.

I'm trying to use the `glsl` frontend, but despite enabling the required features `cargo` is not finding the module. I've included the relevant section of my `cargo.toml` for reference.

```toml
[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
rayon = "1.4"
shaderc = "0.6"
naga = { version = "0.2", features = ["spirv", "pomelo"], git = "https://github.com/gfx-rs/naga" }
```

Here's the relevant build script code.

```rust
use anyhow::*;
use glob::glob;
use naga::back::spv::{Writer, WriterFlags};
use rayon::prelude::*;
use std::fs::{read_to_string, write};
use std::path::PathBuf;


// Snipped...

fn main() -> Result<()> {
    let mut shader_paths = Vec::new();
    shader_paths.extend(glob("./src/**/*.vert")?);
    shader_paths.extend(glob("./src/**/*.frag")?);
    shader_paths.extend(glob("./src/**/*.comp")?);
    shader_paths.into_par_iter().map(|glob_result| {
        let src_path = glob_result?;
        let extension = src_path.extension()
            .context("File has no extension!")?
            .to_str()
            .context("Extensions cannot be converted to &str!")?;

        let stage = match extension {
            "vert" => naga::ShaderStage::Vertex,
            "frag" => naga::ShaderStage::Fragment,
            "comp" => naga::ShaderStage::Compute,
            _ => bail!("Unsupported shader: {}", src_path.display()),
        };

        let spv_path = src_path.with_extension(format!("{}.spv", extension));
        let src = read_to_string(src_path)?;
        let module = naga::front::glsl::parse_str(&src, "main", stage);

        let spv = Writer::new(&module.header, WriterFlags::NONE).write(&module);
        let bytes = spv
            .iter()
            .fold(Vec::with_capacity(spv.len() * 4), |mut v, w| {
                v.extend_from_slice(&w.to_le_bytes());
                v
            });
        
        write(&spv_path, bytes.as_slice())
            .context(format!("Unable to write shader to file: {}", spv_path.display()))
    }).collect::<Result<_>>()
}
```

It's weird because code completion sees `glsl` as well as `glsl_new`, but when I `cargo run`, it's nowhere to be found.

Here's a link to the GitHub branch I'm working on https://github.com/sotrh/wgpu-multiplatform/tree/naga

EDIT: This seems to be an issue on `docs.rs` as well. https://docs.rs/naga/0.2.0/naga/front/index.html The `msl` module is visible, but the others aren't.

**Comment by kristoff3r** [comment]
I'm not sure why docs.rs doesn't show any features, but you need to explicitly add the glsl-in feature (or simply enable all features).

Also, the GLSL parser has a lot of stuff missing still, so unless you want to contribute here your time might be better spent fighting shaderc for the time being.

**Comment by kvark** [comment]
Today, all frontends and backends are feature-gated. It was partially the case for naga v0.2 as well.
We'll need to convince the docs rs to build with all features...

**Comment by kvark** [comment]
The feature you are missing is "glsl"
