### ISSUE TITLE
OOM triggered when compiling wgsl shader

### ISSUE THREAD

**Issue by wgslfuzz** [gfx-rs/naga#2560]
On git commit 9eb3a1d  naga some kind of resource exhaustion bug when executing `naga input.wgsl output.hlsl`. Setting a ulimit of 4GB terminates the execution, higher limit fail also.

```
memory allocation of 4294967296 bytes failed
[1]    1426281 IOT instruction (core dumped) 
```

```wgsl
@group(0) @binding(2) var g_4: texture_depth_2d_array;
@group(1025612598) @binding(3) var g_5: sampler_comparison;

@fragment
fn fs_main_without_storage() {
    let flip_correction = vec2<f32>(0.0, 0.0) ; 
    textureSampleCompareLevel(g_4, g_5, flip_correction, 0, 0.0); 
} 
```

**Comment by teoxoy** [comment]
Traced it down to this problematic code block:

https://github.com/gfx-rs/naga/blob/9eb3a1dc8a522e627b266f9157442f0fe8b65ec9/src/valid/interface.rs#L771-L773
