### ISSUE TITLE
[glsl-in] Support for casting

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/naga#277]
It is not yet possible to cast. Using the following GLSL code:

```glsl
#version 450

void main() {
    float a = float(1);
}
```

This does not crash the compilation, but rather results for some reason to `Expression::Compose`, instead of the expected `Expression::As`.

**Comment by pjoe** [comment]
Currently glsl-in sees this as a type constructor, that always result in compose. Thinking it should be easy enough to have it use `Expression::As` when there is only one component.

**Comment by Napokue** [comment]
Fixed in #278
