### ISSUE TITLE
[glsl-in] Support for Layout Qualifiers

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/naga#282]
It seems that Layout Qualifiers aren't implemented yet for glsl-in. This is a blocker for at least 3 wgpu-rs examples, so I think this would be a great implementation to have in the near future.

- Boids - [boids.comp](https://github.com/gfx-rs/wgpu-rs/blob/517ce3ef8d65fcd906c66d4cf2d31b8e636f452d/examples/boids/boids.comp) - There are quite a few different qualifiers used here.
- Hello-compute - [shader.comp](https://github.com/gfx-rs/wgpu-rs/blob/517ce3ef8d65fcd906c66d4cf2d31b8e636f452d/examples/hello-compute/shader.comp)
- Water - [terrain_shader.frag](https://github.com/gfx-rs/wgpu-rs/blob/517ce3ef8d65fcd906c66d4cf2d31b8e636f452d/examples/water/terrain_shader.frag)

**Comment by ColdIce1605** [comment]
btw all links give 404

**Comment by kvark** [comment]
@ColdIce1605 fixed now

**Comment by JCapucho** [comment]
Closing this in favor of more concrete issues
#902 #901 #899 #246
