### ISSUE TITLE
[glsl-in] Support for keyword "const"

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/naga#285]
As I'm taking an inventory of what is missing for the wgpu-rs examples, I have found that the keyword "const" is not implemented for glsl-in. However, I found this [TODO](https://github.com/gfx-rs/naga/blob/master/src/front/glsl/parser.rs#L520). So there were attempts to add it.

There are already 4 shaders in the wgpu-rs examples depending on this support, so this would be a great addition to have, and I can imagine that a lot more shaders use the "const" keyword.

**Comment by JCapucho** [comment]
This should be fixed with the new parser, please reopen if it isn't the case.
