### ISSUE TITLE
[glsl-in] AccessIndex not generated when using builtin

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/naga#288]
When using the following GLSL:
```
#version 450 core
void main() {
    gl_Position = vec4(1);
}
```

Naga's `glsl-in` translates the `gl_Position` to a Statement::Store with as pointer to the variable and as value to the  composite object. The pointer however, has to point to an `AccessIndex` instead of directly the variable.

Difference can be seen here:

GLSL -> SPV (Naga):
https://wasm-shaders.vercel.app/

GLSL -> SPV (Glslang):
http://shader-playground.timjones.io/28f92af5ec10fba8cd6a9c6baec37849

**Comment by kvark** [comment]
> The pointer however, has to point to an AccessIndex instead of directly the variable.

That's not correct in general. If `gl_Position` is implicit, then it's fine to store into it directly, and the code should work correctly.

If, however, it's a part of the "out" structure like this:
```glsl
out gl_PerVertex {
    vec4 gl_Position;
};
```
then... we need to figure out what to do with it. It's not clear. The IR needs to figure out if it permits builtins in I/O structures or not. My feeling is that for IR it's just extra functionality that doesn't help it in any way, so it should expect the builtins to be outside of structs at all times. For this to happen, the GLSL frontend would need to do more work - when it detects cases like this (specifically `out gl_PerVertex` stuff), it should not make IR aware of this structure at all.

@pjoe any concern with following that route?

**Comment by pjoe** [comment]
Sounds like the cleanest solution.

There is work to be done in glsl-in for `gl_PerVertex` regardless, so might as well do it right :)

**Comment by kvark** [comment]
Let's close in favor of #290, which is more concrete
