### ISSUE TITLE
Needs a readme

### ISSUE THREAD

**Issue by icefoxen** [gfx-rs/naga#3]
Because I am apparently subscribed to issues here but I  can't even remember what it's for anymore.

**Comment by mrec** [comment]
Just copypasting the [announcement blog post](https://gfx-rs.github.io/2019/07/13/javelin.html) would be a decent start, although as an outsider I'm not sure whether this project is still alive.

**Comment by kvark** [comment]
The project is trying to figure out what basis to use, still. `rspirv` development turned out quite hard.

**Comment by kvark** [comment]
Fixed in e1a6b5aa554d97b1edef4028933405770e55a02c
