### ISSUE TITLE
Required SPIR-V capabilities

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#312]
The way it's defined by SPIR-V spec is - for each instruction there can be a set of capabilities, such that if any of the set is enabled, the instruction is valid to use. If we are considering all the instructions, then their requirement would be a mix of different sets. This is not the same as just a union of all sets that we currently use.

**Comment by teoxoy** [comment]
This was iterated on and fixed in:

- https://github.com/gfx-rs/naga/pull/315
- https://github.com/gfx-rs/naga/pull/777
- https://github.com/gfx-rs/naga/pull/881
- https://github.com/gfx-rs/naga/pull/1256
