### ISSUE TITLE
Consider removing Pomelo

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#327]
Now that we have experience with using Pomelo for parsing GLSL, we can see the following disadvantages:
  - all the parsing is opaque to rustfmt
  - hard to debug
  - extra dependency

This is an open question - how much of an advantage does Pomelo bring to the table to justify the cost?

For comparison, WGSL frontend has a hand-written recursive descend parser, and I'm very happy about the way it's structured so far. Of course, WGSL has a benefit of being designed up-front with ease of parsing in mind, but it's still tempting to try out a similar approach to GLSL.

**Comment by pjoe** [comment]
There are (as always) pros and cons 😄 

I still very much like how the pomelo parser rules maps directly to the spec and how you don't need to figure out possible next token for selecting which recursive descent branch to take.

But it being a macro causes pains with: rustfmt, rust analyzer (somewhat at least), debugging, etc.

A good first step would be to move any substantial logic out of the macro (which has already been done in some areas, like variables.rs).

Another more drastic refactoring would be to let pomelo only do simple parsing to a 'parse tree' and then have a second pass (visitor pattern), turning the parse tree into naga IR.

And 3rd option would be to remove pomelo entirely. My gut feeling though is that as GLSL is a somewhat complex beast, crafting the parser entirely by hand would be a substantial task.

Just my 2 cents 😄

**Comment by JCapucho** [comment]
The new parser has been merged, so I'm closing this.
