### ISSUE TITLE
Reflect all the resource binding names in GLSL backend

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#334]
If explicit bindings are not supported, the host side needs to be able to query the uniform/storage buffer bindings by name. That means we need to return the names we generate. Currently, we are only returning the generated texture-sampler names.

Related to https://github.com/gfx-rs/gfx/pull/3533

**Comment by Gordon-F** [comment]
Look like we fixed it in glsl backend (https://github.com/gfx-rs/naga/pull/555, https://github.com/gfx-rs/naga/pull/606)? Or maybe I miss something?
