### ISSUE TITLE
Generated SPIR-V structures are missing the offset decorations

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#336]
> VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (7060244)] : Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x555557536d20, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Structure id 19 decorated as Block must be explicitly laid out with Offset decorations.
  %_struct_19 = OpTypeStruct %mat4v4float

This is a blocker for enabling experimental shader support in wgpu-rs examples.

**Comment by parasyte** [comment]
The WGSL parser is also missing offset decorations.

**Comment by kvark** [comment]
The parser now expects spans (only when necessary), see https://github.com/gpuweb/gpuweb/issues/1303
