### ISSUE TITLE
SPIR-V writer panics with local array indexing

### ISSUE THREAD

**Issue by parasyte** [gfx-rs/naga#346]
I created a minimal test case.

```
$ cat test.wgsl
const foo: array<f32, 3> = array<f32, 3>(1.0, -1.0, 0.0);
fn main() {
    var bar: f32 = foo[1];
}

$ cat test.param.ron
(
    spv_capabilities: [ Shader ],
    mtl_bindings: {},
)

$ RUST_BACKTRACE=1 cargo run --example convert --features=wgsl-in,spv-out -- test.wgsl test.spv
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/examples/convert test.wgsl test.spv`
thread 'main' panicked at 'no entry found for key', src/back/spv/writer.rs:643:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/0b644e419681835bd0f5871c3bfbd648aa04f157/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/0b644e419681835bd0f5871c3bfbd648aa04f157/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/0b644e419681835bd0f5871c3bfbd648aa04f157/library/core/src/option.rs:1260:5
   3: core::option::Option<T>::expect
             at /Users/parasyte/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /Users/parasyte/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/collections/hash/map.rs:1096:9
   5: naga::back::spv::writer::Writer::write_type_declaration_arena
             at ./src/back/spv/writer.rs:643:41
   6: naga::back::spv::writer::Writer::get_type_id
             at ./src/back/spv/writer.rs:228:26
   7: naga::back::spv::writer::Writer::write_constant_type
             at ./src/back/spv/writer.rs:768:31
   8: naga::back::spv::writer::Writer::get_constant_id
             at ./src/back/spv/writer.rs:243:37
   9: naga::back::spv::writer::Writer::write_expression_raw
             at ./src/back/spv/writer.rs:1118:26
  10: naga::back::spv::writer::Writer::write_expression_pointer
             at ./src/back/spv/writer.rs:991:13
  11: naga::back::spv::writer::Writer::write_expression_raw
             at ./src/back/spv/writer.rs:1016:21
  12: naga::back::spv::writer::Writer::write_expression
             at ./src/back/spv/writer.rs:967:13
  13: naga::back::spv::writer::Writer::write_block
             at ./src/back/spv/writer.rs:1539:25
  14: naga::back::spv::writer::Writer::write_function
             at ./src/back/spv/writer.rs:407:9
  15: naga::back::spv::writer::Writer::write_logical_layout
             at ./src/back/spv/writer.rs:1579:22
  16: naga::back::spv::writer::Writer::write
             at ./src/back/spv/writer.rs:1615:9
  17: naga::back::spv::write_vec
             at ./src/back/spv/mod.rs:62:5
  18: convert::main
             at ./examples/convert.rs:186:23
  19: core::ops::function::FnOnce::call_once
             at /Users/parasyte/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Backtrace points to panic while indexing this `HashSet`: https://github.com/gfx-rs/naga/blob/6710f5954e707ca144805bab0b71a8cd46a82034/src/back/spv/writer.rs#L643

**Comment by parasyte** [comment]
I dug into this a bit yesterday. Here are my findings.

Composite `const` types are written here: https://github.com/gfx-rs/naga/blob/3bf7f4106837dfcb48d441b045b4540ce631978f/src/back/spv/writer.rs#L761-L774 The call to `self.get_type_id()` tries to resolve the composite `ty` handle...

```rust
    constants: Arena {
        data: [
            // ...
            Constant {
                name: None,
                specialization: None,
                inner: Composite {
                    ty: Handle(2), // Resolved by self.get_type_id()
                    components: [
                        Handle(2),
                        Handle(3),
                        Handle(4),
                    ],
                },
            },
            // ...
        ],
    },
```

This `Handle(2)` points to the types arena:

```rust
    types: Arena {
        data: [
            // ...
            Type {
                name: None,
                inner: Array {
                    base: Handle(1),
                    size: Constant(
                        Handle(1),
                    ),
                    stride: None,
                },
            },
            // ...
        ],
    },
```

`self.get_type_id()` in turn calls `self.write_type_declaration_arena()` for any non-Scalar no-Vector types (e.g. Arrays). And this is the branch that specifically handles arrays: https://github.com/gfx-rs/naga/blob/3bf7f4106837dfcb48d441b045b4540ce631978f/src/back/spv/writer.rs#L630-L650

The panic occurs in there while looking up the const array `size` (see the type arena block above). `Constant(Handle(1))` points back to the constants arena, but this constant hasn't been seen yet by the parser. I have attempted to patch this by populating the `lookup_types` handle for constant-sized arrays while parsing composite types. Something like this:

```patch
diff --git a/src/back/spv/writer.rs b/src/back/spv/writer.rs
index 7f52906..143077f 100644
--- a/src/back/spv/writer.rs
+++ b/src/back/spv/writer.rs
@@ -765,6 +765,13 @@ impl Writer {
                     constituent_ids.push(constituent_id);
                 }

+                // Get the size constant for arrays
+                if let crate::TypeInner::Array { size, .. } = arena[ty].inner {
+                    if let crate::ArraySize::Constant(const_handle) = size {
+                        self.get_constant_id(const_handle, &ir_module)?;
+                    }
+                }
+
                 let type_id = self.get_type_id(arena, LookupType::Handle(ty))?;
                 super::instructions::instruction_constant_composite(
                     type_id,
```

Though that works, the next steps hits this case, because composite types are values: https://github.com/gfx-rs/naga/blob/3bf7f4106837dfcb48d441b045b4540ce631978f/src/back/spv/writer.rs#L993-L997

And now I'm stuck because I don't even know if this was the right path to go down, or what "pointer of a value" even means in the context of SPIR-V.

**Comment by kvark** [comment]
Thank you for the investigation! This part in particular makes me suspicious:
> Constant(Handle(1)) points back to the constants arena, but this constant hasn't been seen yet by the parser. 

So the constant for the whole array comes before the constant of its size? I believe this would be an error in IR then. It should consider the size of the array to be dependency for the array itself, so the constant for the size needs to come first. IR validator needs to check for this as well. I'll try to look at it from the IR side.

**Comment by kvark** [comment]
I've implemented the relevant validation bits in #347, but it appears to me that WGSL frontend does everything correctly: validation doesn't fire up on your example, and the IR is correct.

**Comment by kvark** [comment]
Looking at the failure in more depth, I see what's missing. It's the very comment you posted:
> //TODO: create a local variable? 

The problem is that the indexing operation (`foo[1]`) in SPIR-V basically *requires* a pointer to the array (see `OpAccessIndex` in SPIR-V). But all we have at this point is a constant *value*. So what we'll need to do (unfortunately so!) is to create a temporary variable, store the array into it, and then call `OpAccessIndex` on it... Apparently that's what glslang does, see the [shader playground](http://shader-playground.timjones.io/c0c61244c4412dab2ced0960433805b8).

Here are the relevant lines:
> %15 = OpConstantComposite %_arr_float_uint_3 %float_1 %float_2 %float_3
> %indexable = OpVariable %_ptr_Function__arr_float_uint_3 Function
> OpStore %indexable %15
> %22 = OpAccessChain %_ptr_Function_float %indexable %19
> %23 = OpLoad %float %22

@parasyte if that's a blocker, you can work around it by creating a value yourself, i.e.
```rust
const foo: array<f32, 3> = array<f32, 3>(1.0, -1.0, 0.0);
fn main() {
    var temp: array<f32, 3> = foo;
    var bar: f32 = temp[1];
}
```

**Comment by parasyte** [comment]
Thanks for that workaround! I'm going to give this a go with my use case. Unfortunately I cannot provide anything more here. I'm wholly unfamiliar with the SPIR-V ABI.

**Comment by parasyte** [comment]
@kvark Did you actually try the workaround? It gives me the same panic as the code in the OP.

**Comment by kvark** [comment]
@parasyte sorry, I figured it was a workaround, but I didn't try it. Looking at it now, it fails indeed, but it's a different panic code. The old one was "getting pointer of a value", the new one is "accessing of non-vector". I'm looking into it now.

**Comment by kvark** [comment]
Oh no, I just had your suggested fix in place. I suppose without your fix the panic is exactly the same, as you said.

**Comment by JCapucho** [comment]
This has been fixed
