### ISSUE TITLE
MatrixStride is not implemented

### ISSUE THREAD

**Issue by parasyte** [gfx-rs/naga#350]
This looks like a validation error. According to VK spec, all array and matrix types in composite objects must provide explicit layout; https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#ShaderValidation

```
$ cat test.wgsl
[[block]] struct Locals {
    transform: [[stride(64)]] mat4x4<f32>;
};

$ cargo run --example convert --features=wgsl-in -- test.wgsl
// ... snip
            Type {
                name: None,
                inner: Matrix {
                    columns: Quad,
                    rows: Quad,
                    width: 4,
                },
            },
// ... snip
```

The `Array` type does include a stride member... I won't copy-paste it here, but you can see that in the code. https://github.com/gfx-rs/naga/blob/bd998f6c32f94dd66b98f23866ede7ed2878e87b/src/lib.rs#L371-L375

**Comment by kvark** [comment]
I believe, even if that's fixed, you'd still required #336 to be implemented before you can do anything useful.
