### ISSUE TITLE
Integrate with snapshot testing

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#41]
https://github.com/mitsuhiko/insta
Depends on #32

**Comment by paulkernfeld** [comment]
I just pushed a branch with a prototype of this implementation, but maybe it doesn't make sense to open a PR until #48 is merged.

**Comment by kvark** [comment]
Ah I see. Yes, let's merge serialization first, then make it nice (the `Handle` stuff), then proceed with snapshots. And thank you for all the hard work here, it's amazing to see these changes coming :heart:

**Comment by pjoe** [comment]
One issue: having the handle ids in the snapshots will fail the cases where ordering changes, but module is still semantically identical. Think e.g. a different glsl parser that orders expressions slightly different.

I'm not sure general snapshot testing can handle this. I've previously worked on some similar testing for a glTF exporter, where we ended up de-referencing indexed data before doing comparison between actual and expected results. In this way you 'abstract away' the specific ordering and index values, where they don't have any semantic difference.
