### ISSUE TITLE
WGSL: Array of Vec seems to cause a parser error

### ISSUE THREAD

**Issue by sshashank124** [gfx-rs/naga#415]
For example: if I have a type alias as follows:

```
type PixelArr = array<vec4<f32>>;
```

I get an error as follows:

> Failed to parse WGSL code: error while parsing WGSL in scopes [TypeDecl, TypeDecl] at line .. pos ..: unexpected token ShiftOperation('>'), expected paren

Currently, I have a workaround for this by using an intermediate type alias:

```
type Pixel = vec4<f32>;
type PixelArr = array<Pixel>;
```

However, it should ideally still be possible to specify `array<vec4<f32>>`

**Comment by kvark** [comment]
Interesting! Yeah, I think we need to support this.

**Comment by sshashank124** [comment]
Upon further reading, this is the same as the issue that arose in C++ with the ambiguity between double template closing `>>` and the shift operator `>>`. There are two options for resolving this.

1. The simpler option is to require a space between the two closing delimiters (`array<vec4<f32> >`) so as to treat them as two individual `>`. This would make the syntax `array<vec4<f32>>` illegal
2. The more complex option is to allow this and add context-disambiguation in the parser for this case. There are a few potential approaches for this, as mentioned in [the following link](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1757.html)

Which approach would `naga` prefer? I would also be glad to implement either approach if the help is needed.

**Comment by kvark** [comment]
This is something we'll need to discuss in WebGPU group for WGSL upstream. The decision is not going to be Naga-specific.
