### ISSUE TITLE
WGSL nested loop doesn't work

### ISSUE THREAD

**Issue by J-F-Liu** [gfx-rs/naga#434]
Example code is here: https://github.com/J-F-Liu/image-convolution/blob/master/src/convolution.wgsl

The code runs without error, but doesn't get the expected result.

**Comment by kvark** [comment]
I've done a few tests, the produced SPIR-V looks correct, the produced Metal had an issue that I fixed - #435.
The output shader is 
[test.metal.txt](https://github.com/gfx-rs/naga/files/5941398/test.metal.txt)

It looks like everything is correct both in IR and in the outputs. Would you be able to debug the execution in, say RenderDoc or XCode, to see where does the logic break? It's totally not clear to me so far what the translation could have done wrong.

**Comment by kvark** [comment]
Actually, I have a hypothesis. You were using `EXPERIMENTAL_TRANSLATION` on Metal, and you faced the exact issue #435 that I just fixed. That would explain the wrong results.

**Comment by J-F-Liu** [comment]
I'm using a Windows PC, EXPERIMENTAL_TRANSLATION flag is not used: https://github.com/J-F-Liu/image-convolution/blob/master/src/gpu_device.rs#L120

**Comment by kvark** [comment]
Ok. Would you be able to step through the shader in RenderDoc and see if there are any abnormalities?

**Comment by J-F-Liu** [comment]
Lanched exe file of the example by RenderDoc, but nothing is captured.
The [whole project](https://github.com/J-F-Liu/image-convolution) is dedicated for this issue, maybe some else can also help out.

**Comment by kvark** [comment]
Cool, I'll have a look!

**Comment by kvark** [comment]
@J-F-Liu could you provide more details, please? How do I run it to reproduce the issue, what do you expect and what do you get, on what platform, etc.

**Comment by J-F-Liu** [comment]
Apply gaussian filter to an image will get a blurred image, bigger sigma parameter results larger blurriness.
In convolution.wgsl comment out the inner loop and set `var j: u32 = 3u;`, you can get a blurred but dimmed image.
If the inner loop works, the brightness will remain the same as original image.

**Comment by J-F-Liu** [comment]
Clone https://github.com/J-F-Liu/image-convolution and run `cargo run --example gaussian -- IMAGE_FILE`.
Reproduced the issue on both Windows and Linux.

**Comment by J-F-Liu** [comment]
Verified, thanks.
