### ISSUE TITLE
Call expression namespace inference

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/naga#45]
For the back-end there is now no information about where a function in the call expression is located. It could be a intrinsic/built-in, imported or user declared function. 

In case for SPIR-V there are other opcode instructions used for all three cases. So it would be very hard if not impossible at the moment to determine where to look for the function and what opcode to use.

**Comment by kvark** [comment]
I think this is not an issue any more. We have strong separation between standard library and user functions.
