### ISSUE TITLE
SPIR-V handling with the EXPERIMENTAL_TRANSLATION flag

### ISSUE THREAD

**Issue by acowley** [gfx-rs/naga#455]
I was attempting to compile WGSL to SPIR-V with the `tint` compiler to see if it supports more of the WGSL spec than naga when working with `wgpu-rs`. I built `tint` from source (git revision 22a9f175e0f4b760afd583557d57868c50553409 from 2021-02-10), and compiled the WGSL program on [this gist](https://gist.github.com/acowley/85ecf7df01593f9c2e0a1eadb0bc2744). The gist also includes a full Rust program that exhibits this unusual behavior:

The program has two control flow paths that one may observe by passing either no arguments to the program, or some argument (e.g. `cargo run --bin bug 1`). If no arguments are passed, the `spv` file is loaded with the `EXPERIMENTAL_TRANSLATION` shader flag, and the program works as expected, printing `Output: [1.0, 1.0, 1.0, 1.0]`. If that shader flag is *not* set, then the program prints `Output: [0.000000000000000000000000000000000000005831554, 0.000000000000000000000000000000000000005831554, 0.000000000000000000000000000000000000005831554, 0.000000000000000000000000000000000000005831554]`.

It seems that there is something unusual about the `spv` file produced by tint that causes these differing behaviors. My expectation is that the `EXPERIMENTAL_TRANSLATION` flag would not change behavior when loading a binary SPIR-V file.

The binary `spv` produced by `tint` is available here: [bug.zip](https://github.com/gfx-rs/naga/files/5973094/bug.zip)

**Comment by acowley** [comment]
Progress was made here. If an offset decoration is added to the `struct` field in the WGSL source, i.e.

```
[[offset(0)]] data: [[stride(4)]] array<f32>;
```

(`[[offset(0]]` is the new part), then the `spv` produced by `tint` works with `wgpu` regardless of the `EXPERIMENTAL_TRANSLATION` flag. However, that code change causes the WGSL to be rejected by naga if one uses `wgpu::ShaderSource::Wgsl`.

**Comment by kvark** [comment]
It turned out that the SPV produced by Tint was not valid to start with. We parsed it fine, and we validated the IR, but our parser is not in the business of validating SPIR-V, so it didn't complain.
