### ISSUE TITLE
Cannot define fractional constants

### ISSUE THREAD

**Issue by Diggsey** [gfx-rs/naga#471]
The following will fail to compile:
```wgsl
const w2: vec4<f32> = vec4<f32>(4.0/9.0, 0.0, 0.0, 0.0);
```

(Even if `const` is replaced with `var`, it will still fail)

**Comment by kvark** [comment]
I think the part of WGSL specification related to this is still being hashed out - https://github.com/gpuweb/gpuweb/issues/1272
So we could either just put the concrete values in there, or we can do our best at computing the constants as we parse.
