### ISSUE TITLE
[meta] glslang-generated SPIR-V issues

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#475]
SPIR-V shaders generated by `glslang` are a bit weird. They cause trouble for our SPIR-V front-end:
  - [x] functions get re-ordered, so that dependent function are not yet processed. See https://github.com/gfx-rs/naga/issues/265#issuecomment-778834989
    - fixed in #574
  - [x] interface block is used for `gl_PerVertex`. This will be easier to implement once https://github.com/gpuweb/gpuweb/pull/1426 lands.

**Comment by dneto0** [comment]
> interface block is used for gl_PerVertex. 

Yes, this was a pain for the Tint SPIR-V reader.  
- ClipDistance and CullDistance should be dropped.
- Don't pass through PointSize.  But reading the value should result in float 1.0;  writing to it should be ignored.

**Comment by kvark** [comment]
@dneto0 we can't cut the corners you suggest, since Naga aims to be more than just a shader compiler for WebGPU. We want to use Naga everywhere:
  - Vulkan users that write shaders in GLSL would use Naga to convert it to SPIR-V
  - gfx-rs users who provide SPIR-V shaders would internally use Naga to build MSL/HLSL from it
  - WebGPU case

So we still want to handle the clip/cull distance and the point size.
