### ISSUE TITLE
[glsl-in] Preprocessor errors

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/naga#484]
The glsl frontend currently treats preprecessor errors as the end of input, causing it sometimes erroneously _succeed_ when encountering shaders it doesn't understand. The offending code is here:
https://github.com/gfx-rs/naga/blob/321420c019aea76e3c51a5829513e07ed0e5509a/src/front/glsl/lex.rs#L353-L361

And how this can play out on an actual shader:

```glsl
#version 450 core

#if 0    // this line is ignored since the preprocessor doesn't understand '#if'
#endif   // this one triggers an 'unmatched endif' error, which prevents future lines from being processed

fn main() { ... }   // all this ignored
```

**Comment by JCapucho** [comment]
The parser should now handle preprocessor errors and if directives are now supported so I'm closing this.
