### ISSUE TITLE
Validation of constant sized array types: signed or unsigned

### ISSUE THREAD

**Issue by acowley** [gfx-rs/naga#516]
The [validator requires](https://github.com/gfx-rs/naga/blob/master/src/proc/validator.rs#L465) that a constant-sized array's size be a `uint`. This requires a `u` suffix on a literal used for this purpose (e.g. `array<vec2<f32>, 3u>`, but the tint compiler rejects a program with a `u` suffix on an array size. All [examples in the spec](https://gpuweb.github.io/gpuweb/wgsl.html#type-declarations) do not include the suffix.

We could change the array type parsing to produce a `UInt` when the literal fits, or we could say that spec and tint should require the `u` suffix, or perhaps another option. I'm happy to help with a change if a change is wanted.

**Comment by kvark** [comment]
Our requirement for u32 stems from https://gpuweb.github.io/gpuweb/wgsl.html#array-types, where you can see `arrayLength` returning `u32` specifically.
I think at least for now we should make it so `i32` is also fine for the array sizes, for convenience. We can come back to this once WGSL has limited form of type inference, and just `5` would automatically be seen as `u32`. At that point, no user code would need to be changed if we relax the requirement today, so we should go for it.
