### ISSUE TITLE
Shader parsing gets stuck in `naga_traverse`

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/naga#520]
Have not identified what it is exactly that it gets stuck on. Debugger shows a long recursive callstack in `naga_traverse`. Waited for a couple of minutes and it did not run into stackoverflow (so who knows maybe it just works if one waits long enough ;-))

Repro:
`cargo run --all-features --example convert -- c:\dev\naga\repro\shader.comp.spv test.ron `
[shader.comp.zip](https://github.com/gfx-rs/naga/files/6032082/shader.comp.zip)
Original shader combines in a few includes but [this](https://github.com/gfx-rs/naga/files/6032102/extrapolate_velocity.comp.txt) should give a good idea of the main structure

This is a somewhat repetitive compute shader. Compiled with `shaderc`

**Comment by kvark** [comment]
[flow.Compute-main.dot.txt](https://github.com/gfx-rs/naga/files/6036683/flow.Compute-main.dot.txt)
