### ISSUE TITLE
Validation of vertex modules requires integer outputs to be declared as `flat`

### ISSUE THREAD

**Issue by thenlevy** [gfx-rs/naga#534]
Declaring a vertex shader output as  `layout(location=0) out uint v_example;` in a glsl source compiled to spirv, causes validation error `InvalidIntegerInterpolation` when trying to create a shader module from the spriv file.

This is fixed by adding the `flat` interpolation qualifiers: `layout(location=0) flat out uint v_example;`, but the use of this qualifier should not be mandatory in the vertex shader source.

**Comment by kvark** [comment]
We should make it so IR doesn't expect interpolation qualifiers on vertex outputs at all, and the frontends make sure to ignore it if present.
