### ISSUE TITLE
[wgsl-in] Adding statements to a block causes implicit return to not be generated

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/naga#536]
Some time ago, we implemented the implicit return for Naga. I found out that this is not getting applied when not having an empty block.

Example that generates implicit `Return { value: None }`:
```
[[stage(vertex)]]
fn main() -> void {

}
```

Example that does not generate implicit `Return { value: None }`:
```
[[stage(vertex)]]
fn main() -> void {
  if(true == true) {
    
  }
}
```

**Note:** I have not tested the other front-ends, so that is the reason I marked it as wgsl-in, but presumably this is something that is done in the middle-end.

**Comment by JCapucho** [comment]
This seems to be fixed but weirdly the return is not added as a new statement to the function body but twice to the ifs `accept` and `reject` block
