### ISSUE TITLE
[spv-in][msl-out] gl_NumWorkGroups: is invalid: InvalidType

### ISSUE THREAD

**Issue by DavidPeicho** [gfx-rs/naga#548]
It looks like there is a type mismatch between SPIR-V and the MSL generated for the global variable `gl_NumWorkGroups`.
When using a SPIR-V shader in WGPU with the Metal backend, the following error occurs:

```
Global variable Handle(2) 'gl_NumWorkGroups' is invalid: InvalidType
```

**Comment by kvark** [comment]
The SPIR-V frontend has the logic to take care of i32->u32 conversion of some builtins, but this one is missing. It's failing in the validation, unrelated to MSL.
