### ISSUE TITLE
Polyfill Kill on HLSL

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#559]
We can't just "discard" there. WGSL follows SPIR-V/MSL/GLSL semantics, where the invocation is terminated, while HLSL has the invocation continuing. So it may technically get into an endless loop or other weird states.
See https://github.com/gpuweb/gpuweb/pull/1476#issuecomment-789064737

**Comment by kdashg** [comment]
WGSL now uses demote-to-helper semantics, so we should be set here.
