### ISSUE TITLE
[glsl-out] Cannot bitcast Uint to Sint

### ISSUE THREAD

**Issue by Gordon-F** [gfx-rs/naga#616]
Reproduction steps:
1. Use [wgpu-rs](https://github.com/gfx-rs/wgpu-rs) master example
2. Run `WGPU_BACKEND=gl cargo run --example mipmap` without `EXPERIMENTAL_TRANSLATION` flag and disabled `cross` feature.

```rust
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `blit`
    Internal error in stage VERTEX: Shader module failed to compile: Custom("Cannot bitcast Uint to Sint") shader compilation failed: Vertex
```

**Comment by kvark** [comment]
I don't think there needs to be a bitcast here at all. Maybe it's a bitcast we generate internally?
In any case, GLSL backend can implement it via regular cast.

**Comment by Gordon-F** [comment]
@kvark We use it inside wgsl shader:
https://github.com/gfx-rs/wgpu-rs/blob/a964fed4bd3385b0f8e52cff4fb8f121249caeee/examples/mipmap/blit.wgsl#L7-L10

Any suggestion how we can find this behavior in IR and fix it?

**Comment by kvark** [comment]
I think from IR perspective, going from Sint to Uint or back is supposed to work the same way between casts and converts. The only case where `convert: bool` makes a difference is when going between integers and floats.
So the GLSL backend should just process this `As` expression like a regular cast. IR seems fine in this case.

**Comment by Gordon-F** [comment]
Digging into this error a little bit and saw that this error was generated from the `naga` side. And reproduces only if I disable `EXPERIMENTAL TRANSLATION` flag  and disabled `cross` feature.

If I understand it right in this case shader path is: WGSL -> Naga IR -> Naga Spv-out -> GLSL. Where we loosing `convert` flag in `Expression::As`.... 🤔

**Comment by kvark** [comment]
No, this isn't a possible path. `cross` is enabled by default in wgpu-rs right now, and the command line in the body of this issue doesn't try to disable it.

**Comment by Gordon-F** [comment]
> No, this isn't a possible path.

I think we can close this issue. Potentially users can disable both `EXPERIMENTAL_TRANSLATION` and `cross` features, but its not naga issue.

**Comment by kvark** [comment]
@Gordon-F are you sure this is the case here? I'd expect an entirely different error if both `cross` and experimental translation were disabled. You wouldn't reach "glsl-out" at all there.
I think we should still fix the lack of the cast in the backend, re-opening.

**Comment by Gordon-F** [comment]
@kvark Retested it again (wgpu-rs 53d92fa6173ed52ccebd916eadfcb8ccd8c113bd):

https://github.com/gfx-rs/wgpu-rs/blob/c5ee9cd98310aee66fb49bc98f4f65590304e4aa/examples/mipmap/main.rs#L280-L286

`RUST_LOG=debug WGPU_BACKEND=gl cargo run --example mipmap --no-default-features`

```rust
[2021-03-29T23:01:07Z WARN  gfx_backend_gl::device] Naga GLSL write: Cannot bitcast Uint to Sint
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `blit`
    Internal error in stage VERTEX: Shader module failed to compile: Custom("Cannot bitcast Uint to Sint") shader compilation failed: Vertex


thread 'main' panicked at 'Handling wgpu errors as fatal by default', src/backend/direct.rs:1889:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kvark** [comment]
Yep, we just need "glsl-out" to treat cast the same way we do for conversion.

**Comment by kvark** [comment]
@Gordon-F I'd like to kick off the next Naga train. Would you want to take a stab at fixing this PR, so that it's included?
