### ISSUE TITLE
Unable to use textureStore

### ISSUE THREAD

**Issue by james-j-obrien** [gfx-rs/naga#624]
According to the WGSL spec I believe I should be able to do something similar to below in a compute shader:

```rust
[[group(0), binding(0)]] var<storage> c_texture : [[access(write)]] texture_storage_2d<rgba8unorm>;

[[stage(compute), workgroup_size(320, 240)]]
fn cs_texture(
  [[builtin(global_invocation_id)]] id: vec3<u32>
) {
  var coords: vec2<i32> = vec2<i32>(i32(id.x), i32(id.y));
  textureStore(c_texture, coords, vec4<f32>(1.0, 0.0, 0.0, 0.0));
}
```

I am attempting to write to a 2d texture with a constant value in every position as a test but am receiving this error:
```
[2021-03-28T03:29:57Z ERROR wgpu_core::device] Failed to parse WGSL code: bad texture c_texture`
```
I can see that this is originating from within the textureStore parser where it expects the expr_context type to be TypeInner::Image but is instead receiving a Pointer with class Storage.

Am I misinterpreting something here or is this a bug, I understand that this compilation is very much experimental.

**Comment by james-j-obrien** [comment]
As a workaround I have been copying from a standard storage array buffer to a texture between the computer and render passes.

**Comment by kvark** [comment]
`var<storage>` is not the right class for this. Could you try this instead:
```rust
[[group(0), binding(0)]] var c_texture : [[access(write)]] texture_storage_2d<rgba8unorm>;
```

**Comment by kvark** [comment]
Actually, looks like the validation is all fine. Dropping the flag.

**Comment by james-j-obrien** [comment]
You are correct this does fix my problem. Thanks.

**Comment by kvark** [comment]
Fwiw, I added a simple test for `textureStore` parsing in #625
