### ISSUE TITLE
[wgsl-in] Follow WGSL spec in indexing matrices like `mat[0]` rather than `mat.x`

### ISSUE THREAD

**Issue by ashpil** [gfx-rs/naga#637]
It seems currently naga expects matrix indexing to work like vector indexing does: just do `mat.x` for the first column. This is mostly fine, but I think it makes sense to follow the [official WGSL spec in this operation](https://gpuweb.github.io/gpuweb/wgsl.html#matrix-access-expr), as that is currently the only source of WGSL syntax/learning material, so it's confusing when naga doesn't behave as it describes.

**Comment by jimblandy** [comment]
I think this is fixed. Consider [tests/in/access.wgsl](https://github.com/gfx-rs/naga/blob/a45b9a6cc691a671aa24a32114b51c5acae02420/tests/in/access.wgsl#L33):

```
struct Bar {
	matrix: mat4x4<f32>;
	matrix_array: array<mat2x2<f32>, 2>;
	atom: atomic<i32>;
	arr: array<vec2<u32>, 2>;
	data: array<AlignedWrapper>;
};

@group(0) @binding(0)
var<storage,read_write> bar: Bar;
...
@stage(vertex)
fn foo(@builtin(vertex_index) vi: u32) -> @builtin(position) vec4<f32> {
        ...
	let b = bar.matrix[index].x;
        ...
	bar.matrix[1].z = 1.0;
```
