### ISSUE TITLE
[spv-in/mtl-out] handle `float length(float x)`

### ISSUE THREAD

**Issue by expenses** [gfx-rs/naga#695]
`glsl` let's you call `length()` on a scalar (for some reason) which just returns the same scalar. SPIR-V does the same with:

```
%21 = OpLoad %float %20
%22 = OpExtInst %float %1 Length %21
```

Metal is a bit more sensible and doesn't have a `metal::length(scalar)` function, so at the moment any code that does the above will fail to compile. I've come up with a solution for the metal backend where the function is just removed if called on a scalar, but because multiple backends are likely to run into this it might be better to handle this while parsing the SPIR-V.

**Comment by kvark** [comment]
Interesting. We need to make a call on whether the IR allows this or not.
To complete the investigation, let's check what WGSL and HLSL expect.

**Comment by expenses** [comment]
`float distance(float a, float b)` has the same problem:
```
msl/4tdGRfImage.spv.metal:82:9: error: call to 'distance' is ambiguous
    if (metal::distance(uv[0u], 0.5 + ((metal::sin((uv[1u] - (_.iTime * 0.5)) * 10.0) * 0.05000000074505806) * uv[1u])) > (metal::sin(uv[1u]) * 0.30000001192092896)) {
        ^~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/31001.160/include/metal/metal_geometric:481:17: note: candidate function
METAL_FUNC half distance(half2 x, half2 y)
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/31001.160/include/metal/metal_geometric:512:17: note: candidate function
METAL_FUNC half distance(half3 x, half3 y)
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/31001.160/include/metal/metal_geometric:543:17: note: candidate function
METAL_FUNC half distance(half4 x, half4 y)
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/31001.160/include/metal/metal_geometric:648:18: note: candidate function
METAL_FUNC float distance(float2 x, float2 y)
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/31001.160/include/metal/metal_geometric:691:18: note: candidate function
METAL_FUNC float distance(float3 x, float3 y)
                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/31001.160/include/metal/metal_geometric:734:18: note: candidate function
METAL_FUNC float distance(float4 x, float4 y)
```

**Comment by kvark** [comment]
Yeah, for both issues, we can make a call to say, at which level this can be resolved: either in the frontends, or in the backends. So there are two factors in play for making the decision:
  1. how much work are we saving in frontends/backends
  2. a more restricted IR is better, with all other equals

Therefore I wrote that we need to complete an investigation, to see where the work would need to be done in either path.

**Comment by expenses** [comment]
For HLSL, the [Microsoft docs](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-length#type-description) say that it takes a `vector,` however a `vector` consists of '[1 component minimum, 4 components maximum (inclusive)](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-intrinsic-functions#component-and-template-types)', so as far as I know, a scalar counts.

`glslc` accepts a scalar input when compiling hlsl:
```hlsl
struct VS_OUTPUT{
    float4 pos: POSITION;
};
VS_OUTPUT main(float4 pos: POSITION){
    VS_OUTPUT output;
    output.pos = float4(length(pos.x), length(pos.y), length(pos.z), length(pos.w));
    return output;
}
```
->
```
         %54 = OpAccessChain %_ptr_Function_float %param %uint_0
         %55 = OpLoad %float %54
         %56 = OpExtInst %float %1 Length %55
         %57 = OpAccessChain %_ptr_Function_float %param %uint_1
         %58 = OpLoad %float %57
         %59 = OpExtInst %float %1 Length %58
         %60 = OpAccessChain %_ptr_Function_float %param %uint_2
         %61 = OpLoad %float %60
         %62 = OpExtInst %float %1 Length %61
         %63 = OpAccessChain %_ptr_Function_float %param %uint_3
         %64 = OpLoad %float %63
         %65 = OpExtInst %float %1 Length %64
         %66 = OpCompositeConstruct %v4float %56 %59 %62 %65
```

**Comment by kvark** [comment]
Yep, I tried HLSL in the shader playground, and it accepts that (as well as `distance` on floats).
Let's proceed with allowing it in IR. Thank you for investigation!

**Comment by expenses** [comment]
Ok, so I think we only have to worry about `length` and `distance` because `normalize(float)` is caught in validation.
`spirv-cross` transforms `length(float)` into `abs(float)` and `distance(float, float)` into `abs(float - float)` which is probably the way to go.
