### ISSUE TITLE
Validation error on `textureDimensions(t)` call

### ISSUE THREAD

**Issue by simast** [gfx-rs/naga#696]
Based on the WGSL spec I understand that the following pseudo code should work and return texture dimensions:

```
[[group(0), binding(1)]]
var t: texture_2d<f32>;
...
// ... and then in a vertex stage:
const size = textureDimensions(t);
```

However wgpu master with naga reports a validation error:

```
Caused by:
    In Device::create_shader_module
    Entry point main at Vertex is invalid
    Expression [7] is invalid
    Unable to operate on image class Sampled { kind: Float, multi: false }
```

Is this expected behavior or a potential bug?

**Comment by kvark** [comment]
That's a bug in Validation, unfortunately. Should be easy to fix. Would you want to try?

**Comment by simast** [comment]
Yes, I will give it a shot with a PR.
