### ISSUE TITLE
Secure out-of-bounds accesses

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#732]
For WebGPU, we need to guarantee that all out-of-bound accesses are not really happening. We can employ one of the following strategies:
  1. Read zeroes, write nothing (follows D3D)
  2. Clamp reads and writes (one of the possible behaviors of Vulkan)
  3. Detect this and early return (signalling a failure of any sort to wgpu).

**Comment by lachlansneff** [comment]
It looks like webgpu requires that the index is clamped. To be specific, if the index is out of bounds, than an index that is inside of bounds is used instead.

https://gpuweb.github.io/gpuweb/wgsl/#array-access-expr

**Comment by kvark** [comment]
Well, the current spec is just plain wrong, it doesn't reflect the consensus of the group.
I filed https://github.com/gpuweb/gpuweb/issues/1649 recently to address this.

**Comment by jimblandy** [comment]
The current WGSL spec says the below, which I think meets our requirements:

> If a reference or pointer access is out of bounds, an invalid memory reference is produced. [Loads](https://gpuweb.github.io/gpuweb/wgsl/#load-rule) from an invalid reference return one of:
> 
> -   a value from any [memory location(s)](https://gpuweb.github.io/gpuweb/wgsl/#memory-locations) of the [WebGPU buffer](https://gpuweb.github.io/gpuweb/#buffers) bound to the [originating variable](https://gpuweb.github.io/gpuweb/wgsl/#originating-variable)
> 
> -   the [zero value](https://gpuweb.github.io/gpuweb/wgsl/#zero-value) for store type of the reference
> 
> -   if the loaded value is a vector, the value (0, 0, 0, x), where x is:
> 
>     -   0, 1, or the maximum positive value for integer components
> 
>     -   0.0 or 1.0 for floating-point components
> 
> [Stores](https://gpuweb.github.io/gpuweb/wgsl/#statement-assignment) to an invalid reference may either:
> 
> -   store the value to any [memory location(s)](https://gpuweb.github.io/gpuweb/wgsl/#memory-locations) of the [WebGPU buffer](https://gpuweb.github.io/gpuweb/#buffers) bound to the [originating variable](https://gpuweb.github.io/gpuweb/wgsl/#originating-variable)
> 
> -   not be executed
> 
> [Read-modify-write atomics](https://gpuweb.github.io/gpuweb/wgsl/#atomic-rmw) that operate on an invalid memory reference must load and store from the same memory locations if they access memory.
