### ISSUE TITLE
[wgsl-in] Support `const` operations in `const` variables

### ISSUE THREAD

**Issue by ashpil** [gfx-rs/naga#733]
I'm not sure whether the official WGSL spec specifies anything about this, but I'm running into a pattern in my code where I'd like to do something like this:

```glsl
const phi_sun: f32 = PI * 2.0;
```

However, the compiler doesn't like this:

```glsl
error: expected separator, found '*'
   ┌─ wgsl:84:25
   │
84 │ const phi_sun: f32 = PI * 2.0;
   │                         ^ expected separator

error: aborting due to previous error
```

**Comment by kvark** [comment]
Unfortunately, the constant initializers in WGSL today can't do this - see `const_expr` grammar in the spec. We definitely do want to have this soon, just struggling with a good constexpr semantic.

**Comment by jimblandy** [comment]
WGSL issues:
- [wgsl] Support compile-time-constants (constexpr) gpuweb/gpuweb/#1272
- Literal unification gpuweb/gpuweb#2200
