### ISSUE TITLE
Varying arrays coming from SPIR-V

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#754]
> [2021-04-22T21:02:05Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([10]), stride: 4 }

We only support scalars and vectors in the interface vars, but apparently SPIR-V allows passing vectors around. Therefore, we need a plan on how to handle this, either in the frontend alone, or in the IR.

**Comment by kvark** [comment]
See also - https://bugs.chromium.org/p/tint/issues/detail?id=737
These array might come from the `gl_CullDistance` builtin.

**Comment by kvark** [comment]
@Nehliin I refer to input/output variables (*not* uniforms).
I believe the original issue is fixed now. IR and MSL handle the arrays, to some extent. But user arrays in I/O are still not allowed.
Please run on latest Naga master and file issues if something still doesn't work!

**Comment by Nehliin** [comment]
I tested with latest naga master now and my .spv shader passes validation (even when using a `mat3` as output variable FYI). I'll hold off switching to wgpu-rs 0.8 until this fix reaches that crate then 👍

**Comment by kvark** [comment]
So Naga from v0.4 branch doesn't accept your SPV? Could you attach the shader here?

**Comment by kvark** [comment]
Looks like we are missing the `inverse` handling in SPV-in. This is a different issue.
