### ISSUE TITLE
Validation error location

### ISSUE THREAD

**Issue by niklaskorz** [gfx-rs/naga#809]
Parser errors indicate the position the error occured through a tuple returned from `ParserError::location`. Validation errors, however, only identify the handle of the function/expression/... the error occured in.
Is there any way to map from such a handle to the location in the source code? This would improve the quality of validation errors a lot and allow easier integration into editors.

**Comment by kvark** [comment]
We haven't got the `codespan` hooked up to validation yet. Basically dupe of #358
I agree it would be very useful!

**Comment by niklaskorz** [comment]
Thanks! Subscribed to that issue now. :)
