### ISSUE TITLE
False positive: wrong array stride

### ISSUE THREAD

**Issue by dragostis** [gfx-rs/naga#811]
Trying to compile the following compute shader works in 0.7 but fails in 0.8:

```glsl
#version 450
layout(local_size_x = 64) in;

struct Foo {
    uint lo;
    uint hi;
};

layout(set = 0, binding = 0) buffer FooBar {
    Foo[] foo;
};

void main() {
}
```

with:

```
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `foo.spv`
    Type [4] '' is invalid
    Array stride 8 is smaller than the base element size 16
```

**Comment by kvark** [comment]
> //TODO: we should be able to do better than this.
        const STRUCT_ALIGNMENT: u32 = 16;

**Comment by kvark** [comment]
@dragostis you can work around for now by enabling "cross" feature of wgpu-rs and not passing the `VALIDATION` flag to shader creation.
