### ISSUE TITLE
Parse shaders with Float64

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/naga#831]
Naga currently cannot parse SPIR-V shaders which use 64-bit floats:

<pre><font color="#555753">[</font>2021-05-04T23:27:13Z <font color="#C4A000">WARN </font> wgpu_core::device<font color="#555753">]</font> Failed to parse shader SPIR-V code: UnsupportedCapability(Float64)
</pre>

**Comment by JCapucho** [comment]
Closed by #1209, confirmed working on e1552fd.
