### ISSUE TITLE
InvalidEdgeClassification on collatz shader

### ISSUE THREAD

**Issue by kvark** [gfx-rs/naga#856]
https://github.com/linebender/piet-gpu/blob/master/piet-gpu-hal/examples/shader/collatz.spv

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidEdgeClassification', bin/naga.rs:116:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by raphlinus** [comment]
Possibly related, https://github.com/linebender/piet-gpu/blob/master/piet-gpu/shader/backdrop.spv gives `ControlFlowGraphCycle(220)`. Some of the others fail on atomics, but that sounds more or less expected, as atomic support is not yet complete.

**Comment by kvark** [comment]
@raphlinus thank you for the info!
If you enable "cross" feature and disable `VALIDATION` flag, you should still be able to use these shaders, as a workaround.

**Comment by MatusT** [comment]
This should be fixed by: https://github.com/gfx-rs/naga/pull/860.
The problem here is not related to ControlFlowGraphCycle(220) at all.
