### ISSUE TITLE
Receiving buffer structure size wrong with min_binding_size of unbound array, with no unbound_array

### ISSUE THREAD

**Issue by Dispersia** [gfx-rs/naga#882]
Hello, I create a minimum example here: https://github.com/Dispersia/naga_example

Error:
```
wgpu error: Validation Error
Caused by:
    In Device::create_render_pipeline
    error matching VERTEX shader requirements against the pipeline
    shader global ResourceBinding { group: 0, binding: 0 } is not available in the layout pipeline layout
    buffer structure size 80, added to one element of an unbound array, if it's the last field, ended up greater than the given `min_binding_size`
```

 If it matters, it only triggered when adding * globals.scale in the shader, but maybe naga is just removing the entire uniform since it's not used otherwise.

wgpu: 0.8.1, naga 0.4.1.

Specs: windows 10, using vulkan

**Comment by kvark** [comment]
Thank you for filing this!

I believe naga/wgpu behavior is correct here. If you look at https://gpuweb.github.io/gpuweb/wgsl/#alignment-and-size, the size of the struct is computed by aligning the end of the last member with the alignment of the struct. The alignment of the struct is the biggest alignment of it's members. For this struct, the alignment is 16, hence the whole struct size is 80.

Therefore your code needs to make sure that `struct Uniform` is 80 bytes, or at least allocate 80 bytes for it in the buffer.
Going to close the issue, but feel free to follow-up and discuss it!

**Comment by Dispersia** [comment]
Thank you for the response, that makes sense to me according to the spec, I guess I don't fully understand the optimizations that are occuring then. If a mat4x4<f32> aligns to 16, it's treating it as a 2d array instead of one contiguous, correct? If so why does the same not apply to an individual vec and its alignment is of a single element? The answer could just be because that's how GPU's work, but I'm just curious.

 On a side note though, is this something that wgpu could align for you then? I know these automatic alignments happen in other places, but I'm not sure if there is a rule when it takes care of it for you vs doesn't

**Comment by kvark** [comment]
When you are creating the buffer, there is nothing to tell us which shader-side structures are going to be in it, at which offsets, etc. So the short answer is "no" - we can't automate this part for you.
