### ISSUE TITLE
[glsl-in] Unable to parse push_constant layout

### ISSUE THREAD

**Issue by Foltik** [gfx-rs/naga#896]
```glsl
#version 450

layout(push_constant) uniform PushConstants {
    float example;
} c;

void main() {}
```
```rust
ParseError {
    kind: UnknownLayoutQualifier(
        SourceMetadata {
            start: 21,
            end: 34,
        },
        "push_constant",
    ),
}
```

**Comment by JCapucho** [comment]
Push constants are not yet supported

**Comment by JCapucho** [comment]
I won't add this for now because I don't have time, but this is an easy thing to add and I'll be willing to provide guidance if someone wants to implement it.

**Comment by Foltik** [comment]
I'll give it a shot :smile:

**Comment by JCapucho** [comment]
Cool, it should be simple just go to `parse_layout_qualifier_id` and add in the second match the `TypeQualifier::StorageClass` with `StorageClass::PushConstant`

**Comment by Foltik** [comment]
Would it make sense to also add a `TypeQualifier::Layout` with a new `StructLayout::Std430`?
