### ISSUE TITLE
[glsl-in] Implicit conversions

### ISSUE THREAD

**Issue by JCapucho** [gfx-rs/naga#900]
This is a tracking issue for implicit conversions in the glsl frontend

- [x] In function casting
This is one is the easier of the two, we have a list of conversion priority and when there is a type conflict we try to catch to the one with higher priority

<details>
<summary>example</summary>
  
```glsl
void main() {
  // float has priority greater than int
  float a = 1; // This works and 1 is casted to float
  float b = 2.0 * 1; // This also works and 1 is casted to float
  int c = 1.0; // This doesn't work because float has higher priority than int
  uint d = 1; // this works because uint has a higher priority than int
  int e = 1u; // The last line implies that this doesn't work and it's true
  vec2 f = ivec(2); // This works the same way, we only check the scalar kind
}
```
</details>

- [x] function call casting
This one is a little stranger, the idea is that if the signature matches any known definition/prototype we use it, otherwise we try a cast for all known overloads, then we can have three scenarios
- if none satisfy the priority rule we throw a error saying that there's no known function with that signature
- if we have one result it's business as usual we do the casts and call the selected overload
- if we get more a error is thrown saying that the resolution is ambiguous

<details>
<summary>example</summary>
  
```glsl
// Signature match call the second overload
void test(float a) {}
void test(int a) {}

void main() {
  test(1);
}
```

```glsl
// No signature match and no valid cast, throw error
void test(int a) {}
void test(uint a) {}

void main() {
  test(1.0);
}
```

```glsl
// No signature match but one overload satisfies the cast rules
void test(float a) {}
void test(int a) {}

void main() {
  test(1u);
}
```

```glsl
// No signature match but multiple overloads satisfy the cast rules, throw error
void test(float a) {}
void test(uint a) {}

void main() {
  test(1);
}
```
</details>

The first issue is a simple integer comparison but the second one I'm not sure about the best implementation so if anyone has any idea please leave a comment.

Our current implementation has a `HashMap` of `FunctionSignature` pointing to a function.

`FunctionSignature` is defined has
```
struct FunctionSignature {
  name: String,
  parameters: Vec<Handle<Type>>
}
```

**Comment by jakobhellermann** [comment]
Another case where implicit conversions aren't currently done is `vec4 vec = { 1, 1.0, 1.0, 1.0 };` which logs
```glsl
[ERROR naga::valid::compose] Vector component[0] type Scalar { kind: Sint, width: 4 }
Constant [5] '' is invalid: 
	Composing 0's component type is not expected
```

**Comment by JCapucho** [comment]
There are still some parts that do not handle implicit conversions yet

**Comment by jakobhellermann** [comment]
Also while a float and a vec3 can be multiplied together, adding or subtracting them doesn't work:
```glsl
float scalar = 1.0;
vec3 vector = vec3(1.0);

vec3 a = scalar + vector;
vec3 b = vector + scalar;
// WORKS: vec3 c = vector * scalar;
// WORKS: vec3 d = scalar * vector;
```

```
[ERRORnaga::valid::expression] Left: Load { pointer: [2] } of type Scalar { kind: Float, width: 4 }
[ERROR naga::valid::expression] Right: Load { pointer: [5] } of type Vector { size: Tri, kind: Float, width: 4 }
Function [1] 'vector_scalar' is invalid: 
	Expression [8] is invalid
	Operation Add can't work with [6] and [7]
thread 'main' panicked at 'Output has no extension?', cli/src/main.rs:214:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by JCapucho** [comment]
If this is allowed in glsl than the problem is that Naga validation doesn't allow it or we need to handle this cases explicitly

**Comment by JCapucho** [comment]
> Also while a float and a vec3 can be multiplied together, adding or subtracting them doesn't work:
> 
> ```glsl
> float scalar = 1.0;
> vec3 vector = vec3(1.0);
> 
> vec3 a = scalar + vector;
> vec3 b = vector + scalar;
> // WORKS: vec3 c = vector * scalar;
> // WORKS: vec3 d = scalar * vector;
> ```
> 
> ```
> [ERROR naga::valid::expression] Left: Load { pointer: [2] } of type Scalar { kind: Float, width: 4 }
> [ERROR naga::valid::expression] Right: Load { pointer: [5] } of type Vector { size: Tri, kind: Float, width: 4 }
> Function [1] 'vector_scalar' is invalid: 
> 	Expression [8] is invalid
> 	Operation Add can't work with [6] and [7]
> thread 'main' panicked at 'Output has no extension?', cli/src/main.rs:214:14
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

@jakobhellermann should be fixed
