### ISSUE TITLE
[glsl-in] invalid offset calculation

### ISSUE THREAD

**Issue by jakobhellermann** [gfx-rs/naga#906]
When giving naga the input
```glsl
layout(set = 0, binding = 0) uniform Foo {
    vec4 pos;
    vec4 pos2;
    vec4 pos3;
};
```
it will generate the struct
```rust

Struct {
    top_level: true,
    members: [
    	StructMember {
    		name: Some(
    			"pos",
    		),
    		ty: [1],
    		binding: None,
    		offset: 0,
    	},
    	StructMember {
    		name: Some(
    			"pos2",
    		),
    		ty: [1],
    		binding: None,
    		offset: 16,
    	},
    	StructMember {
    		name: Some(
    			"pos3",
    		),
    		ty: [1],
    		binding: None,
    		offset: 16,
    	},
    ],
    span: 16,
}
```

and errors on validation:
```
Type [2] 'Foo' is invalid:
        Structure member[1] at 16 and size 16 crosses the structure boundary
```

The offsets currently [all use the span](https://github.com/gfx-rs/naga/blob/f57739d30bf5b1075ba4ab8ed44dfd3dc51259d5/src/front/glsl/parser.rs#L839) at the time of parsing. Instead I believe after the fields are collected, each one should get `offset: field_index * span`.

**Comment by JCapucho** [comment]
This is a very dumb mistake on my part I'll bundle the fix with the next wave of validation fixes

**Comment by jakobhellermann** [comment]
I'm trying to fix it right now but I'm confused about what the right way should be. Having the offsets `0, 16, 32` still reproduces the error. The validation code checks that `member.offset + member_size <= span`,  which doesn't work when the struct span, member offset and member size are all 16.

Is the `span` of a struct its size or the size of its biggest member or something else entirely?

**Comment by JCapucho** [comment]
Span is the size of the entire struct

**Comment by JCapucho** [comment]
The fix should only be changing the assignment within the loop to a `+=`

**Comment by jakobhellermann** [comment]
What about
```glsl
layout(set = 0, binding = 0) uniform Foo {
    vec2 pos;
    vec4 pos2;
    vec4 pos3;
};
```
When changing to `+=` I get 
```
Global variable [1] '' is invalid:
        Alignment requirements for this storage class are not met by [3]
        The struct span 40, is not a multiple of the required alignment 16
```

**Comment by jakobhellermann** [comment]
*reading https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf Standard Uniform Block Layout

**Comment by JCapucho** [comment]
That's a more long term solution if you are willing to put in the work :)

**Comment by magcius** [comment]
There are a lot of edge cases here. For instance, user-defined structs don't have a singular span, since their members are collectively laid out according to the layout:

```glsl

struct BunchaFloats {
    float v[5];
};

layout(std140) uniform TestStd140 {
    float test_float; // +0x00
    BunchaFloats test_struct; // +0x10
};

layout(scalar) uniform TestScalar {
    float test_float; // +0x00
    BunchaFloats test_struct; // +0x04
};
```

Here, `BunchaFloats` is 5 vec4's large in std140, taking up the area between +0x10 and +0x60, but in the scalar layout case, each member is 5 float's large, and the base alignment is now that of a single float, so it takes up the space between +0x04 and +0x18.

This means that you can't have a single "span" for a user struct, it depends on the packing, which isn't specified by the parent.

**Comment by JCapucho** [comment]
@jakobhellermann are you working on this, if not or you no longer have the time I'll do it since it has been one of the errors that's being hit by more complicated shaders.

**Comment by jakobhellermann** [comment]
I have some local experiments but nothing worth PRing. Feel free to take this on, thanks for your work.
