### ISSUE TITLE
Statements are incorrectly ordered from `mtl` and `glsl` backends.

### ISSUE THREAD

**Issue by paulgb** [gfx-rs/naga#910]
I've created a gist with steps to reproduce [here](https://gist.github.com/paulgb/a8f705d9e80bbfd0ca42410086a5c04f).

The input WGSL code is:

    [...snip; full code in linked repo]
    var a: f32 = 0.0;
    let b: f32 = a;
    a = 1.0;
    v_data.data = b;
    [snip...]

The correct resulting value of `v_data.data` is `0.0`.

The code returned by `naga` for `metal` is:

    [snip]
    float a = 0.0;
    a = 1.0;
    v_data.data = a;
    return;
    [snip...]

The resulting value of `v_data.data` is `1.0`. The value `b` is written out entirely, but instead of taking on the value at the time of its assignment, it takes on the value of `a` at the end.

The `.spv` file itself appears to be ordered correctly, so the issue appears to occur between loading the `.spv` file and generating the output in the backend. To confirm this, I used `spirv-cross` to generate metal and glsl output from the same input `.spv` returned by `naga`; these files are correctly ordered.

I'm planning to keep digging into this, but I wanted to raise it as an issue in case it's come up elsewhere.

In case anyone needs a workaround, changing `let` expressions to `var` expressions seems to fix it, possibly with a small performance penalty.

**Comment by kvark** [comment]
Thank you for filing this!
So the frontend emits the expressions correctly, but the backends decide to "inline" it instead. Unfortunately, inlining means changing the region, technically, where it's computed, and it gets re-ordered with a `Store`.
Your #914 fix should do, it's consistent with `ImageLoad`.

**Comment by Gordon-F** [comment]
@kvark What if we fix this problem on wgsl front end side? It seems that this problem occurs only for wgsl `let`. Other fronts generate local variables and store statements.

What if we will do the same logic for `let`, that we do for `var` if rvalue is `Load` expression?

For example, this line:
```wgsl
let b: f32 = a;
```

Will generate not only `Emit` statement but additional `Local Variable ` expression and `Store` statement? In this case, we still have redundant expressions,  but much less than now.

**Comment by kvark** [comment]
This isn't just WGSL, it's also all of SPIR-V. If we create a variable for every SPIR-V ID, that would be quite silly.

**Comment by Gordon-F** [comment]
@kvark Based on generated shader, `spv-in` already handle it.

```glsl
#version 450

layout(location = 0) in vec4 color;

void main() {
    float xxx = color.x;
    gl_Position = vec4(xxx);
}
```

```wgsl
fn main1() {
    var xxx: f32;

    xxx = color1[0u];
    perVertexStruct.gl_Position = vec4<f32>(xxx);
    return;
}
```

```ir
local_variables: {
                [1]: LocalVariable {
                    name: Some(
                        "xxx",
                    ),
                    ty: [1],
                    init: None,
                },
            },

[10]: LocalVariable(
                    [1],
                ),
                [11]: Access {
                    base: [2],
                    index: [7],
                },
                [12]: Load {
                    pointer: [11],
                },

Store {
                    pointer: [10],
                    value: [12],
                },
```
