### ISSUE TITLE
Validate that variable name does not clash with builtin function

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/naga#913]
When I write WGSL like this:
```
let distance = ...
let t = distance / sigma;
```
I get an error that a paren is expected where the `/` is, because `distance` is recognised as a builtin function. I would expect this to either override the name, or to fail at the declaration of `let distance`.

Using latest `master`.

**Comment by jimblandy** [comment]
WGSL [says](https://gpuweb.github.io/gpuweb/wgsl/#declaration-and-scope) that, if the `let` declaration is local to a function, it should override the global definition. So this code should be permitted, with the apparently intended interpretation.

**Comment by jimblandy** [comment]
Hmm, on Naga master (48363fc), I tried the following:
```
fn f(x: f32) -> f32 {
   let distance = x;
   const factor: f32 = 2.0;
   return distance / factor;
}
```
and got this error:
```
error: call to local `const(..)` can't be resolved

thread 'main' panicked at 'unable to parse WGSL', bin/naga.rs:126:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is still wrong, but it's different from what you cited.

Are you using gfx-rs master, or are you running the naga bin directly? gfx-rs lags behind naga master; it uses a specific tag, unless you fiddle with the `Cargo.toml` for local development.

**Comment by almarklein** [comment]
I used naga master

**Comment by almarklein** [comment]
If I you `const` to `let` there, you should get my error :)

**Comment by jimblandy** [comment]
> If I you change `const` to `let` there, you should get my error :)

True! There's something pretty twisted going on in there.

Right now, the lists of built-in definitions are scattered across various functions like `map_standard_fun` and `map_derivative_axis`, and even `parse_local_function_call`.

The way I'd really like to do this instead is by introducing a new `LookupIdentifier` enum that can represent any definition in scope for an identifier, and then use something like [`phf`](https://docs.rs/phf/0.8.0/phf/) to generate a lookup table at compile time for the built-in definitions, mapping strings to `LookupIdentifier` values. Then it would only take one query to handle all built-in definitions, and we could just match to handle it, rather than having chains of `if let` statements as we do now.

**Comment by jimblandy** [comment]
Not that we need more test cases for this, but I just happened to run into this myself:

It's even more fun if you declare a variable with the same name as a type!
```
fn f() {
   var array: array<f32, 1>;

   array = array<f32, 1>(10);
}
```

This produces:
```
error: expected paren, found ','
  ┌─ wgsl:4:21
  │
4 │    array = array<f32, 1>(10);
  │                     ^ expected paren
```

What's going on is that we consult `ctx.lookup_ident` [here](https://github.com/gfx-rs/naga/blob/48363fcef1cb171792d6f69270b9daee42396731/src/front/wgsl/mod.rs#L1209), find a binding, and then proceed to parse the rest as an expression. `<` becomes a relational operator.

**Comment by jimblandy** [comment]
I think the WGSL spec is unclear as to whether this should be permitted:

```
fn f(x: f32) -> f32 {
   let distance = x;
   let factor: f32 = 2.0;
   return distance / factor;
}
```

However, both Naga and Tint permit this program. I've filed gpuweb/gpuweb#2619 about this.

**Comment by jimblandy** [comment]
Naga now handles this program better:

```
fn f() {
   var array: array<f32, 1>;

   array = array<f32, 1>(10);
}
```

It says:

```
error: name `array` is a reserved keyword
  ┌─ 913.wgsl:2:8
  │
2 │    var array: array<f32, 1>;
  │        ^^^^^ definition of `array`
```

which makes total sense.

Since I think Naga (together with Tint) is implementing a reasonable interpretation of a currently unclear spec, I'm closing this as fixed.
