### ISSUE TITLE
call to local atomicMax cannot be resolved

### ISSUE THREAD

**Issue by fctorial** [gfx-rs/naga#956]
I'm trying to compile this program using naga:

```
[[group(0), binding(1)]] var<storage> result : [[access(write)]] u32;

[[stage(compute), workgroup_size(1)]]
fn main() {
    atomicMax(result, 12u);
}
```

The compilation fails with an error saying `atomicMax not found`:

```
$ ~/.cargo/bin/naga ./shader.wgsl ./shader.spv
error: call to local `atomicMax(..)` can't be resolved

thread 'main' panicked at 'unable to parse WGSL', /home/fctorial/.cargo/registry/src/github.com-1ecc6299db9ec823/naga-0.4.2/bin/naga.rs:122:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Even though `atomicMax` is a part of wgsl spec:

https://www.w3.org/TR/WGSL/#atomic-store

**Comment by JCapucho** [comment]
Atomics aren't implemented yet, see #929

**Comment by JCapucho** [comment]
Please don't close issues that aren't yet resolved as other people may hit them and create duplicate issues

**Comment by kvark** [comment]
@JCapucho it is a duplicate though, so we generally close those. We don't want any traffic on this issue in particular, since that would mean the information is no longer in one place.
We should expect users to either discover the atomic issue directly, or to see this in the closed issues list.
