### ISSUE TITLE
wgsl-in: access chains broken up by loads

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/naga#959]
In our SPIR-V back end, we try to gather up chains of `Access` and `AccessIndex` operations into a single SPIR-V `OpAccessChain` instruction. This is done by `cache_expression_value` and `is_intermediate`, with `write_expression_pointer` putting together the combined insn. But when indexing matrices, at least, the WGSL front end tends to generate `Access` / `Load` / `Access` expressions, and that intermediate `Load` breaks the chain, so we generate an `OpAccessChain` followed by an `OpVectorExtractDynamic`.

For bounds checks, it's not hard for me to generate a single branch per `OpAccessChain` or `OpVectorExtractDynamic`. But I'll generate two bounds check branches if they are two separate instructions. The code needed to consolidate those into a single branch is the same code needed to consolidate them into a single `OpAccessChain`.

So ideally, we should fix the WGSL front end to put off the `Load` until the end, and then we'll get a single `OpAccessChain` and a single bounds check branch.

**Comment by kvark** [comment]
IIRC, the original reasoning for injecting a `Load` there was that I wasn't sure if it's valid to point to parts of matrices/vectors in WGSL at all. I think it was clarified that it's possible, so we should go ahead and make the generated IR better. May also improve perf a bit!

**Comment by teoxoy** [comment]
I think we can close this now since #1360 has been merged.

**Comment by kvark** [comment]
Please reopen if needed!
