### ISSUE TITLE
Reorganize test snapshot folder

### ISSUE THREAD

**Issue by Gordon-F** [gfx-rs/naga#976]
Since the number of tests is increasing, so I suggest moving test snapshots to subfolders for each front/back.

As is:
```
./test/in
./test/out
```
To be:
```
./test/in/wgsl
./test/in/spv
...

./test/out/wgsl
./test/out/glsl
...
```

**Comment by kvark** [comment]
Thank you! I think some reorg will be useful.
I would prefer to make one slight tweak to your suggestion though. Following #752, it's natural to treat WGSL as a privileged input/output. So can we have it in the root?
```
test/in/xxx.wgsl
test/in/spv/yyy.spv
test/out/yyy.wgsl
test/out/glsl/xxx.glsl
```

**Comment by Gordon-F** [comment]
@kvark What we should do with `*.param.ron` files? Leave them at the root directory with `wgsl` shaders?

**Comment by kvark** [comment]
Let's keep them in the same place as the files they describe. So the SPV inputs will have the param ron in their tests/in/spv/
